nextflow-io/nextflow

- src/main/groovy/nextflow/util/LoggerHelper.groovy
Very nit-picky grammatical corrections.
> Tiny corrections to error messages

- README.md
> Update README: Add syntax coloring

- src/main/groovy/nextflow/executor/SlurmExecutor.groovy
Do not work -- Reverts nextflow-io/nextflow#192
> Revert "Allow sbatch to only output the jobid by itself"

- nextflow
> Silence mkdir error if NXF_HOME not writable

- COPYING
> Update to COPYING

- src/main/groovy/nextflow/executor/NqsiiExecutor.groovy
- src/main/groovy/nextflow/processor/ProcessFactory.groovy
- src/test/groovy/nextflow/executor/NqsiiExecutorTest.groovy
Added executor and tests for NQSII. No documentation for NQSII is available on the web it seems.
> Add executor for NQSII, queuing system used on NEC clusters.

- src/main/groovy/nextflow/util/NameGenerator.groovy
A few contributions for workflow names.
Adjectives taken from a [very silly game](http://beta.tallphil.co.uk/firstword_secondword/) that I wrote as a teenager.
> Added new adjectives and famous names.

- src/main/groovy/nextflow/util/NameGenerator.groovy
> more famous scientist

- src/main/groovy/nextflow/util/NameGenerator.groovy
Add Belgian/Flemish known figures.
> Add Belgian/Flemish known figures.

- docs/awscloud.rst
Might be slightly more clear wording.
> AWS doc change

- docs/tracing.rst
- src/main/groovy/nextflow/processor/TaskHandler.groovy
- src/main/groovy/nextflow/trace/TraceRecord.groovy
- src/test/groovy/nextflow/processor/TaskHandlerTest.groovy
- src/test/groovy/nextflow/trace/TraceFileObserverTest.groovy
- src/test/groovy/nextflow/trace/TraceRecordTest.groovy
Ok, here is a hopefully clean commit without all of my garbage commits and also without Const.  Sorry for the hassle!
> Added queue to TraceRecord along with tests and docs

- src/main/groovy/nextflow/extension/DataflowExtensions.groovy
- src/main/groovy/nextflow/extension/RandomSampleOp.groovy
- src/test/groovy/nextflow/extension/RandomSampleTest.groovy
That should allow resuming cached pipelines.
> Added seed parameter to randomSample (#410)

- docs/executor.rst
Link to SLURM seems out of date
> Updated link to SLURM

- docs/operator.rst
> Fixed typos in docs/operator.rst

- docs/process.rst
I learned this from @ewels. Would be nice to have this in the documentation in case it is intentional behavior.
> Document how to not publish a file

- docs/executor.rst
Added some documentation on how to use the Nextflow branch supporting AWS Batch, the configuration parameters and the instructions to build a custom AMI.
> Aws batch documentation

- src/main/groovy/nextflow/util/NameGenerator.groovy
- sorted both lists
- added names: `cantor`,`carlsson`,`celsius`,`ekeblad`,`gautier`,`hilbert`,`linnaeus`,`stone`,`tuckerman`
- code polishing, remove comma after last name.
Don't know what to do with some duplicates:
`bartik` and `jennings` refers both to the same person, I propose to remove `jennings`
`franklin` refers to both Benjamin and Rosalind, `rosalind` obviously refers to Rosalind, but as it's her first name I propose to remove it.
> Added some scientists

- src/main/resources/nextflow/trace/ReportTemplate.html
- src/main/resources/nextflow/trace/assets/ReportTemplate.js
* New plot for % of allocated time used, styled like the other plots
* Reordered table columns so that they're easier to read and compare
* More styling and tidying (eg. prettier navbar)
Ok, I think I'm happy with this now if you are @pditommaso!
> Html trace

- src/main/resources/nextflow/trace/ReportTemplate.html
- src/main/resources/nextflow/trace/assets/ReportTemplate.js
> Time plot: Don't show % allocated if there is no allocation time data.

- src/main/resources/nextflow/trace/ReportTemplate.html
- src/main/resources/nextflow/trace/assets/ReportTemplate.js
Submitting now for speed and convenience, not yet tested. Will try to take a look now.
Phil
> Add dropdown to choose whether values in tasks table should be human readable

- src/main/groovy/nextflow/cli/CliOptions.groovy
- src/main/groovy/nextflow/cli/Launcher.groovy
- src/main/groovy/nextflow/util/LoggerHelper.groovy
Hi! Here are the changes to add syslogappender for issue #330. Fairly basic right now but let me know if any changes should be made.
Thanks!
> Refactor to add syslog appender #330

- src/main/groovy/nextflow/util/LoggerHelper.groovy
@pditommaso hi! Here is the fix for what is mentioned in #330 
Thanks!
> Refactor to fix syslog option.

- docs/basic.rst
- docs/getstarted.rst
- docs/script.rst
I initially intended just to fix some hyperlinks in the documentation, but then made time to do some copy editing that, I hope, results in a somewhat more idiomatic English style. I will make inline comments to explain some choices and am happy to answer any questions. If this is useful, I could possibly work further into other sections of the docs.
> Copy editing, fixed hyperlinks

- docs/metadata.rst
> Typo in Workflow Introspection documentation

- README.md
Just a few small edits to correct the English.
> fix some grammar errors in readme docs

- docs/conda.rst
- docs/config.rst
I have added a section to the Conda docs describing the use of profiles as a best practices, and mentioning that Conda cannot be disabled.
> Conda docs 

- docs/config.rst
Updated two dead docker links.
> Updated docker links

- docs/awscloud.rst
Hi Paolo,
I took the liberty of cleaning up some formatting issues with the AWS Batch documentation section and added a bit of clarification.  Hope this helps!
thanks,
Mike
> Cleaned up the AWS Batch documentation a bit

- docs/config.rst
- Add doc about manifest.nextflowVersion cf #752
> Added nextflowVersion documentation

- docs/tracing.rst
> Add weblog example documentation

- docs/cli.rst
A stub of some of the CLI commands of Nextflow #950
> added a stub of cli docs

- docs/singularity.rst
Added singularity library (again) and removed docker2singularity mention.
> Singularity docs

- docs/basic.rst
- docs/script.rst
> Updated basic documentation

- docs/singularity.rst
Fix syntax error in Singularity containers doc file.
> DOC: Fix syntax error in Singularity containers doc file.

- modules/nextflow/src/main/groovy/nextflow/container/ContainerHandler.groovy
This options add docker-daemon support. Thread: https://twitter.com/SingularityApp/status/1097199509677826049 Tested with Singularity 3.0.3
> Adding docker-daemon Singularity support

- README.md
draft updated readme
Signed-off-by: KevinSayers <sayerskt@gmail.com>
> new signed readme

- docs/tracing.rst
- modules/nextflow/src/main/groovy/nextflow/Const.groovy
- modules/nextflow/src/main/groovy/nextflow/trace/WebLogObserver.groovy
- modules/nextflow/src/test/groovy/nextflow/trace/WebLogObserverTest.groovy
> Provides workflow metadata in weblog message on workflow submission event

- modules/nextflow/src/main/groovy/nextflow/k8s/K8sTaskHandler.groovy
- modules/nextflow/src/main/groovy/nextflow/k8s/client/K8sResponseException.groovy
- modules/nextflow/src/test/groovy/nextflow/k8s/K8sTaskHandlerTest.groovy
- modules/nextflow/src/test/groovy/nextflow/k8s/client/K8sResponseExceptionTest.groovy
fix for issue: https://github.com/nextflow-io/nextflow/issues/1255
> K8s Taskhandler updates its status correctly to 'RUNNING'

- modules/nextflow/src/main/groovy/nextflow/cloud/aws/AmazonPriceReader.groovy
Signed-off-by: Chenhao Li <lichenhao.sg@gmail.com>
> Adding ENDPOINT support for cn regions.

- docs/google.rst
Add details and links which clarify the difference between location (Cloud Life Sciences API location) and region (Compute Engine region).
> Update google.rst to clarify location v. region

- README.md
Changed Google Genomics Pipelines to Cloud Life Sciences
> Update Google docs

- modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy
- modules/nextflow/src/test/groovy/nextflow/k8s/model/PodSpecBuilderTest.groovy
This PR proposes automated truncation of labels for k8s where they exceed the 63 character limit, see https://github.com/nextflow-io/nextflow/issues/1577.
> [WIP] Truncate labels for k8s

- modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy
- modules/nextflow/src/test/groovy/nextflow/k8s/model/PodSpecBuilderTest.groovy
See https://github.com/nextflow-io/nextflow/issues/1647 for details.
> Fix for feature 1647 that allows non gpu k8s accelerator resources.

- nextflow
Signed-off-by: Edmund Miller <edmund.a.miller@protonmail.com>
Close #1598 
Open to discussing the fix, just looking to help out and get involved!
> Use current environment bash (#1598)

- modules/nf-google/src/main/nextflow/cloud/google/lifesciences/GoogleLifeSciencesHelper.groovy
Signed-off-by: Timothy Jennison <tjennison@google.com>
> Fix unexpected default GLS action flags

- docs/operator.rst
> Minor typo in docs.

- docs/charliecloud.rst
- docs/config.rst
- modules/nextflow/src/main/groovy/nextflow/Session.groovy
- modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy
- modules/nextflow/src/main/groovy/nextflow/cli/Launcher.groovy
- modules/nextflow/src/main/groovy/nextflow/config/ConfigBuilder.groovy
- modules/nextflow/src/main/groovy/nextflow/container/CharliecloudBuilder.groovy
- modules/nextflow/src/main/groovy/nextflow/container/CharliecloudCache.groovy
- modules/nextflow/src/main/groovy/nextflow/container/ContainerHandler.groovy
- modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy
- modules/nextflow/src/test/groovy/nextflow/SessionTest.groovy
- modules/nextflow/src/test/groovy/nextflow/cli/LauncherTest.groovy
- modules/nextflow/src/test/groovy/nextflow/container/CharliecloudBuilderTest.groovy
- modules/nextflow/src/test/groovy/nextflow/container/CharliecloudCacheTest.groovy
- modules/nextflow/src/test/groovy/nextflow/container/ContainerHandlerTest.groovy
This supersedes https://github.com/nextflow-io/nextflow/pull/1712 (I rebased against master and cherry-picked the commits by @tbugfinder in an attempt to make the DCO bot happy)
> add support for charliecloud container engine

- modules/nextflow/src/main/groovy/nextflow/container/ContainerBuilder.groovy
- modules/nextflow/src/main/groovy/nextflow/container/DockerBuilder.groovy
- modules/nextflow/src/main/groovy/nextflow/container/PodmanBuilder.groovy
- modules/nextflow/src/main/groovy/nextflow/container/SingularityBuilder.groovy
- modules/nextflow/src/main/groovy/nextflow/container/UdockerBuilder.groovy
- modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy
- modules/nextflow/src/main/groovy/nextflow/processor/TaskBean.groovy
- modules/nextflow/src/test/groovy/nextflow/cli/CmdConfigTest.groovy
- modules/nextflow/src/test/groovy/nextflow/container/DockerBuilderTest.groovy
- modules/nextflow/src/test/groovy/nextflow/container/PodmanBuilderTest.groovy
- modules/nextflow/src/test/groovy/nextflow/container/SingularityBuilderTest.groovy
- modules/nextflow/src/test/groovy/nextflow/container/UdockerBuilderTest.groovy
- modules/nextflow/src/test/groovy/nextflow/executor/BashWrapperBuilderTest.groovy
This PR addresses the discussion done here https://github.com/nextflow-io/nextflow/issues/1832
`cpus` throttling support in 
- `docker` https://docs.docker.com/config/containers/resource_constraints/#cpu 
- `podman` http://docs.podman.io/en/latest/markdown/podman-run.1.html#cpu-quota-limit 
- `singularity` https://sylabs.io/guides/3.3/user-guide/cli/singularity_exec.html?highlight=cpu
> Update CPU and RAM for containers

- modules/nextflow/src/main/groovy/nextflow/config/ConfigBuilder.groovy
- modules/nextflow/src/test/groovy/nextflow/config/ConfigBuilderTest.groovy
Adds the option to alse use variables (following the format `${variable_name}`) when defining parameter values at the JSON or YAML parameters file.
> Allow variable binding also at params file

- docs/azure.rst
After running some tests on pre-existing named pools in Azure, I found out some requirements not listed in the current documentation but needed by Nextflow to use these pools as queues where to submit tasks.
> List requirements on pre-existing named pools in Azure.

- docs/operator.rst
Fix some usages of onComplete. 
Adjust formatting and typos.
> Improve documentation for Operators.

- modules/nextflow/src/main/groovy/nextflow/file/FileCollector.groovy
Signed-off-by: Chase Clark <cmclark8@wisc.edu>
> Fix typo: 'Retrivied' to 'Retrieved

- docs/kubernetes.rst
This PR addresses  https://github.com/nextflow-io/nextflow/issues/1823
> Add a note for multiple volumes in K8S

- modules/nextflow/src/main/groovy/nextflow/k8s/client/K8sClient.groovy
- modules/nextflow/src/test/groovy/nextflow/k8s/client/K8sClientTest.groovy
To fix this bug I add an additional check to checkInvalidWaitingState that checks if the pod phase is Failed and throw an exception if it is. A test validating this behavior has been included and I have confirmed that the test fails without this fix.
> Fixes bug 2428 

- docs/singularity.rst
Small PR to fix the singularity docs.
> Fix singularity docs

- plugins/nf-azure/src/main/nextflow/cloud/azure/file/AzBashLib.groovy
- plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzFileCopyStrategyTest.groovy
- plugins/nf-azure/src/test/nextflow/cloud/azure/file/AzBashLibTest.groovy
- validation/test-subdirs.nf
This PR fixes the issue described in #2577
> Fix upload of nested directory outputs on azure

- docs/azure.rst
A clarification about how to access to File share dirs in the Azure doc.
> Explain how to access to File share dirs.

- docs/process.rst
- modules/nextflow/src/main/groovy/nextflow/k8s/model/PodOptions.groovy
- modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy
- modules/nextflow/src/test/groovy/nextflow/k8s/K8sDriverLauncherTest.groovy
- modules/nextflow/src/test/groovy/nextflow/k8s/K8sTaskHandlerTest.groovy
- modules/nextflow/src/test/groovy/nextflow/k8s/model/PodOptionsTest.groovy
- modules/nextflow/src/test/groovy/nextflow/k8s/model/PodSpecBuilderTest.groovy
Adds the `priorityClassName` pod option. Also cleaned up some of the k8s tests.
Closes #1845
> Added priorityClassName pod option

- modules/nextflow/src/main/groovy/nextflow/k8s/client/K8sClient.groovy
- modules/nextflow/src/test/groovy/nextflow/k8s/client/K8sClientTest.groovy
Supersedes https://github.com/nextflow-io/nextflow/pull/2404
> k8s executor: throw NodeTerminationException on node shutdown

- docs/google.rst
Added some notes about preemptible VMs and resource quotas on Google Cloud.
> Update google cloud docs

- modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy
- modules/nextflow/src/test/groovy/nextflow/executor/BashWrapperBuilderTest.groovy
Signed-off-by: Jorge Aguilera jorge.aguilera@seqera.io
> bugfix: process output 'env' as array

- modules/nextflow/src/main/groovy/nextflow/config/ConfigBase.groovy
When using Tower (or trace enabled) Nextflow is reading the `includeConfig` file twice. 
First time, it is read as expected when building the config map here:
https://github.com/nextflow-io/nextflow/blob/787a1fd84aead0f285ab94ab8a328093cbe0ec84/modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy#L287
and the second time is read when building the resolved config string here:
https://github.com/nextflow-io/nextflow/blob/787a1fd84aead0f285ab94ab8a328093cbe0ec84/modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy#L306-L307
It is not possible to reuse the same config object when building the resolve configuration due to the use of the method `setShowClosures` on the second builder.
https://github.com/nextflow-io/nextflow/blob/21792bf727f668c50a6155153b208a0faae88d6c/modules/next …
> Avoid to read an included config file more than once

- modules/nextflow/src/main/groovy/nextflow/k8s/K8sDriverLauncher.groovy
- wait for pod to stop running before shutdown.
- Patch for Issue #2654
> Force kuberun to wait for pods before shutdown

- plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy
> Fix log message in nf-azure.

- docs/script.rst
> Document task object

- docs/basic.rst
- docs/channel.rst
- docs/cli.rst
- docs/conda.rst
- docs/conf.py
- docs/config.rst
- docs/container.rst
- docs/dsl2.rst
- docs/example.rst
- docs/faq.rst
- docs/getstarted.rst
- docs/index.rst
- docs/mail.rst
- docs/metadata.rst
- docs/metrics.rst
- docs/operator.rst
- docs/plugins.rst
- docs/process.rst
- docs/script.rst
- docs/secrets.rst
- docs/sharing.rst
- docs/tracing.rst
This PR includes the following changes:
- Edit code blocks for consistent formatting
- Edit tips, notes, warnings for consistency
- Remove notes about version requirements for 0.x versions
- General language and formatting improvements
> Documentation -- general improvements

- modules/nextflow/build.gradle
- modules/nextflow/src/main/groovy/nextflow/script/WorkflowNotifier.groovy
- modules/nextflow/src/test/groovy/nextflow/conda/CondaCacheTest.groovy
- modules/nextflow/src/test/groovy/nextflow/container/ContainerHandlerTest.groovy
- modules/nextflow/src/test/groovy/nextflow/datasource/SraExplorerTest.groovy
- modules/nextflow/src/test/groovy/nextflow/executor/BashWrapperBuilderTest.groovy
- modules/nextflow/src/test/groovy/nextflow/executor/LsfExecutorTest.groovy
- modules/nextflow/src/test/groovy/nextflow/k8s/K8sDriverLauncherTest.groovy
- modules/nextflow/src/test/groovy/nextflow/k8s/K8sTaskHandlerTest.groovy
- modules/nextflow/src/test/groovy/nextflow/processor/TaskProcessorTest.groovy
- modules/nextflow/src/test/groovy/nextflow/scm/RepositoryProviderTest.groovy
- modules/nextflow/src/test/groovy/nextflow/script/WorkflowNotifierTest.groovy
- modules/nextflow/src/test/groovy/nextflow/trace/TimelineObserverTest.groovy
- modules/nextflow/src/test/groovy/nextflow/trace/WebLogObserverTest.groovy
- plugins/nf-amazon/src/test/nextflow/cloud/aws/batch/AwsBatchTaskHandlerTest.groovy
- plugins/nf-google/src/test/nextflow/cloud/google/lifesciences/GoogleLifeSciencesExecutorTest.groovy
- plugins/nf-google/src/test/nextflow/cloud/google/lifesciences/GoogleLifeSciencesTaskHandlerTest.groovy
- plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerClient.groovy
- plugins/nf-tower/src/test/io/seqera/tower/plugin/TowerClientTest.groovy
This PR upgrades Spock testing library to version 2.1.
> Upgrage tests to spock 2.1

- modules/nextflow/src/main/groovy/nextflow/scm/AzureRepositoryProvider.groovy
- modules/nextflow/src/test/groovy/nextflow/scm/AzureRepositoryProviderTest.groovy
> bugfix: include revision in the Azure Repos provider if specified

- .github/workflows/build.yml
changed pipeline from java 17 to 18
> feature: add pipeline for java 18

- CONTRIBUTING.md
- README.md
I recently had to reimport the project in IntelliJ IDEA. Some instructions were outdated and I fixed them here.
> Improve instructions for contributors

- modules/nextflow/src/main/groovy/nextflow/NextflowMeta.groovy
- modules/nextflow/src/test/groovy/nextflow/NextflowMetaTest.groovy
Fixes https://github.com/nextflow-io/nextflow/issues/2874
Signed-off-by: JoseEspinosa <kadomu@gmail.com>
> Changed pattern to avoid problems with workflow.foo {} instances in DSL1 scripts

- modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy
- modules/nextflow/src/main/groovy/nextflow/scm/AssetManager.groovy
- modules/nextflow/src/test/groovy/nextflow/scm/AssetManagerTest.groovy
Tested against a Github repo but must also work with other repositories as revision feature is implemented in all of them
closes #1988
> gets pipeline metainformation from revision if specified

- modules/nextflow/src/main/groovy/nextflow/executor/GridTaskHandler.groovy
- modules/nextflow/src/test/groovy/nextflow/executor/GridTaskHandlerTest.groovy
> Fix missing err message on submit failure

- modules/nextflow/src/main/groovy/nextflow/config/ConfigBuilder.groovy
- modules/nextflow/src/main/groovy/nextflow/scm/ProviderConfig.groovy
- modules/nf-commons/src/main/nextflow/util/StringUtils.groovy
- modules/nf-commons/src/test/nextflow/util/StringUtilsTest.groovy
search and replace for password, token, secret and licence keywords as key:value string
closes #2905
> feature: stripe sensitive data into strings

- docs/basic.rst
> bugfix: fix documentation in channel example [ci fast]

- modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy
- modules/nextflow/src/test/groovy/nextflow/k8s/K8sDriverLauncherTest.groovy
- modules/nextflow/src/test/groovy/nextflow/k8s/model/PodSpecBuilderTest.groovy
Signed-off-by: romanaduraciova <duraciovar@gmail.com>
> added labels and annotations for job

- docs/azure.rst
Following up this [discussion](https://github.com/nextflow-io/nextflow/discussions/2958), this PR provides an expanded explanation of what should be used as value for the ``location`` setting in nf-azure.
> Improve doc for azure location.

- docs/config.rst
- modules/nextflow/src/main/groovy/nextflow/executor/LsfExecutor.groovy
- modules/nextflow/src/test/groovy/nextflow/executor/LsfExecutorTest.groovy
This PR improves the LSF configation 
Signed-off-by: Ben Sherman <bentshermann@gmail.com>
Co-authored-by: Paolo Di Tommaso <paolo.ditommaso@gmail.com>
> Allow to override lsf.conf settings with nextflow config #2862

- docs/google.rst
- plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy
- plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchTaskHandlerTest.groovy
> Add disk directive to google batch

- plugins/nf-amazon/src/main/com/upplication/s3fs/AmazonS3Client.java
> bugfix: instantiate an S3 ObjectMetada if not present

- docs/config.rst
> Add warning to env config docs

- modules/nextflow/src/test/groovy/nextflow/ChannelTest.groovy
- modules/nf-commons/src/main/nextflow/file/FileHelper.groovy
> bugfix: emit relative path when relative parameter is set

- docs/config.rst
- plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchTaskHandler.groovy
- plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsOptions.groovy
- plugins/nf-amazon/src/test/nextflow/cloud/aws/batch/AwsBatchTaskHandlerTest.groovy
> Add share identifier to aws batch

- plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy
- plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchTaskHandlerTest.groovy
> Change google batch disk directive to override boot disk size

- plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchExecutor.groovy
> Set aws batch polling monitor capacity from executor queueSize

- docs/conf.py
Replaces https://github.com/nextflow-io/nextflow/pull/3146. Simples!
> Update Google Analytics ID to use GA4

- modules/nextflow/src/main/groovy/nextflow/cli/CmdSecret.groovy
- modules/nextflow/src/test/groovy/nextflow/cli/CmdSecretTest.groovy
> feature: improve secrets cmd

- docs/getstarted.rst
> bugfix: fix getstarted tutorial

- plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy
- plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchTaskHandlerTest.groovy
> Add support for resource labels for google batch (#3168)

- modules/nextflow/src/main/groovy/nextflow/executor/fusion/FusionAwareTask.groovy
- modules/nextflow/src/main/groovy/nextflow/executor/fusion/FusionScriptLauncher.groovy
> Fix handling of targetDir when using Fusion fs

- plugins/nf-amazon/build.gradle
before logs
Caused by:
Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: TGPEXK7JT3192ZWK; S3 Extended Request ID: 7iOAgg4HTZzIk6ger5qTf/H48Ow5Iy0irern5SbJFBfWcmKOHVS8tiC3r9pVQWlVsxLmlnbhlZU=; Proxy: null)
After Logs: is able to access s3 bucket using IRSA role
nextflow.file.FilePorter - Local cache found for foreign file s3://
> added java sdk core and sts libraries to enable use of IRSA in k8s

- modules/nextflow/src/main/groovy/nextflow/extension/OperatorImpl.groovy
Signed-off-by: Kibubu <85624897+Kibubu@users.noreply.github.com>
> Fix #3219 Channel merge still deprecated for DSL2

- changelog.txt
> Add author name to commit in changelog.txt

- modules/nextflow/src/main/groovy/nextflow/cli/CmdSecret.groovy
The command name is secrets not secret.
Signed-off-by: Marcel Ribeiro-Dantas <mribeirodantas@seqera.io>
> Fix secrets command name in the CLI

- modules/nextflow/src/main/groovy/nextflow/Session.groovy
- modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy
- modules/nextflow/src/main/groovy/nextflow/cli/Launcher.groovy
- modules/nextflow/src/main/groovy/nextflow/container/ApptainerBuilder.groovy
- modules/nextflow/src/main/groovy/nextflow/container/ApptainerCache.groovy
- modules/nextflow/src/main/groovy/nextflow/container/ContainerBuilder.groovy
- modules/nextflow/src/main/groovy/nextflow/container/ContainerHandler.groovy
- modules/nextflow/src/main/groovy/nextflow/container/SingularityBuilder.groovy
- modules/nextflow/src/main/groovy/nextflow/container/SingularityCache.groovy
- modules/nextflow/src/test/groovy/nextflow/container/ApptainerBuilderTest.groovy
- modules/nextflow/src/test/groovy/nextflow/container/ApptainerCacheTest.groovy
- modules/nextflow/src/test/groovy/nextflow/container/ContainerBuilderTest.groovy
This PR adds the support for Apptainer container engine 
Signed-off-by: Paolo Di Tommaso <paolo.ditommaso@gmail.com>
> Add support for Apptainer

- modules/nf-httpfs/src/main/nextflow/file/http/XAuthProvider.groovy
- modules/nf-httpfs/src/main/nextflow/file/http/XAuthRegistry.groovy
- modules/nf-httpfs/src/main/nextflow/file/http/XFileSystemProvider.groovy
- plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerFactory.groovy
- plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerXAuth.groovy
Implement support for Tower refresh token for XFileSystemProvider accessed resources
> Add support for refresh token 

- modules/nextflow/build.gradle
- modules/nextflow/src/main/groovy/nextflow/mail/Mailer.groovy
following the maven report, these versions contain vulnerabilities. Upgrading libs fix them
> upgrade jsoup and snakeyaml version

- .github/workflows/build.yml
- .github/workflows/cffconvert.yml
> upgrade github actions to v3

- docs/script.rst
Documentation fix, no code changes.
Signed-off-by: Scott Norton <53584889+ScottNortonPhD@users.noreply.github.com>
> Fix "Check file attributes" example missing brace

- docs/operator.rst
Fixes #3189
Inspired by [This issue thread](https://github.com/nextflow-io/nextflow/issues/796) and Abhinav Sharma :)
Signed-off-by: Pauline <paulineauffret@hotmail.com>
> Add example for groupKey function in operator.rst

- .gitignore
- README.md
- docker/flux/.devcontainer/Dockerfile
- docker/flux/.devcontainer/devcontainer.json
- docker/flux/README.md
- docs/basic.rst
- docs/executor.rst
- docs/flux.rst
- modules/nextflow/src/main/groovy/nextflow/executor/ExecutorFactory.groovy
- modules/nextflow/src/main/groovy/nextflow/executor/FluxExecutor.groovy
- modules/nextflow/src/test/groovy/nextflow/executor/FluxExecutorTest.groovy
This work adds the Flux Framework executor, meaning a Nextflow user can submit jobs to flux. 
- This will close https://github.com/nextflow-io/nextflow/issues/3403
This addition includes:
- the executor itself
- the executor tests 
- a new documentation tutorial flux.rst, which I think is important for interested developers and/or if we want to add more detail for users
- addition to the executor.rst page
- a Docker and/or DevContainers environment for the interested developer / user
Notably, Flux is different from a typical executor because it doesn't do any kind of header file, nor does it allow specifying memory. To get around this, basically instead of having the header section populate user preferences, we add them to the command line instead! This makes the testing file uglier, but …
> add flux executor to nextflow

- docs/executor.rst
Signed-off-by: Llewellyn vd Berg <113503285+llewellyn-sl@users.noreply.github.com>
> Add time directive to AWS Batch, clean up language

- changelog.txt
Signed-off-by: Cornelius Roemer <cornelius.roemer@gmail.com>
> Fix typos in changelog.txt

- docs/google.rst
- plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy
- plugins/nf-google/src/main/nextflow/cloud/google/batch/client/BatchConfig.groovy
- plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchTaskHandlerTest.groovy
> Add allowedLocations option to google batch

- modules/nextflow/src/main/groovy/nextflow/executor/Executor.groovy
- modules/nextflow/src/main/groovy/nextflow/file/FilePorter.groovy
- modules/nextflow/src/test/groovy/nextflow/executor/ExecutorTest.groovy
- modules/nextflow/src/test/groovy/nextflow/file/FilePorterTest.groovy
- plugins/nf-amazon/src/test/nextflow/cloud/aws/util/S3PathTest.groovy
- plugins/nf-google/src/test/nextflow/file/GsPathTest.groovy
This PR address a concurrency issue in the `FilePorter` logic.
> Fix FilePorter concurrency issue

- modules/nextflow/src/main/groovy/nextflow/Nextflow.groovy
- modules/nextflow/src/main/groovy/nextflow/file/PathVisitor.groovy
- modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy
- modules/nextflow/src/main/groovy/nextflow/util/LoggerHelper.groovy
> Change "no such file" error message to "no such file or directory"

- docs/process.rst
- modules/nextflow/src/main/groovy/nextflow/executor/SimpleFileCopyStrategy.groovy
- modules/nextflow/src/main/resources/nextflow/executor/command-run.txt
- modules/nextflow/src/test/resources/nextflow/executor/test-bash-wrapper-with-trace.txt
- modules/nextflow/src/test/resources/nextflow/executor/test-bash-wrapper.txt
- plugins/nf-google/src/test/nextflow/cloud/google/lifesciences/bash-wrapper-gcp.txt
This PR builds upon the discussion in https://github.com/nextflow-io/nextflow/issues/3549#issuecomment-1385020467 
( And the automated tests have betrayed the build again 😅 )
All tests passing locally
> Add the fcp tool option to file copy strategy

- modules/nextflow/src/main/groovy/nextflow/util/SerializationHelper.groovy
- plugins/nf-amazon/src/main/nextflow/cloud/aws/util/S3PathFactory.groovy
- plugins/nf-amazon/src/main/nextflow/cloud/aws/util/S3PathSerializer.groovy
- plugins/nf-amazon/src/test/nextflow/util/S3PathSerializerTest.groovy
> Fix serialization of S3 paths with spaces

- modules/nextflow/src/main/groovy/nextflow/util/NameGenerator.groovy
Signed-off-by: Marco De La Pierre <marco.delapierre@gmail.com>
> Add Piero Angela to list of names

- modules/nextflow/src/main/groovy/nextflow/container/ContainerConfig.groovy
- modules/nextflow/src/main/groovy/nextflow/container/SingularityCache.groovy
- modules/nextflow/src/main/groovy/nextflow/fusion/FusionAwareTask.groovy
- modules/nextflow/src/test/groovy/nextflow/executor/local/LocalTaskHandlerTest.groovy
- modules/nextflow/src/test/groovy/nextflow/k8s/K8sTaskHandlerTest.groovy
- plugins/nf-amazon/src/test/nextflow/cloud/aws/batch/AwsBatchTaskHandlerTest.groovy
- plugins/nf-wave/src/main/io/seqera/wave/plugin/cli/WaveDebugCmd.groovy
This PR is meant to implement the support for entry-less Fusion configuration and support for Singularity containers.
> Add support for entryless Fusion configuration and Singularity support

- modules/nextflow/src/main/groovy/nextflow/config/ConfigBuilder.groovy
- modules/nextflow/src/main/groovy/nextflow/k8s/K8sDriverLauncher.groovy
From this conversation: https://github.com/nextflow-io/nextflow/pull/3345/files#r1092475481
> Fix -with-apptainer cli option

- modules/nextflow/src/main/groovy/nextflow/fusion/FusionScriptLauncher.groovy
- modules/nextflow/src/test/groovy/nextflow/executor/GridTaskHandlerTest.groovy
- modules/nextflow/src/test/groovy/nextflow/executor/fusion/FusionScriptLauncherTest.groovy
- modules/nextflow/src/test/groovy/nextflow/executor/local/LocalTaskHandlerTest.groovy
- modules/nf-commons/src/main/nextflow/Const.groovy
- plugins/nf-amazon/src/test/nextflow/executor/FusionScriptLauncherS3Test.groovy
- plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveClient.groovy
This PR adds the support for `FUSION_TAGS` env variable.
> Add support for fusion tags

- .gitignore
Signed-off-by: Marco De La Pierre <marco.delapierre@gmail.com>
> gitignore: added bin/ directories

- modules/nextflow/src/main/groovy/nextflow/scm/AzureRepositoryProvider.groovy
- modules/nextflow/src/test/groovy/nextflow/scm/AzureRepositoryProviderTest.groovy
> Infer commit revision type for azure repos

- docs/script.rst
> Add note about modifying maps with the `+` operator

- plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy
> Add error message for missing container image with Google Batch

- docs/azure.rst
This PR stems from a question on [Nextflow Slack](https://nextflow.slack.com/archives/C02TPRRLCF4/p1678987463116539) which made me realize that the defaults were not mentioned on the docs page.
> Document the azure fileshare mount option

- docs/azure.rst
Adding a couple of warnings about Azure named pools in the configuration. They would have saved us some headache.
> Add warnings for Azure named pools.

- docs/_templates/layout.html
- docs/conf.py
Documentation: Load Google Analytics via GTM instead of gtag.js
> Use Google Tag Manager.

- plugins/nf-amazon/src/main/nextflow/cloud/aws/nio/S3Client.java
> Fix string comparison in S3 client

- modules/nextflow/build.gradle
- modules/nextflow/src/main/groovy/nextflow/scm/AssetManager.groovy
> Update to JGit 6.5 to use .setDepth(1) when cloning (#3879)

- README.md
@pditommaso as per title, just a 1-liner update
> README: added link to Spack Environments docs page

- modules/nextflow/src/main/groovy/nextflow/k8s/K8sTaskHandler.groovy
- modules/nextflow/src/test/groovy/nextflow/k8s/K8sTaskHandlerTest.groovy
This fix simply handles PodUnschedulableException in the same way that NodeTerminationException is already handled. The synthetic state object updates the task correctly and the failing pod (for any PodUnschedulableException reason) will be ignored, but the task will still be cleaned up.
> Fixing bug 2428 for errorStrategy ignore

- docs/operator.md
Close #3935 
Regarding the documentation of groupKey, I will draft a separate PR that documents built-in methods and classes in a reference-complete manner.
> Clarify tip about groupTuple size and groupKey

- modules/nextflow/src/main/groovy/nextflow/extension/DumpHelper.groovy
Close #3952 
Did some cleanup, but the key change is to use `inject` instead of `each` on maps so that the original input isn't modified by the dump operator when pretty print is enabled.
> Fix dump pretty print to not modify input

- plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchMachineTypeSelector.groovy
- plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy
- plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchMachineTypeSelectorTest.groovy
This PR adds default machine types when local SSD is not required
> Patch Google batch instance types

- docs/container.md
- modules/nextflow/src/main/groovy/nextflow/container/SingularityBuilder.groovy
- modules/nextflow/src/test/groovy/nextflow/container/ApptainerBuilderTest.groovy
- modules/nextflow/src/test/groovy/nextflow/container/SingularityBuilderTest.groovy
- modules/nextflow/src/test/groovy/nextflow/executor/BashWrapperBuilderTest.groovy
- modules/nextflow/src/test/groovy/nextflow/executor/fusion/FusionHelperTest.groovy
> Disable singularity home mount by default

- docs/container.md
- docs/executor.md
- Fix typo in version note on containers page
- Add version note to TES executor
> Fix errors in docs

- docs/script.md
Fix typo eachFiles() should be eachFile().
> Fix typo in script.md

- modules/nextflow/src/main/groovy/nextflow/trace/ReportObserver.groovy
> Remove logging of report JSON data

- docs/config.md
Close https://github.com/seqeralabs/nf-tower-docs/issues/393
> Document `NXF_WRAPPER_STAGE_FILE_THRESHOLD` environment variable

- docs/channel.md
Based on a Slack discussion about the description of value channels. Tried to tighten up some of the terminology here.
> Improve description of channels and channel types

- docs/config.md
> Document behavior of withName selector with included aliases

- modules/nextflow/src/main/groovy/nextflow/k8s/K8sTaskHandler.groovy
- modules/nextflow/src/test/groovy/nextflow/k8s/K8sTaskHandlerTest.groovy
Fixes a bug which caused resource labels to not be applied to K8s tasks.
> Fix bug with K8s resource labels

- modules/nf-commons/src/main/nextflow/plugin/PluginsFacade.groovy
- modules/nf-commons/src/test/nextflow/plugin/PluginsFacadeTest.groovy
- plugins/nf-cloudcache/src/main/nextflow/cache/CloudCacheStore.groovy
By the way, tested with nf-core/rnaseq and it works 👍
> Enable cloud cache based on environment variable

- plugins/nf-tower/src/main/io/seqera/tower/plugin/LogsCheckpoint.groovy
This PR fixes the termination condition for the logs checkpointing thread
> Fix checkpoint thread termination

- docs/script.md
> Update tip about modifying maps

- nextflow
- packing.gradle
> Remove dockerize launcher classpath file

- modules/nf-commons/src/main/nextflow/util/Escape.groovy
- modules/nf-commons/src/test/nextflow/util/EscapeTest.groovy
> Escape semicolons in paths

- modules/nextflow/src/main/resources/nextflow/executor/command-run.txt
- modules/nextflow/src/test/resources/nextflow/executor/test-bash-wrapper-with-trace.txt
- modules/nextflow/src/test/resources/nextflow/executor/test-bash-wrapper.txt
- plugins/nf-google/src/test/nextflow/cloud/google/lifesciences/bash-wrapper-gcp.txt
> Fix printf command with negative exit code

- .github/workflows/build.yml
See discussion in https://github.com/nextflow-io/nextflow/pull/4248\#issuecomment-1701666678
> CI: Add back logic to skip Tests for docs-only PRs.

- docs/process.md
Close https://github.com/seqeralabs/nf-tower-docs/issues/432
> Add warning about using clusterOptions with process directives

- modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy
- modules/nextflow/src/test/groovy/nextflow/cli/CmdRunTest.groovy
> Parse negative CLI params as numbers

- modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy
- modules/nextflow/src/test/groovy/nextflow/executor/BashWrapperBuilderTest.groovy
- modules/nextflow/src/test/resources/nextflow/executor/test-bash-wrapper-with-trace.txt
- plugins/nf-amazon/src/test/nextflow/cloud/aws/batch/AwsBatchScriptLauncherTest.groovy
- plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzFileCopyStrategyTest.groovy
Addresses https://github.com/nextflow-io/nextflow/issues/4209
> Allow setting shell directive when using the trace file.

- docs/sharing.md
I've noticed that there are some users who are a little unclear about the utility of the `bin` directory. This is a first pass at making some of the functionality and expected motivation a little clearer
> First attempt at clarification of the bin dir

- docs/process.md
> Improve pod options documentation

- modules/nextflow/src/main/groovy/nextflow/processor/PublishDir.groovy
Close https://github.com/seqeralabs/nf-tower-cloud/issues/3870
> Always emit publish event for cached task outputs

- modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy
- plugins/nf-amazon/src/test/nextflow/cloud/aws/batch/AwsBatchScriptLauncherTest.groovy
- plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzFileCopyStrategyTest.groovy
> Disable staging script for remote work dir

- docs/cli.md
- docs/config.md
- docs/plugins.md
- docs/wave.md
> Document `NXF_DISABLE_CHECK_LATEST` environment var

- modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy
> Remove line endings from container box id

- docs/azure.md
Only changed in documentation for simplicity.
Fixes #3421
Hi! Thanks for contributing to Nextflow project.
When submitting a Pull Request please make sure to not include
in the changeset any modification in these files:
* `nextflow`
* `docs/conf.py`
* `modules/nf-commons/src/main/nextflow/Const.groovy`
Also, please sign-off the DCO [1] to certify you are the author of the contribution
and you adhere to Nextflow open source license [2] adding a `Signed-off-by` line to
the contribution commit message. For more details check [3].
1. https://developercertificate.org/
2. https://github.com/nextflow-io/nextflow/blob/master/COPYING
3. https://github.com/apps/dco
> Rename Microsoft AAD to Microsoft Entra

- modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy
I just ran into this (check print screen below).
> Update warning complaining about tuple but mentioning set

- .github/workflows/build.yml
- build.gradle
- buildSrc/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- packing.gradle
- settings.gradle
This PR upgraded Gradle to version 8.4 and added CI tests for Java 21
> Gradle 8.4 and test vs Java 21

- docs/executor.md
> Add note about local executor and enforcing resource limits

- docs/config.md
- modules/nf-commons/src/main/nextflow/plugin/PluginUpdater.groovy
- modules/nf-commons/src/main/nextflow/plugin/PluginsFacade.groovy
Alternative to #4340
This PR provides a clearer error message when using plugins in offline mode.
> Return error if plugin version is not specified in offline mode

- modules/nf-commons/src/main/nextflow/util/Duration.groovy
- modules/nf-commons/src/test/nextflow/util/DurationTest.groovy
> Fix rounding error with long durations

- docs/config.md
> Add note about limitations of glacier auto retrieval

- modules/nextflow/src/main/groovy/nextflow/container/ContainerConfig.groovy
- modules/nextflow/src/test/groovy/nextflow/container/ContainerConfigTest.groovy
This PR adds Fusion support when using Singularity running in OCI mode. 
Close https://github.com/nextflow-io/nextflow/issues/4506
Related https://github.com/sylabs/singularity/pull/2328
> Add support for Fusion when using Singularity OCI mode

- docker/Dockerfile
- modules/nextflow/build.gradle
- modules/nf-commons/build.gradle
- modules/nf-commons/src/main/nextflow/plugin/CustomPluginManager.groovy
- modules/nf-commons/src/testFixtures/groovy/nextflow/plugin/TestPluginDescriptorFinder.groovy
- packing.gradle
- plugins/nf-amazon/build.gradle
- plugins/nf-azure/build.gradle
- plugins/nf-cloudcache/build.gradle
- plugins/nf-codecommit/build.gradle
- plugins/nf-console/build.gradle
- plugins/nf-ga4gh/build.gradle
- plugins/nf-google/build.gradle
- plugins/nf-tower/build.gradle
- plugins/nf-wave/build.gradle
Close #4512 
Based on trivy scan of latest nextflow release:
```bash
trivy image nextflow/nextflow:23.10.0
```
> Fix security vulnerabilities

- plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveClient.groovy
@pditommaso  can you check this?  I have noticed it while reviewing your code from https://github.com/nextflow-io/nextflow/pull/4524
NOTE: before MERGING, please let's make sure CIs have been run
> Minor fix to WaveClient - following addition of google storage retry policy

- docs/config.md
Fix _Singulairty_ to _Singularity_ in the docs.
> [ci-skip] Fix typo in the docs

- plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzStorageOpts.groovy
> Use AZURE_STORAGE_SAS_TOKEN environment variable

- modules/nextflow/src/main/groovy/nextflow/trace/AnsiLogObserver.groovy
> Ignore stored process message when ansi log is enabled

- docs/config.md
- plugins/nf-amazon/src/main/nextflow/cloud/aws/nio/S3Client.java
- plugins/nf-amazon/src/main/nextflow/cloud/aws/nio/S3FileSystemProvider.java
- plugins/nf-amazon/src/test/nextflow/cloud/aws/nio/AwsS3NioTest.groovy
Deprecating/removing because it is not useful as implemented. Can be merged whenever you are ready.
> Remove Glacier auto-retrieval

- docs/config.md
Oops, forgot to push this elaboration.
> Aws client endpoint https

- docs/azure.md
Signed-off-by: Adam Talbot <12817534+adamrtalbot@users.noreply.github.com>
Hi! Thanks for contributing to Nextflow project.
When submitting a Pull Request please make sure to not include
in the changeset any modification in these files:
* `nextflow`
* `docs/conf.py`
* `modules/nf-commons/src/main/nextflow/Const.groovy`
Also, please sign-off the DCO [1] to certify you are the author of the contribution
and you adhere to Nextflow open source license [2] adding a `Signed-off-by` line to
the contribution commit message. For more details check [3].
1. https://developercertificate.org/
2. https://github.com/nextflow-io/nextflow/blob/master/COPYING
3. https://github.com/apps/dco
> Fix typo in Azure Batch docs ('Azore')

- plugins/nf-cloudcache/src/main/nextflow/cache/CloudCacheFactory.groovy
Just stumbled upon this, figured I'd fix
> minor cli docstring fix

- docs/channel.md
Channel topic section was duplicated for some reason
> Remove duplicate channel topic docs

- docs/aws.md
Add a brief mention of Tower Forge to the start of the AWS docs page.
> Docs: AWS - mention Tower Forge.

- modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy
x-ref: https://github.com/nextflow-io/nextflow/pull/4898#issuecomment-2046961431
> ANSI Log: Remove | from 'Launching' log line

- docs/azure.md
- docs/config.md
- plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy
- plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzPoolOpts.groovy
- plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzStartTaskOpts.groovy
- plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzBatchServiceTest.groovy
This PR improves the handling of Azure startTask options
> Improve startTask

- modules/nextflow/build.gradle
- modules/nf-commons/build.gradle
- modules/nf-httpfs/build.gradle
Fix some CVEs reported by Arnau:
- https://nvd.nist.gov/vuln/detail/CVE-2023-6378
- https://nvd.nist.gov/vuln/detail/CVE-2023-6481
> Fix security vulnerability in logback

- modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy
- modules/nextflow/src/main/groovy/nextflow/processor/TaskRun.groovy
This PR restores a few methods to private visibility since there's no public usage for them
> Restore private methods visibility

- modules/nextflow/src/main/groovy/nextflow/file/SimpleFileCollector.groovy
> Fix collectFile saving to GCS with sort: false

- docs/aws.md
I was recently using your guide to set up Nextflow, and I ran into some missing roles when it came to setting up AWS Batch Compute Environment. After I added the following roles, I was able to get it working.
> Update aws.md to include Cluster access

- docs/process.md
> Fix job array docs

- modules/nextflow/src/main/groovy/nextflow/fusion/FusionConfig.groovy
- modules/nextflow/src/test/groovy/nextflow/fusion/FusionConfigTest.groovy
- modules/nextflow/src/test/groovy/nextflow/script/FusionMetaTest.groovy
- plugins/nf-wave/src/test/io/seqera/wave/plugin/WaveClientTest.groovy
This PR bumps Fusion version 2.3
> Bump Fusion 2.3

- docs/metadata.md
> Update docs on version matching

- plugins/nf-azure/build.gradle
- plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy
- plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchTaskHandler.groovy
- plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzHelper.groovy
- plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzManagedIdentityOpts.groovy
- plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzPoolOpts.groovy
- plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzBatchServiceTest.groovy
This PR bumps Azure Batch SDK version to version 1.0.0-beta1 and changes the code to accomodate to the new sdk
> task: update azure batch to 1.0.0-beta version

- docs/process.md
Wording isn't great, so feel free to rewrite as needed @nextflow-io/docs 🙏🏻 😊
> Add note that beforeScript runs inside the container for some execution environments

- docs/azure.md
Updates Azure documentation to include the Managed Identity authentication method.
> Add Managed Identity to Azure authentication documentation

- modules/nextflow/src/main/groovy/nextflow/fusion/FusionConfig.groovy
- modules/nextflow/src/test/groovy/nextflow/fusion/FusionConfigTest.groovy
- modules/nextflow/src/test/groovy/nextflow/script/FusionMetaTest.groovy
- plugins/nf-wave/src/test/io/seqera/wave/plugin/WaveClientTest.groovy
This PR updates Fusion to version 2.4
> Bump Fusion 2.4

- modules/nextflow/src/main/groovy/nextflow/k8s/client/K8sClient.groovy
> fix: k8s client status cond is possible null in podState

- modules/nextflow/src/main/resources/nextflow/dag/mermaid.dag.template.html
> Fix large mermaid diagrams

- .github/workflows/build.yml
- docs/config.md
- docs/install.md
- gradle/wrapper/gradle-wrapper.properties
- launch.sh
- nextflow
This PR adds the support for Java 23
> Add Java 23 support

- plugins/nf-wave/src/main/io/seqera/wave/plugin/config/WaveConfig.groovy
This remove unused config option
> Remove unused reportsOpts

- modules/nextflow/src/main/groovy/nextflow/processor/TaskConfig.groovy
- modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy
- modules/nextflow/src/main/groovy/nextflow/processor/TaskRun.groovy
- modules/nextflow/src/test/groovy/nextflow/processor/TaskRunTest.groovy
This PR consolidate the resolve logic for stub run in the TaskRun class
> Consolidate resolve stub run logic

- plugins/nf-google/src/main/nextflow/cloud/google/lifesciences/GoogleLifeSciencesExecutor.groovy
This PR adds a deprecation warning for Google LS APIs
> Add Google LS deprecation notice

- modules/nextflow/src/test/groovy/nextflow/util/KryoHelperTest.groovy
- modules/nf-httpfs/src/main/nextflow/file/http/XFileSystem.groovy
close #5208 
-  Adding no-args constructor in XFileSystem
- XFileSystem serialization/deserialization tes
> Fix XFileSystem serilization issue

- plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchTaskHandler.groovy
> Demote azure batch task status log level to trace

- docs/executor.md
Fixes #5478
Signed-off-by: adamrtalbot <12817534+adamrtalbot@users.noreply.github.com>
Hi! Thanks for contributing to Nextflow project.
When submitting a Pull Request please make sure to not include
in the changeset any modification in these files:
* `nextflow`
* `modules/nf-commons/src/main/nextflow/Const.groovy`
Also, please sign-off the DCO [1] to certify you are the author of the contribution
and you adhere to Nextflow open source license [2] adding a `Signed-off-by` line to
the contribution commit message. For more details check [3].
1. https://developercertificate.org/
2. https://github.com/nextflow-io/nextflow/blob/master/COPYING
3. https://github.com/apps/dco
> Explicitly list the local executor directives in the docs

- docs/fusion.md
This PR document the Fusion compatibility with Oracle Object storage
> Document Fusion compatibility for Oracle storage

- docs/reference/process.md
> Clarify meaning of `task.id` versus `task.index`

- docs/install.md
This PR improves the docs for the standalone installer. Solves #5539
> Improve installer docs

- docs/aws.md
See https://github.com/nextflow-io/nextflow/pull/5562\#discussion_r1869837320
> Fix wave docs link.

- docs/sharing.md
> Fixes #5596 

- docs/reference/operator.md
> Document differences between `join` operator and SQL join

- docs/fusion.md
This PR adds more details about the setting of AWS storage for Fusion
> Add fusion tip about AWS storage config

- docs/install.md
@netlify /install.html#seqera-platform
> Add section for Seqera Platform into installation docs

- modules/nextflow/src/main/groovy/nextflow/processor/TaskBean.groovy
- plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchScriptLauncher.groovy
- validation/google.config
- validation/google.sh
- validation/test-arrays.nf
Close #5701
Contains #5726 and includes validation test for this case.
> Mount input file buckets in task arrays for Google Batch

- docs/reference/operator.md
> Document null-filtering behavior of `map` operator

- modules/nextflow/src/main/groovy/nextflow/processor/TaskRun.groovy
- modules/nextflow/src/test/groovy/nextflow/processor/TaskRunTest.groovy
Close #5469 
Allow templates to be used in stub sections.
> Fix stub templates

- docs/reference/process.md
Close #5565 
Just fixing a lazily-copied paragraph
> Fix documentation of process `path` input

- docs/cache-and-resume.md
> Improve documentation of task hash

- modules/nextflow/src/main/groovy/nextflow/trace/GraphObserver.groovy
> Create parent directory for DAG report

- gradle.properties
Why weren't we doing this before 😆
> Use parallelization in Gradle build

- modules/nextflow/src/main/groovy/nextflow/config/parser/v2/ConfigToGroovyVisitor.java
I had to make some changes to the language server that will break the Nextflow build, since Nextflow is tracking the `main` branch of language-server. This PR should fix the build with latest main.
Apologies for the inconvenience. I intend to move the compiler module into Nextflow as soon as possible so that this doesn't happen again.
> Update config-to-groovy visitor

- docs/metrics.md
- gradle.properties
- Expand i/o section
- Align language where possible
> Update metrics tutorial

- docs/index.md
- Reduce listing in the main body of text
- Revise get started to align with side navigation
- Update text to point at courses and training
- Wording and tense updates
> Update index page

- modules/nextflow/src/main/groovy/nextflow/dag/MermaidRenderer.groovy
Fix the incorrect subgraph naming in exported DAGs in the Mermaid format, as presented in issue #5843.
> Fix subgraph merge in rendered Mermaid DAG (#5843)

- modules/nextflow/build.gradle
Tentative fix for lineage package loading.
> Fix lineage packaging

- modules/nf-lineage/src/main/nextflow/lineage/fs/LinPath.groovy
- modules/nf-lineage/src/test/nextflow/lineage/fs/LinPathTest.groovy
close #6017
Forgot to replace /outputs to #outputs in the fromPath case.
> fix errors in output fragment

- docs/cli.md
- docs/index.md
- Fix small formatting inconsistencies that cause errors when trying to build with Docusaurus.
- Does not change anything in Shinx build.
> Fix small formatting inconsistencies 

- modules/nf-lineage/src/main/nextflow/lineage/cli/LinDagRenderer.groovy
Improve the error message in the case where the `render` command queries a non-existing LID while traversing the lineage graph
I encountered this because I resumed a run with lineage, where the initial run did not have lineage enabled. Because the LinObserver doesn't store cached tasks, only new tasks were recorded in the lineage store.
I thought about adding the onTaskCached hook to the LinObserver, but I don't know if we want to re-write every task run on a resume -- a fully-resumed run should be fast. Maybe we could implement onTaskCached and write the record only if it doesn't already exist in the lineage store.
> Improve not found error in lineage `render`

- docs/migrations/25-04.md
This PR brings the 25.04 migration notes out of preview and adds any remaining misc items.
> Finalize 25.04 migration notes

- modules/nextflow/src/main/groovy/nextflow/cli/CmdPlugin.groovy
- modules/nextflow/src/test/groovy/nextflow/cli/CmdPluginCreateTest.groovy
- modules/nf-commons/src/main/nextflow/plugin/util/PluginRefactor.groovy
This PR updates the plugin template to version v0.2.0
> Update plugin template to v0.2.0

- modules/nextflow/src/main/groovy/nextflow/fusion/FusionConfig.groovy
- plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveClient.groovy
- plugins/nf-wave/src/test/io/seqera/wave/plugin/WaveClientTest.groovy
This PR adds the support for Snapshots on ARM architecture
> Add support for ARM and Snapshots

- docs/reference/cli.md
- modules/nextflow/src/main/groovy/nextflow/cli/CmdLineage.groovy
- modules/nf-lineage/src/main/nextflow/lineage/cli/LinCommandImpl.groovy
- modules/nf-lineage/src/main/nextflow/lineage/config/LineageConfig.groovy
- modules/nf-lineage/src/main/nextflow/lineage/config/LineageStoreOpts.groovy
- modules/nf-lineage/src/main/nextflow/lineage/fs/LinFileSystemProvider.groovy
- modules/nf-lineage/src/main/nextflow/lineage/fs/LinPath.groovy
- modules/nf-lineage/src/test/nextflow/lineage/cli/LinCommandImplTest.groovy
- modules/nf-lineage/src/test/nextflow/lineage/fs/LinPathTest.groovy
This PR adds the check subcommand in the lineage CLI command.This command is used to validate the integrity of an output path.
> Add check subcommand in lineage

- docs/process.md
- docs/reference/cli.md
- docs/reference/process.md
- Fixes node > note error
- Add secrets to cli and process reference
Fixes #6081
> Add secrets to cli and process reference

- docs/cli.md
- Fix code block that is missing some ticks
> Fix code block

- docs/reference/config.md
Close #6088 
Documents some config default values that were missing and some extra cleanup that I did along the way.
> Document config default values

- docs/reference/config.md
- modules/nextflow/src/main/groovy/nextflow/config/ConfigValidator.groovy
- modules/nf-lang/src/main/java/nextflow/config/scopes/Config.java
> Document `bucketDir` config option

- modules/nf-lang/src/main/java/nextflow/script/control/VariableScopeVisitor.java
- modules/nf-lang/src/test/groovy/nextflow/script/control/ScriptResolveTest.groovy
- modules/nf-lang/src/testFixtures/groovy/test/TestUtils.groovy
Fix the error reported here: https://community.seqera.io/t/stdout-not-defined/2213
> Fix false error when using stdin/stdout in a tuple

- modules/nf-lang/src/main/java/nextflow/script/ast/IncludeEntryNode.java
- modules/nf-lang/src/main/java/nextflow/script/ast/IncludeNode.java
- modules/nf-lang/src/main/java/nextflow/script/control/ResolveIncludeVisitor.java
- modules/nf-lang/src/main/java/nextflow/script/control/ScriptToGroovyVisitor.java
- modules/nf-lang/src/main/java/nextflow/script/control/VariableScopeVisitor.java
- modules/nf-lang/src/main/java/nextflow/script/formatter/ScriptFormattingVisitor.java
- modules/nf-lang/src/main/java/nextflow/script/parser/ScriptAstBuilder.java
Rename the AST node for include entries to avoid ambiguity with ModuleNode and [modules](https://nextflow.io/docs/latest/module.html) in general
> Rename IncludeModuleNode to IncludeEntryNode

- plugins/nf-google/build.gradle
This PR updates Google GCP and Batch dependencies.
> Update Google dependencies

- modules/nextflow/src/main/groovy/nextflow/Session.groovy
- modules/nextflow/src/main/groovy/nextflow/trace/AnsiLogObserver.groovy
- modules/nextflow/src/main/groovy/nextflow/trace/DefaultObserverFactory.groovy
- modules/nextflow/src/main/groovy/nextflow/trace/GraphObserver.groovy
- modules/nextflow/src/main/groovy/nextflow/trace/ReportObserver.groovy
- modules/nextflow/src/main/groovy/nextflow/trace/TimelineObserver.groovy
- modules/nextflow/src/main/groovy/nextflow/trace/TraceFileObserver.groovy
- modules/nextflow/src/main/groovy/nextflow/trace/WorkflowStatsObserver.groovy
- modules/nextflow/src/test/groovy/nextflow/SessionTest.groovy
- modules/nextflow/src/test/groovy/nextflow/trace/ReportObserverTest.groovy
- modules/nextflow/src/test/groovy/nextflow/trace/TimelineObserverTest.groovy
- modules/nextflow/src/test/groovy/nextflow/trace/TraceFileObserverTest.groovy
- modules/nf-commons/src/testFixtures/groovy/nextflow/plugin/hello/HelloFactory.groovy
- modules/nf-commons/src/testFixtures/groovy/nextflow/plugin/hello/HelloObserver.groovy
- plugins/nf-tower/src/main/io/seqera/tower/plugin/LogsCheckpoint.groovy
- plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerClient.groovy
- plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerFactory.groovy
- plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveFactory.groovy
This pull request introduces significant updates to the Nextflow tracing and observer system, primarily focused on refactoring the observer classes to support a new `TraceObserverV2` interface. It also includes code cleanup, optimizations, and enhancements to improve maintainability and functionality.
* Refactored `AnsiLogObserver`, `GraphObserver`, and `ReportObserver` to implement the new `TraceObserverV2` interface. This involved renaming methods (e.g., `onProcessSubmit` to `onTaskSubmit`) and updating method parameters to use the `TaskEvent` class. (`[[1]](diffhunk://#diff-483299acf7148ae9c19ae3276b024336bfa608f5d8f5352758a68e779fee4b7fL41-R42)`, `[[2]](diffhunk://#diff-32f9369643f5607fedb8abadeef4add6bafe8b03cf753924f44056cb27cc5b71L34-R40)`, …
> Update trace observers to v2

- docs/developer-env.md
Some phrasing was repeated—update for clarity and readability.
> Rephrase nf-core extension pack description

- docs/reports.md
Fixed this typo I caught while reading the docs
> Fixed docs typo in error_action

- plugins/nf-codecommit/build.gradle
- plugins/nf-codecommit/src/main/nextflow/cloud/aws/codecommit/AwsCodeCommitCredentialProvider.groovy
- plugins/nf-codecommit/src/main/nextflow/cloud/aws/codecommit/AwsCodeCommitRepositoryProvider.groovy
- plugins/nf-codecommit/src/test/nextflow/cloud/aws/codecommit/AwsCodeCommitRepositoryProviderTest.groovy
Updates the nf-codecommit as in #6263 without commenting the `@Requires` line causing https://github.com/nextflow-io/nextflow/pull/6269#issuecomment-3063383071
> Update nf-codecommit to AWS SDK v2 with corrected test 

- modules/nf-commons/build.gradle
- modules/nf-commons/src/main/nextflow/plugin/HttpPluginRepository.groovy
- modules/nf-commons/src/main/nextflow/plugin/OciAwareFileDownloader.groovy
- modules/nf-commons/src/main/nextflow/plugin/Plugins.groovy
- modules/nf-commons/src/main/nextflow/plugin/PluginsFacade.groovy
- modules/nf-commons/src/test/nextflow/plugin/HttpPluginRepositoryTest.groovy
- modules/nf-commons/src/test/nextflow/plugin/OciAwareFileDownloaderTest.groovy
This pull request updates the plugin repository integration to support the new Nextflow plugin registry API and improves plugin metadata handling, including robust date conversion for plugin releases. It also refactors the file downloader to streamline HTTP request handling and clarifies registry URL management. The changes are validated with new comprehensive test cases.
**Plugin Registry API Integration and Metadata Handling**
* Added support for the new `io.seqera:npr-api` dependency and updated the plugin repository to consume plugin metadata from the Nextflow registry API, replacing legacy response types and mapping API objects to pf4j-compatible objects, including correct date conversions for plugin releases. [[1]](diffhunk://#diff-852c6469d85cf3a9326e10b1c29793ec7a771e869f47937effc6 …
> Bump nextflow registry as default

- docs/reference/process.md
See discussion: https://community.seqera.io/t/nextflow-process-directive-scratch-cleans-but-does-not-remove-scratch-dir/2337
> Docs: Minor addition to docs about `scratch`
