nextflow

I'm using an older Linux install that uses mktemp version 1.5 http://www.mktemp.org/mktemp/manual.html that doesn't support --tmpdir. Since newer coreutils mktemp still seems to support -p I think this is a safe change.

Use mktemp -p for non-coreutils mktemp compatibility

---

src/main/groovy/nextflow/util/DockerBuilder.groovy
src/test/groovy/nextflow/util/DockerBuilderTest.groovy

Sample usage:
```
docker {
enabled = true
engineOptions = "--tlsverify --tlscacert=\"/Users/mas2182/.docker/machine/machines/dev/ca.pem\" --tlscert=\"/Users/mas2182/.docker/machine/machines/dev/cert.pem\" --tlskey=\"/Users/mas2182/.docker/machine/machines/dev/key.pem\" -H=tcp://192.168.99.100:2376"   
runOptions = " -v /Users/mas2182/temp/ARTIFACT_REPOSITORY:/scratchLocal/gobyweb/ARTIFACT_REPOSITORY"       
}
```

Add engineOptions setting to Docker configuration.

---

docs/doctests/storedir.nf
docs/process.rst

I wish I could contribute in a more meaningful way, but these are a start. Very, very minor adjustments to the docs. Two changes:
- Changed "need to `together` the result of multiple execution" to "need to `group together` the results of multiple executions"
- Changed 'specie' to 'species'. The plural == singular in this case. "specie" is a word that means coin money (as distinct from notes).

Typo fixes

---

src/main/groovy/nextflow/dag/CytoscapeHtmlRenderer.groovy
src/main/groovy/nextflow/dag/CytoscapeJsRenderer.groovy
src/main/groovy/nextflow/dag/DAG.groovy
src/main/groovy/nextflow/dag/DagRenderer.groovy
src/main/groovy/nextflow/dag/DagreD3HtmlRenderer.groovy
src/main/groovy/nextflow/dag/DotRenderer.groovy
src/main/groovy/nextflow/dag/ErrorRenderer.groovy
src/main/groovy/nextflow/dag/GraphRender.groovy
src/main/groovy/nextflow/dag/GraphVizRenderer.groovy
src/main/resources/nextflow/dag/cytoscape.js.dag.template.html
src/main/resources/nextflow/dag/dagre.d3.dag.template.html
src/test/groovy/nextflow/dag/GraphRenderTest.groovy

This change adds the ability to export a DAG as an html file where the DAG is rendered using Cytoscape.js and Dagre.  It uses a template html file and simply substitutes in the network data formatted as json that Cytoscape.js will understand.  
The only notable change is that the rendering of Dot and Cytoscape.js are separated into individual classes that are separate from the definition of the DAG, edges, and vertices.  I'd probably argue that the GraphRender class should probably move execution of the dot command to the DotRenderer class to tidy things up, but I haven't made that change.

First shot at Cytoscape.js DAG rendering

---

src/main/groovy/nextflow/executor/SlurmExecutor.groovy

see issue #190 - our sbatch wrapper outputs just the jobid for convenience. This pull request accepts just a naked jobid in addition to the default sbatch output.

Allow sbatch to only output the jobid by itself

---

src/main/groovy/nextflow/splitter/AbstractTextSplitter.groovy
src/main/groovy/nextflow/splitter/StringSplitter.groovy
src/test/groovy/nextflow/splitter/AbstractTextSplitterTest.groovy
src/test/groovy/nextflow/splitter/FastaSplitterTest.groovy
src/test/groovy/nextflow/splitter/StringSplitterTest.groovy

This patch addresses issue https://github.com/nextflow-io/nextflow/issues/181.
This works, but I wish I had the time to cleanly refactor and separate the concepts of "count" and "collecting."  
One question: I'm not sure what to do about StringSplitter.groovy, which check if count>1.  Not sure if that should be changed or not too.
Let me know what you think and I'll updated as needed!

Allows splitFasta to both write files and split by one sequence.

---

docs/config.rst
src/main/groovy/nextflow/executor/AwsBatchExecutor.groovy
subprojects/nxf-commons/src/main/nextflow/Global.groovy
subprojects/nxf-commons/src/test/nextflow/GlobalTest.groovy

I have added into the nextflow.config file the option to specify S3 server side encryption (currently just AES256). Also the existing storage class option, already available for the S3FileSystem client, is now retrieved in the AWS Batch Executor and used during file upload. Tests are provided for the functions that were added.

Encryption and S3 storage class options for AWS Batch executor 

---

src/main/groovy/nextflow/container/ShifterBuilder.groovy

This PR is a possible fix on issue #500. 
This modification in the `awk` command improves the fetching of the `READY` flag of Shifter images and prevents a job from hanging indefinitely in a pull cycle.

Possible fix on issue #500

---

src/main/groovy/nextflow/executor/AwsBatchExecutor.groovy

This should address #512, it has been already tested and the export variable string is correctly added into the ```.command.run``` bash wrapper script.

adding AWS_DEFAULT_REGION variable. Addressing #512

---

docs/process.rst

Added a section documenting `optional true` for the process outputs.

Documented optional output for process output

---

src/main/resources/nextflow/trace/ReportTemplate.html

Fixed the text overflow CSS.
From this:
to this:

Report HTML/CSS tweaks to make progress bar text overflow work properly

---

nextflow

The `mktemp` that ships with the latest Alpine Linux Docker image (which uses BusyBox v1.27.2) requires a template string longer than the one specified in the NextFlow 0.28.1 install script.
In the install script we have `nxf-tmp.XXXXX` but BusyBox's `mktemp` requires `nxf-tmp.XXXXXX`.  
I've also updated the template string for OS X; someone with access to OS X will need to check that I haven't broken things for them.

install script: mktemp fails on busybox as template string contains one too few 'X's

---

src/main/groovy/nextflow/executor/LsfExecutor.groovy
src/test/groovy/nextflow/executor/LsfExecutorTest.groovy

Sanger Institute's LSF farm requires select as well as rusage to
be specified, along with -M.
Specifying select in this way should not negatively affect any
other LSF installation.

Include select in -R for memory.

---

docs/config.rst
docs/tracing.rst
src/main/groovy/nextflow/Session.groovy
src/main/groovy/nextflow/cli/CmdRun.groovy
src/main/groovy/nextflow/cli/Launcher.groovy
src/main/groovy/nextflow/config/ConfigBuilder.groovy
src/main/groovy/nextflow/processor/TaskPollingMonitor.groovy
src/main/groovy/nextflow/trace/TraceObserver.groovy
src/main/groovy/nextflow/trace/WebLogObserver.groovy
src/main/groovy/nextflow/util/SimpleHttpClient.groovy
src/test/groovy/nextflow/trace/WebLogObserverTest.groovy
src/test/groovy/nextflow/util/SimpleHttpClientTest.groovy

**Motivation**
I thought it would be super cool to have a mechanism to let Nextflow send **trace reports** from the workflow processes **during workflow execution**, so one can **monitor** the workflow status and process on remote target sites (Webportals, API webservice with database logging, etc.).
This idea was already mentioned here https://github.com/nextflow-io/nextflow/pull/454 by @mes5k, but using websockets instead. Websockets are a lot more complex as they are stateful and one would need to be very careful with the implementation not to brake workflow execution. So I desided to go for simple HTTP POST requests, and it is the task of the user to provide a webserver, that consumes the information (JSON).
**Mechanism**
I introduced a `-with-messages` option, that will trigger this …

Introduce HTTP POST feature and broadcast workflow process runtime information

---

src/main/groovy/nextflow/Const.groovy
src/main/groovy/nextflow/dag/DotRenderer.groovy
src/test/groovy/nextflow/dag/DotRendererTest.groovy
src/test/groovy/nextflow/trace/GraphObserverTest.groovy

Fix for #783 bug in dot rendering. Caused by use of DOT language keyword as graph name.  
Graph name in dot is optional, so if it is not needed for anything downstream this should suffice:
```
digraph {
}
```
Otherwise, note that graph name is an instance of `ID` in [DOT language](http://www.graphviz.org/doc/info/lang.html) and:   
> An `ID` is one of the following:
> Any string of alphabetic ([a-zA-Z\200-\377]) characters, underscores ('_') or digits ([0-9]), not beginning with a digit;
> a numeral [-]?(.[0-9]+ | [0-9]+(.[0-9]*)? );
> any double-quoted string ("...") possibly containing escaped quotes (\")1;
> an HTML string (<...>).
> An `ID` is just a string; the lack of quote characters in the first two forms is just for simplicity. There is no semantic difference between abc_2 and …

Fix for #783 bug in dot rendering 

---

src/main/groovy/nextflow/config/ConfigBuilder.groovy

- Changed present tense to present perfect. 
- Replaced "seems" with "appears" because "appears" seems more appropriate in this context. To this developer, "appears" indicates that the warning is tied more closely to data.

Fix up grammar in -resume warning on new project

---

docs/googlecloud.rst

1) Add link to enable required Google Cloud APIs
2) Include Service Account roles that are required

Google Cloud docs: APIs & Service Account roles

---

docs/cli.rst

Adds much more to the `run`section in the CLI documentation, including my changes from https://github.com/nextflow-io/nextflow/pull/945 to document the params-config format.
I can add more if this is needed or desired :-)

Add more documentation to CLI branch

---

docs/process.rst
src/main/groovy/nextflow/executor/SimpleFileCopyStrategy.groovy
src/test/groovy/nextflow/executor/BashWrapperBuilderTest.groovy
src/test/groovy/nextflow/executor/SimpleFileCopyStrategyTest.groovy

This PR addresses issue #745. Based on @pditommaso's comment, this change makes the default behaviour for `storeDir` to move files to the specified directory instead of copying them.
In the process of making this change, I realised that the `storeDir` behaviour is modified by the `stageOutMode` directive, which I had assumed applied only to `publishDir`.
When `targetDir` and `workDir` differ, this is considered an indication that the `storeDir` directive was used as [`storeDir` takes precedence over `workDir`](https://github.com/nextflow-io/nextflow/blob/f8dae9c89155bd1cd0cced92df71bd0ba27e7176/src/main/groovy/nextflow/processor/TaskRun.groovy#L495) and the 'move' `stageOutMode` is used by default, unless `stageOutMode` has been specifically set to some other value.

When using storeDir, files are moved instead of copied + tests

---

docs/awscloud.rst

removed the warning that AWS Batch was experimental. 
Signed-off-by: KevinSayers <sayerskt@gmail.com>

removed the aws batch experimental

---

docs/config.rst
modules/nextflow/src/main/groovy/nextflow/container/SingularityCache.groovy
modules/nextflow/src/test/groovy/nextflow/container/SingularityCacheTest.groovy

Hi,
Singularity has some pull options:
```
Options:
--docker-login     interactive prompt for docker authentication
-F, --force            overwrite an image file if it exists
-h, --help             help for pull
--library string   the library to pull from (default
"https://library.sylabs.io")
--nohttps          do NOT use HTTPS, for communicating with local
docker registry
```
And I need `--nohttps` option to pull my image because my docker registry is in my private network.
Please consider this. 
Thanks.

Add pullOptions for singularity

---

docs/conda.rst

This is a very small change, adapting channel priorities in the environment.yml example to follow bioconda recommendations.
See here:
https://github.com/bioconda/bioconda-recipes/pull/10924

conda documentation: update channel priorities

---

modules/nextflow/src/main/groovy/nextflow/trace/TraceFileObserver.groovy
modules/nextflow/src/test/groovy/nextflow/trace/TraceFileObserverTest.groovy

As the memory plot in the Resource Usage of the report now displays both peak_vmem and peak_rss, I suggest to report these peak memory values as default into the trace file. Indeed, only peak memory values really matters for process profiling.

Use peak_vmem and peak_rss as default output in the trace file instead of rss and vmem

---

build.gradle

The build was relying upon an insecure repository, this is a security vulnerability.
[CWE-829: Inclusion of Functionality from Untrusted Control Sphere](https://cwe.mitre.org/data/definitions/829.html)
[CWE-494: Download of Code Without Integrity Check](https://cwe.mitre.org/data/definitions/494.html)
The build files indicate that this project is resolving dependencies over HTTP instead of HTTPS. Any of these artifacts could have been MITM to maliciously compromise them and infect the build artifacts that were produced. Additionally, if any of these JARs or other dependencies were compromised, any developers using these could continue to be infected past updating to fix this.
This vulnerability has a CVSS v3.0 Base Score of 8.1/10 …

[SECURITY] Don't rely upon insecure repository

---

docs/operator.rst

Operators like `println` consume channels, if combined with other operators during channel creation. I added a small note in the docs, that highlights this for:
- print
- println
- subscribe
- set
Any remarks welcome :)

Adds note in documentation for operators that consume channels

---

modules/nextflow/src/main/groovy/nextflow/scm/AssetManager.groovy
modules/nextflow/src/main/groovy/nextflow/scm/RepositoryProvider.groovy

Fix for issue https://github.com/nextflow-io/nextflow/issues/1134

Provide scm credentials when fetching information about remote branches.

---

modules/nextflow/src/main/groovy/nextflow/scm/BitbucketRepositoryProvider.groovy

Bitbucket has stated that they will remove their 1.0 API on the 29th of April 2019. See - https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/
For some reason they are still up, but its just a matter of time until they remove them.
This pull request updates the BitbucketRepositoryProvider to use the 2.0 API for all interaction with Bitbucket.
Fix for issue: https://github.com/nextflow-io/nextflow/issues/1183
Signed-off-by: Ólafur Haukur Flygenring <olafurh@wuxinextcode.com>

Upgrade fully to 2.0 Bitbucket API

---

docs/getstarted.rst

Fixes a typo in the "Modify and Resume" section of the "Get Started" page
Also, clarifies the description of the first process in the tutorial.nf file

typo and clarification about tutorial script process

---

modules/nextflow/src/main/groovy/nextflow/scm/AssetManager.groovy

When I try to run a script directory from gitea, I got error messages as follows:
```
Jun-27 10:42:24.767 [main] DEBUG nextflow.cli.Launcher - $> nextflow run 'https://mydomain.com/gitea/nf-workflows/star-index.git' --input input.yaml
Jun-27 10:42:24.837 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.06.0-edge
Jun-27 10:42:25.347 [main] DEBUG nextflow.scm.AssetManager - Repository URL: https://mydomain.com/gitea/nf-workflows/star-index.git; Project: nf-workflows/star-index; Hub provider: gitea
Jun-27 10:42:25.352 [main] INFO  nextflow.cli.CmdRun - Pulling nf-workflows/star-index ...
Jun-27 10:42:25.356 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials pachiras:*********] -> https://mydomain.com/gitea/api/v1/repos/nf-workflows/star-index/raw/nextflow.con …
```

Added setCredentialsProvider for submodules

---

modules/nextflow/src/main/groovy/nextflow/executor/SlurmExecutor.groovy
modules/nextflow/src/test/groovy/nextflow/executor/SlurmExecutorTest.groovy

The admins on my HPC have configured SLURM with the default_gbytes option set. This will mean that the --mem is interpreted as gigabyte instead of the default megabyte. This behavior can be overruled by supyling a unit. To be compatible with both configurations it is best that nextflow supplies a unit (M) when setting memory requirements.
See https://slurm.schedmd.com/sbatch.html under --mem.

Add megabyte unit to slurm memory config

---

modules/nextflow/src/main/groovy/nextflow/k8s/client/K8sClient.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/client/K8sClientTest.groovy

Fix for issue: https://github.com/nextflow-io/nextflow/issues/1223
Signed-off-by: Ólafur Haukur Flygenring <olafurh@wuxinextcode.com>

Fix: "invalid pod status" when running scrips with the kubernetes executor.

---

docs/process.rst
modules/nextflow/src/main/groovy/nextflow/k8s/K8sConfig.groovy
modules/nextflow/src/main/groovy/nextflow/k8s/K8sTaskHandler.groovy
modules/nextflow/src/main/groovy/nextflow/k8s/model/PodOptions.groovy
modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/K8sTaskHandlerTest.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/model/PodOptionsTest.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/model/PodSpecBuilderTest.groovy

Adds support for kubernetes pod annotations when using he k8s executor.
Allows you to annotate pods in kubernetes for various kubernetes tools such as  autoscalers, log handlers atc.
See: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/

Kubernetes annotations

---

docs/config.rst
docs/dsl2.rst

Before this commit, the example showed the foo() process being passed the output of bar(). I might be mistaken, but the example looks like the output of foo() should be passed to bar(<here>) rather than the other way around - foo() doesn't take any input.
While we're looking at this section, we might as well show the bar() process doing something with the input file.

Tiny docs fixes

---

docs/operator.rst

The docs previously suggested the `size` parameter would control how many lines were skipped, but that parameter doesn't exist. I think that that `skip` parameter does this job instead.

Docs fix: collectFile `size` vs `skip`

---

modules/nextflow/src/main/groovy/nextflow/script/IncludeDef.groovy

Having a module file with multiple dots in its name results in an error. For example:
```bash
ls -1 NextflowCommandLineTools/bwa/0.7.5a.nf
NextflowCommandLineTools/bwa/0.7.5a.nf
```
```nextflow
include mem from 'NextflowCommandLineTools/bwa/0.7.5a'
```
```bash
nextflow run test.nf
N E X T F L O W  ~  version 19.07.0
Launching `test.nf` [furious_poincare] - revision: c5443c2765
WARN: DSL 2 IS AN EXPERIMENTAL FEATURE UNDER DEVELOPMENT -- SYNTAX MAY CHANGE IN FUTURE RELEASE
No such file: Can't find a matching module file for include: NextflowCommandLineTools/bwa/0.7.5a
```
I suggest to explicitly check whether module path does not end with '.nf'.

Explicitly check whether module path does not end with .nf

---

docs/index.rst
docs/shifter.rst
modules/nextflow/src/main/groovy/nextflow/container/ShifterBuilder.groovy
modules/nextflow/src/test/groovy/nextflow/container/ShifterBuilderTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/BashWrapperBuilderTest.groovy

This PR replaces the helper functions `shifter_pull` and `shifter_img` for the `shifterimg` command 
used natively by shifter.
This PR also adds documentation related to using the engine, the structure and some content of the 
documentation was taken from the singularity documentation.

Use native shifterimg for  shifter engine

---

modules/nextflow/src/main/groovy/nextflow/container/ShifterBuilder.groovy
modules/nextflow/src/test/groovy/nextflow/container/ShifterBuilderTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/BashWrapperBuilderTest.groovy

For some unknown reason shifterimg returns before finishing,
it should wait, even from a non-interactive shell.
Added some code from the previous helper function
Signed-off-by: Manuel Torrinha <manuel.torrinha@tecnico.ulisboa.pt>

shifterimg workaround for ensuring image pulls

---

modules/nextflow/src/main/groovy/nextflow/Session.groovy

Fix for issue: https://github.com/nextflow-io/nextflow/issues/1336
Signed-off-by: Ólafur Haukur Flygenring <olafurh@wuxinextcode.com>

Make Session.cleanup use a delete function that doesn't follow symlinks

---

tests/collect_and_merge.nf

Nothing major, but I noticed this tiny thing while going through the tests for learning more about `nextflow`.

correct typo in `collect_and_merge.nf` test

---

modules/nf-commons/src/main/nextflow/util/CacheHelper.java

I had a java.nio.file.ProviderMismatchException which is not catched in CacheHelper because IOException is not a parent class of ProviderMismatchException
The following PR had a catch so the error will be displayed.
```
Nov-18 14:54:18.058 [Actor Thread 20] ERROR nextflow.processor.TaskProcessor - Error executing process > 'mergeControls (merge contols)'
Caused by:
java.nio.file.ProviderMismatchException
java.nio.file.ProviderMismatchException: null
at sun.nio.fs.UnixPath.toUnixPath(UnixPath.java:200)
at sun.nio.fs.UnixFileSystemProvider.getFileAttributeView(UnixFileSystemProvider.java:115)
at sun.nio.fs.LinuxFileSystemProvider.getFileAttributeView(LinuxFileSystemProvider.java:68)
at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
at …
```

Handle ProviderMismatchException in CacheHelper

---

launch.sh

A variable, `$java` was defined, but never used in `launch.sh`.
The env variable `$JAVA_CMD` was therefore ignored.

Fix java command in launch script.

---

docs/operator.rst

Typo fix under .join operator documentation

Small documentation typo fix for join operator

---

modules/nextflow/src/main/groovy/nextflow/executor/SgeExecutor.groovy
modules/nextflow/src/test/groovy/nextflow/executor/SgeExecutorTest.groovy

qhold on a running job will change the state to `hr`, but the jobs is still running. I added `hr` as a RUNNING state. Tests added, too.
Signed-off-by: Benjamin Schuster-Böckler <ben.sb@methodicate.com>

fixed an issue in SGE version OGS/GE 2011.11p1

---

docs/process.rst

Fixed some minor issues with the accelerator directive docs. The anchor from the TOC of directives was linking to Google docs due to the link in the tip box.

fixes for accelerator docs

---

docs/executor.rst
modules/nf-ga4gh/src/main/nextflow/ga4gh/tes/executor/TesTaskHandler.groovy

As part of the [CINECA](https://www.cineca-project.eu/) project we plan to use Nextflow with [GA4GH TES](https://github.com/ga4gh/task-execution-schemas), a simple standardised execution schema. This pull request fixes three critical problems in Nextflow's current support of TES:
* Nextflow creates several standard inputs and outputs for each submitted task.
* For all of them, the `type` field is always set to `null`.
* TES allows this parameter to be either _FILE_ or _DIRECTORY_, but [does not allow it to be null](https://github.com/ga4gh/task-execution-schemas/blob/9cc12b0c215a7f54fdeb0d0598ebc74fa70eb2a7/openapi/task_execution.swagger.yaml#L261).
* This PR fixes it by explicitly setting the type of all inputs and outputs as `FILE`.
* If Docker image is not specified, the …

Fix bugs in GA4GH TES support

---

modules/nextflow/src/main/groovy/nextflow/scm/ProviderConfig.groovy
modules/nextflow/src/test/groovy/nextflow/scm/ProviderConfigTest.groovy

Fix ProviderConfig to support local repositories

---

docs/getstarted.rst

Remove duplicated word 'before'.

getstarted.rst - fix typo

---

docs/config.rst

Small typo in the container documentation

Small typo (changed contained --> container)

---

launch.sh

The main version check above (`version_check="^(1.8|9|10|11|12)"`) works fine, but when deciding whether to append additional args for Java 9+, missing parentheses meant that Java 1.8.0_212 also matches the regex and is being considered 9+, causing an error due to incompatible arguments.

Fix Java version detection in launch.sh

---

Makefile
README.md
packing.gradle

When I tried building a modified Nextflow version, I noticed that the standalone binary generated by `make pack` command works fine but does not include support for GA4GH/TES functionality. This PR fixes it.
Signed-off-by: Kirill Tsukanov <tsukanoffkirill@gmail.com>

Include GA4GH support into the standalone binary (make pack)

---

modules/nf-ga4gh/src/main/nextflow/ga4gh/tes/executor/TesTaskHandler.groovy

This is a new attempt for:
https://github.com/nextflow-io/nextflow/pull/1689
Instead of changing the toGiga function, we are defining a new toGiga function in the `TesTaskHandler` class instead.

Passing exact memory to executors in GiB

---

modules/nextflow/src/main/groovy/nextflow/file/FilePorter.groovy

Fixes https://github.com/nextflow-io/nextflow/issues/1552
The comments should explain it. I tested locally.

stage files to tmp files, then atomically move

---

docs/getstarted.rst

Adding documentation about the `CAPSULE_LOG` environment variable for less verbose logs.
See https://github.com/nextflow-io/nextflow/issues/1800#issuecomment-730168723

Docs for nextflow installation CAPSULE_LOG variable

---

docs/process.rst

This PR updates a minor typo in the `stub-run` docs.

update the stub command docs

---

docs/config.rst

Minor: add inline code formatting to the `-params-file` item
Following on from https://github.com/nextflow-io/nextflow/pull/855 and https://github.com/nextflow-io/nextflow/commit/1ae3855ca4ff7a7763e2c0d52cf91577853edb82

Add code highlighting to -params-file

---

docs/charliecloud.rst
docs/config.rst
modules/nextflow/src/main/groovy/nextflow/container/CharliecloudBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/container/CharliecloudCache.groovy
modules/nextflow/src/test/groovy/nextflow/container/CharliecloudBuilderTest.groovy
modules/nextflow/src/test/groovy/nextflow/container/CharliecloudCacheTest.groovy

Hi @pditommaso,
I have encountered some rough edges when running nextflow with charliecloud, which occur when running from the user $HOME directory.
I think the problem is that Charliecloud does not support passing mountflags with bind-mounted directories as opposed to Singularity for example (I believe that is what the `readOnlyInputs` flag is there for, please correct me if I'm wrong).
So in order to make sure the work directory is writeable, this removes the `readOnlyInputs` logic for Charliecloud entirely and ensures that mounted directories are always writeable in the container.
Further changes:
* addresses a breaking change that will land in Charliecloud 0.23 (`ch-grow pull` is now `ch-image pull`)
* adds the functionality to specify a directory that is mounted to /tmp within the …

Charliecloud improvements

---

modules/nextflow/src/main/groovy/nextflow/container/SingularityBuilder.groovy
modules/nextflow/src/test/groovy/nextflow/container/SingularityBuilderTest.groovy

This PR reverts the changes introduced in #1833  to singularity CPU/memory options as they are not directly related to resource limiting and operate at the vm level.
This issue was raised in #1869

Reverts the singularity CPU/memory options 

---

docs/azure.rst
docs/channel.rst
docs/config.rst
docs/dsl2.rst
docs/example.rst
docs/executor.rst
docs/google.rst
docs/metadata.rst
docs/operator.rst
docs/process.rst
docs/script.rst
docs/singularity.rst

Changes are mostly in Processes, Channels, and Operators because that's how far I've read the tutorial so far.

Fixed typos and grammar issues in tutorial

---

docs/charliecloud.rst
modules/nextflow/src/main/groovy/nextflow/container/CharliecloudBuilder.groovy
modules/nextflow/src/test/groovy/nextflow/container/CharliecloudBuilderTest.groovy

Hi,
With charliecloud v[0.22](https://github.com/hpc/charliecloud/releases/tag/v0.22), ENV layers of docker containers are saved to
a file located in `$IMAGE/ch/environment` when the container is pulled.
Hence it is no longer necessary to pass for example PATH variables explicitly via the env scope, because we can just read it from `/ch/environment`

charliecloud: get container environment from file

---

docs/google.rst

This PR adds a reference the possible `exitStatus` available for GCP.
**References:**
https://github.com/nextflow-io/nextflow/issues/1912
https://github.com/nextflow-io/nextflow/discussions/1913

Add the tip for GCP exitStatus

---

docs/process.rst

This is a super minor change but may prevent some confusion about one of the benefits of using template files—being able to test them independently from the nextflow pipeline.
In this case, using the ablative preposition *from* indicates how the template files may be tested apart from the pipeline.
Signed-off-by: Brandon Cazander <bcazander@canexiahealth.com>

Clarify how template files can be tested independently from the pipeline

---

modules/nextflow/src/main/resources/nextflow/trace/assets/ReportTemplate.js

The datatables render function provides a `type` parameter, which is set
to the string `sort` when sorting by the column. Returning the raw data
when `type == 'sort'` allows the sorting to work while still showing the
human-readable form for display.
Fixes: #1573
Signed-off-by: Brandon Cazander <bcazander@canexiahealth.com>

Properly sort human-readable tasks in report

---

modules/nextflow/src/main/groovy/nextflow/scm/GitlabRepositoryProvider.groovy
modules/nextflow/src/test/groovy/nextflow/scm/GitlabRepositoryProviderTest.groovy

Current Gitlab provider implementation fails to retrieve content of files that are not at the root of the repository. This is due to that the `path` parameter at the API URL must be encoded to escape URL characters like a slash.

Encode path parameter at GitLab getContentUrl

---

docs/channel.rst

This commit fixes a very minor typographical error where the sentence starts with "In you need..." instead of "If you need...".

fix minor typographical error

---

docs/dsl2.rst

I had to poke around to get this to work, adding it here to save other folks time.
I'm not entirely sure why it doesn't require a comma like the other named output does, but....

Add example for using named stdout in dsl2.

---

docs/config.rst

With the latest Tower release, the concept of workspace comes into play, https://github.com/seqeralabs/nf-tower-docs/pull/72
This PR adds the documentation for `workspaceId` within the `Tower` scope.

Add the setting for workspace

---

plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchTaskHandler.groovy

Instead of reporting a generic error message, with these changes, Nextflow fetches the actual error code and message from the Batch API and returns them to the user.
For instance, this is the output if an invalid docker image is specified in the `container` option of a process:
<pre>
N E X T F L O W  ~  version 21.05.0-edge
Launching `main-azure.nf` [berserk_euler] - revision: 2086f6cebe
executor >  azurebatch (1)
[e9/06af2f] process > sayHelloInItalian (1) [  0%] 0 of 1
[-        ] process > sayHelloInFrench      -
[-        ] process > sayHelloInSpanish     -
[-        ] process > sayHelloInEnglish     -
[AZURE BATCH] Task failed. ERROR code: ContainerInvalidImage; message: One or more container images specified are invalid
Error executing process > 'sayHelloInItalian (1)'
Caused by: …

Azure Batch executor: report error code and messages for failed Tasks.

---

docs/conda.rst
docs/config.rst
modules/nextflow/src/main/groovy/nextflow/conda/CondaCache.groovy
modules/nextflow/src/main/groovy/nextflow/util/CustomThreadPool.java
modules/nextflow/src/test/groovy/nextflow/conda/CondaCacheTest.groovy

Initiating the work for `mamba` support in conda.
Planned features are 
~A `mamba` directive with `micromamba` option to users to use `micromamba` which doesn't rely on a base environment - see [here](https://github.com/mamba-org/mamba/blob/master/docs/source/micromamba.md#Installation)~
We have decided to implement this as a config setting for `conda` scope.
```nextflow
conda {
useMamba = true
}
```

Add support for using mamba with conda

---

Makefile
plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchTaskHandler.groovy

Similarly to https://github.com/nextflow-io/nextflow/pull/2099, this change reports the reason why a job in AWS Batch has failed.
For example:
<pre>
executor >  awsbatch (1)
[de/8a1a36] process > sayHelloInItalian (1) [100%] 1 of 1, failed: 1 ✘
[-        ] process > sayHelloInFrench      -
[-        ] process > sayHelloInSpanish     -
[-        ] process > sayHelloInEnglish     -
Error executing process > 'sayHelloInItalian (1)'
Caused by:
ECS was unable to assume the role 'arn:aws:iam::.....:role/ecsInstanceRole' that was provided for this task. Please verify that the role being passed has the proper trust relationship and permissions and that your IAM user has permissions to pass this role.
</pre>
Instead of the generic message:
<pre>
executor >  awsbatch (1)
[c7/a76987] process > …

AWS Batch: provide additional details about the reason why a job has failed.

---

docs/azure.rst
plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy
plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzPoolOpts.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzBatchServiceTest.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/config/AzureConfigTest.groovy

This PR attaches the user identity to the pool. There are two options:
1) If the configuration specifies `runAs`, the task is run under that user. The assumption here is that the user already exists on the execution node in the pool.
2) `runAs` is omitted. In this case, the usual auto-user identity is explicitly attached to the task. For this identity, it is also possible to set `privileged` to `true` to run the task under elevated access (see https://docs.microsoft.com/en-us/azure/batch/batch-user-accounts#elevated-access-for-tasks).
Technically, Azure Batch also offers the possibility to create a user on the fly in the pool, but I don't feel it is needed in this context. Either the auto-user or the pre-existing user should cover all the use cases I can think of.

Run tasks under user accounts in Azure Batch

---

docs/sharing.rst

Add a note for private server configuration endpoint specification, with GitHub Enterprise V3 example.
Addresses #2148

docs sharing: add API endpoint note for private servers

---

plugins/nf-amazon/build.gradle

Upgrade AWS SDK minor version from `1.11.542` to `1.11.1034` to allow EFS support.

Upgrade AWS SDK minor version

---

modules/nextflow/src/main/groovy/nextflow/k8s/client/K8sClient.groovy

Working with Kubernetes and Nextflow I sometimes got an exception socket-reset, which cases the whole workflow to fail. 
This is the exception trace:
```
...
Jun-17 12:07:25.401 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'preprocessing:preprocess (LT05_L1TP_183035_19891106_20180210_01_T1)'
Caused by:
Connection reset
java.net.SocketException: Connection reset
at java.net.SocketInputStream.read(SocketInputStream.java:210)
at java.net.SocketInputStream.read(SocketInputStream.java:141)
at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
at sun.security.ssl.InputRecord.read(InputRecord.java:503)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367 …
```

Fix: Connection-reset crashes the workflow

---

modules/nextflow/src/main/groovy/nextflow/datasource/SraExplorer.groovy

This PR addresses https://github.com/nextflow-io/nextflow/issues/2237 and implements the fix as per the PR on the `nf-core/fetchngs` workflow https://github.com/nf-core/fetchngs/pull/26/files

Accomodate the updated URL for ena API

---

plugins/nf-sqldb/build.gradle
plugins/nf-sqldb/src/main/nextflow/sql/config/SqlDataSource.groovy
plugins/nf-sqldb/src/test/nextflow/sql/config/SqlDataSourceTest.groovy

I noticed that through the new `nf-sqldb` plugin, we have already added support for 
- h2
- mysql
- mariadb
- postgresql
I thought that it makes sense to add `sqlite` driver since it is quite popular and is often used by CLI tools as a simpler database.
I'd be happy to accomodate any change/enhancement requests.

Add sqlite jdbc driver for the nf-sqldb plugin

---

.github/workflows/build.yml
docs/dsl2.rst
docs/process.rst
modules/nextflow/src/main/groovy/nextflow/datasource/SraExplorer.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskContext.groovy
modules/nextflow/src/main/groovy/nextflow/script/BaseScript.groovy
modules/nextflow/src/main/groovy/nextflow/script/ScriptMeta.groovy
modules/nextflow/src/test/groovy/nextflow/datasource/SraExplorerTest.groovy
modules/nextflow/src/test/groovy/nextflow/processor/TaskContextTest.groovy

This PR replaces #2263 adding some minor refactoring and unit testing.

Add ability to define templates library at module level

---

docs/dsl2.rst

A small typo leads to the misconjugated verb "define" in this sentence.

Small typo

---

docker/Dockerfile

So when we went to targeted platform builds, instead of copying `docker` (the bin), we started copying `docker` the folder.
See my local `dist` after a `make dist/docker`:
```
nextflow $ find docker/dist 
docker/dist      
docker/dist/linux
docker/dist/linux/amd64                                                                                   
docker/dist/linux/amd64/docker                                                                            
docker/dist/linux/amd64/docker-runc                                                                       
docker/dist/linux/amd64/docker-init           
docker/dist/linux/amd64/dockerd                                                                           
docker/dist/linux/amd64/docker-containerd-ctr …
```

fix docker bin in image PATH

---

docs/operator.rst

The property that `a.cross(b)` is not equal to `b.cross(a)` reflects non-commutativity of the operator not reflexivity.

Correct description of cross

---

.github/workflows/build.yml

Since Java 17 is the new LTS and is already supported by NF, I thought it might be the right to update the automated test template as well.

Test with java-17 LTS

---

modules/nextflow/src/main/groovy/nextflow/config/ConfigParser.groovy
modules/nextflow/src/test/groovy/FunctionalTests.groovy
modules/nextflow/src/test/groovy/nextflow/config/ConfigParserTest.groovy
modules/nf-commons/src/main/nextflow/extension/Bolts.groovy
modules/nf-commons/src/test/nextflow/extension/BoltsTest.groovy

This fixes #1982, #2166, #2247 and #2358
The first three issues were caused by a lack of cloning which allowed mutability of values where they should have been immutable.  
The last issue required a deep merge vs a `putAll` to avoid overwriting multiple values at the same level when you are overriding them on the command line.

Fix for nested params with the same name

---

docs/dsl2.rst

Make clear that include must be outside of workflow definitions. This worked until 21.04.3 but then was disabled:
- https://github.com/nextflow-io/nextflow/issues/2519
- https://github.com/nextflow-io/nextflow/issues/2162

detail on `include` statements

---

modules/nextflow/src/main/groovy/nextflow/k8s/K8sDriverLauncher.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/K8sDriverLauncherTest.groovy

Some pipelines need to pass -entry parameter. Make it work with kuberun executor.

Add -entry parameter to pass in k8s executor

---

plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy

This PR tries to address the issue mentioned in https://github.com/nextflow-io/nextflow/discussions/2510. 
I tried a loop of 10 executions and didn't get the timeout error. Before this change, I got 2 timeouts out of the 10 executions. I can't be 100% sure this fixes it once and for all. But, at least, it seems to limit its frequency.

Fix docker timeout issues.

---

docs/process.rst
modules/nextflow/src/main/groovy/nextflow/k8s/model/PodOptions.groovy
modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/model/PodSpecBuilderTest.groovy

Closes #2390 
This PR adds support for affinity expressions in the pod directive. Examples of affinity can be found [here](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity). Affinity is used to assign pods to nodes, similar to a node selector, but is more expressive and also allows for soft constraints.
Example:
```groovy
pod = [
affinity: [
nodeAffinity: [
requiredDuringSchedulingIgnoredDuringExecution: [
nodeSelectorTerms: [
[key: "gpu-type", operator: "NotIn", values: ["T4"]]
]
]
]
]
]
```
maps to pod config:
```yaml
spec:
affinity:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: gpu-type
operator: NotIn
values: [T4]
```

Added affinity option to pod directive

---

docs/awscloud.rst

This should help avoid https://github.com/nextflow-io/nextflow/issues/2322
Should we modify the miniconda example to use a path that's definitely unique, e.g. `/opt/aws-ecs-mount/conda` instead of something in `$HOME`, to further reduce the chance of a conflict?

Docs: Warn about AWS CLI grandparent path in container

---

docs/dsl2.rst

While I was working with DSL2, I found several typos and some inconsistencies across the documentation. 
This PR aims at fixing them and improving a bit the readability of this section.

Review DSL2 documentation. Fix typos, improve consistency across sections.

---

docs/azure.rst

This PR builds upon the https://github.com/nextflow-io/nextflow/pull/2355 and updates the docs for the `azure.registry.*` scope.

Update the azure docs for registry

---

plugins/nf-sqldb/build.gradle
plugins/nf-sqldb/src/main/nextflow/sql/config/SqlDataSource.groovy
plugins/nf-sqldb/src/test/nextflow/sql/config/SqlDataSourceTest.groovy

This PR follows up from the discussion on https://github.com/nextflow-io/nf-sqldb/discussions/5 
I've relied on the Athena database generated by crawling the SRA Metadata as described here the instructions shared in https://www.ncbi.nlm.nih.gov/sra/docs/sra-athena.
The exact instructruction to setup the necessary tables/database on the AWS side are descibed in the official walkthrough https://www.youtube.com/watch?v=_F4FhcDWSJg
1. Populate the JDBC URL correctly for the Athena driver with the correct 
- `AWSRegion`
- `S3OutputLocation`
```
jdbc:awsathena://AwsRegion=us-east-1;S3OutputLocation=s3://MY_BUCKET_NAME/AWS_GLUE_OUTPUT_DIR/'
```
2. Add the configuration for your AWS account for the Athena JDBC driver
```
sql {
db {
athena {
url = …
```

Add the AWS Athena JDBC driver for nf-sqldb plugin

---

plugins/build.gradle

bugfix: remove gradle logs about tasks dependencies

bugfix: remove gradle logs about tasks dependencies

---

modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy

Resolve the configuration to show at Tower when it is only enable using configuration file. 
Example config file:
```
tower {
enabled = true
}
```
See issue #2641 and https://github.com/seqeralabs/nf-tower/issues/338
Signed-off-by: Jordi Deu-Pons <jordi@jordeu.net>

Resolve config when Tower is enabled using the config file

---

nextflow

resolve #2298
the idea is to extract the first param between double quotes as the java path using a regexp 

bugfix: allow blank spaces in java path

---

modules/nextflow/src/main/groovy/nextflow/config/ConfigParser.groovy
modules/nextflow/src/main/groovy/nextflow/executor/SimpleFileCopyStrategy.groovy
modules/nextflow/src/test/groovy/nextflow/config/ConfigBuilderTest.groovy

resolve #2701
the problem comes because we are using always `last` config in the stack but when we are starting to parse the config into a profile we need to use the `first` as it's the main config in the tree

bugfix: use first config in stack when is into profile

---

packing.gradle

When building docker, use just compiled version of nextflow, not system wide that might not be even installed.

Use compiled nextflow instead of system wide

---

modules/nextflow/src/main/groovy/nextflow/k8s/K8sDriverLauncher.groovy

- Account for background scenario.
- A user who launches nextflow with background flag wants to exit after pod has started.
- Fix grammer in log message.
- Fixes an issue if a user launches nextflow with "-bg", the application will wait until the run pod state has changed from running. 
Signed-off-by: kfrancisdev <kfrancisdev@gmail.com>

Wait for pod End background scenario 

---

modules/nextflow/src/main/groovy/nextflow/k8s/client/K8sClient.groovy

Return code 500 from kubernetes api is mostly a temporary error like timeout, so we should try again in these cases.

Deal with k8s api timeouts and similar errors

---

docs/process.rst
modules/nextflow/src/main/groovy/nextflow/k8s/model/PodOptions.groovy
modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/model/PodSpecBuilderTest.groovy

This PR adds the `tolerations` pod option, which allows a pod to "tolerate" certain node taints during scheduling. Can be useful for situations where a node is designated for a specific use case (special CPU type, belongs to certain user group, etc), so it will only be scheduled to users who specifically tolerate the taint.
I also reorganized some of the pod-related classes to be more readable. I pushed two separate commits so that you can distinguish the toleration-specific changes from the general changes.

Add tolerations pod option

---

.github/workflows/build.yml

The PR actions are not started automatically: https://github.com/nextflow-io/nextflow/pull/2781
It seems to be related to https://github.com/nextflow-io/nextflow/commit/6e23e0368b2d8baca5a42d45e6de43493e22ef02.
Based on [this](https://frontside.com/blog/2020-05-26-github-actions-pull_request/), synchronize should do the job.

Start Github Actions also for edited PRs

---

docs/config.rst
plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchTaskHandler.groovy
plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsOptions.groovy
plugins/nf-amazon/src/main/nextflow/cloud/aws/util/S3BashLib.groovy
plugins/nf-amazon/src/test/nextflow/cloud/aws/batch/AwsBatchTaskHandlerTest.groovy

This PR adds the missing `--sse` in AWS job launcher when the storage encryption is specified. 
It also add the possibility to enable the debugging mode for `aws` cli commands

Fix 2808 missing sse flag

---

modules/nextflow/src/main/groovy/nextflow/extension/OpCall.groovy

As the pipeline fails if the DeprecationException is thrown, I specified the message accordingly.

Specified deprecation message

---

docs/cli.rst

Updated the documentation for `--params-file` and `self-update`

Document params-file and improve self-update 

---

modules/nextflow/src/main/groovy/nextflow/script/ProcessDef.groovy
modules/nextflow/src/main/groovy/nextflow/script/WorkflowDef.groovy
modules/nextflow/src/test/groovy/nextflow/script/ScriptDslTest.groovy

feature: improve error message

---

modules/nextflow/src/main/groovy/nextflow/processor/TaskPollingMonitor.groovy

In rare cases, the following code
https://github.com/nextflow-io/nextflow/blob/7f7cdadc6a36d0fb99ef125f6c6f89bfca8ca52e/modules/nextflow/src/main/groovy/nextflow/k8s/client/K8sClient.groovy#L301-L324
throws an exception which is then handled here:
https://github.com/nextflow-io/nextflow/blob/7f7cdadc6a36d0fb99ef125f6c6f89bfca8ca52e/modules/nextflow/src/main/groovy/nextflow/processor/TaskPollingMonitor.groovy#L537
In that cases, the failed pod is again and again recognized as failed, and another new instance is started (maxRetries often).
In the maxRetries + 1 case, Nextflow fails the workflow, as all retries are exhausted. 
The problem here is that the failed pod is never evicted, and the exception handling happens again and again.
I can hardly reproduce the error.

Evict pod and decrease process forks if pod is restarted after exception

---

docs/_static/theme.css
docs/cli.rst
docs/conf.py
docs/dsl2.rst

Closes #2819 
This PR includes the following changes:
- Add "Edit on Github" button (top-right)
- Add Nextflow logo (top-left)
- Change code blocks to neutral gray background instead of mild vomit
- Change links to Nextflow green (copied from nextflow.io)
- Adjust admonitions (notes, tips, warnings, etc) to work with Nextflow green
Here is a sample screenshot where I try to represent all the style changes:
Best to view it in your browser to make sure. Let me know if you want to adjust any style rules.

Customize docs theme

---

plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzPoolOpts.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzBatchServiceTest.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/config/AzureConfigTest.groovy

This PR addresses the deprecation of CentOS-8 https://github.com/Azure/Batch/issues/119 , the defaults for a Nextflow pool have become a bit problematic.
From experience with some clients the straight-forward solution seems to be to move to `Ubuntu` based base image rather than `CentOS 7.8` and therefore I've gone ahead and changed those settings.
Happy to accommodate any feedback 😊

Updating the default SKU for Azure Batch

---

modules/nextflow/src/main/groovy/nextflow/script/BaseScript.groovy

This PR adds a more actionable error message when running a DSL2 script 
missing the `workflow` definition.

Improve missing workflow err message [ci skip]

---

docs/executor.rst
plugins/nf-google/src/main/nextflow/cloud/google/lifesciences/GoogleLifeSciencesHelper.groovy
plugins/nf-google/src/main/nextflow/cloud/google/lifesciences/GoogleLifeSciencesSubmitRequest.groovy
plugins/nf-google/src/main/nextflow/cloud/google/lifesciences/GoogleLifeSciencesTaskHandler.groovy
plugins/nf-google/src/test/nextflow/cloud/google/lifesciences/GoogleLifeSciencesHelperTest.groovy
plugins/nf-google/src/test/nextflow/cloud/google/lifesciences/GoogleLifeSciencesTaskHandlerTest.groovy

This PR adds support for the time directive in the Google Lifesciences API executor.
Currently, no timeout value is passed in the API requests which means that google will assign a default value of 7 days.
This can be a problem for long running processes and no way to change this value in nextflow.
This PR fixes this by passsing the processes time directive as a timeout parameter.
In case the timeout is exceeded the task will fail with error code 4 and message: `A user defined timeout has expired.`

Add support for time process directive in GLS executor

---

modules/nextflow/src/main/resources/nextflow/executor/command-run.txt
modules/nextflow/src/test/groovy/nextflow/executor/test-bash-wrapper-with-trace.txt
modules/nextflow/src/test/groovy/nextflow/executor/test-bash-wrapper.txt
plugins/nf-google/src/test/nextflow/cloud/google/lifesciences/bash-wrapper-gcp.txt

Defining a scratch Directory which not yet exists leads to an exception.
This PR solves that issue.
`nextflow test.nf -process.scratch /tmp/nextflow/`
```
N E X T F L O W  ~  version 22.04.0
Launching `test.nf` [spontaneous_poitras] DSL1 - revision: 0f88566b47
executor >  local (1)
[dd/7f3a23] process > a [  0%] 0 of 1
a: errorCount: 1, retryCount: 1
Error executing process > 'a'
executor >  local (1)
[dd/7f3a23] process > a [100%] 1 of 1, failed: 1 ✘
a: errorCount: 1, retryCount: 1
Error executing process > 'a'
Caused by:
Process `a` terminated with an error exit status (1)
Command executed:
echo hello world
Command exit status:
1
Command output:
(empty)
Command wrapper:
mktemp: failed to create directory via template ‘/tmp/nextflow/nxf.XXXXXXXXXX’: No such file or directory
Work dir: …
```

[Bugfix] Do not crash if scratch dir does not exist

---

.gitignore
plugins/nf-sqldb/build.gradle

Athena Driver is included in test classpath but not in the distribution zip due the `application` gradle plugin doesn't include files if not in `src/dist` directory

bugfix: add AthenaJdbc into distribution zip

---

modules/nextflow/src/main/groovy/nextflow/scm/AzureRepositoryProvider.groovy
modules/nextflow/src/test/groovy/nextflow/scm/AzureRepositoryProviderTest.groovy

Azure URL can have 2 or 3 tokens in the repo name (organization / project / repo ) but currently we are using only 2 of them
closes #2384

bugfix: resolve azure devops repositories when projectId is present

---

modules/nextflow/src/main/groovy/nextflow/executor/LsfExecutor.groovy

Debug log for LsfExecutor `RESOURCE_RESERVE_PER_TASK` config should show `perTaskReserve` rather than `perJobMemLimit`.

Update debug log for LsfExecutor RESOURCE_RESERVE_PER_TASK

---

plugins/nf-sqldb/build.gradle

we missed to link tasks dependencies between copyPlugin and copyAthen tasks

bugfix: remove gradle message in nf-sqldb

---

.github/ISSUE_TEMPLATE/general_question.md
CONTRIBUTING.md
README.md

Nextflow has [recently moved to Slack](https://www.nextflow.io/blog/2022/nextflow-is-moving-to-slack.html) and the link to the Slack community chat is the one shown in the Nextflow official website. This pull request updates the references from the Nextflow Gitter channel to Slack in the README.md, CONTRIBUTING.md and general_question.md file.

Update link for questions related to Nextflow

---

.github/ISSUE_TEMPLATE/general_question.md
CONTRIBUTING.md
README.md

This change is related to the updates and discussions that occurred in https://github.com/nextflow-io/nextflow/pull/2917 and
https://github.com/nextflow-io/website/pull/51.

Update temporary slack join link with a permanent one

---

modules/nextflow/src/main/groovy/nextflow/util/NameGenerator.groovy

Add Vital Brazil and César Lattes, two of the most famous Brazilian scientists, to the list of random names.
Signed-off-by: Marcel Ribeiro-Dantas <ribeirodantasdm@gmail.com>

Add more scientists to the list of random names

---

modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy
modules/nextflow/src/test/groovy/FunctionalTests.groovy
modules/nextflow/src/test/groovy/nextflow/script/ScriptRunnerTest.groovy

this PR closes #2926 
don't know why but if we include new tests in `FunctionalTests` a script from `ScriptRunnerTest`fails so at the end I marked as ignored, @pditommaso maybe you find the reason

feature: improve error reporting for custom function

---

plugins/nf-amazon/src/main/com/upplication/s3fs/S3OutputStream.java
plugins/nf-amazon/src/resources/META-INF/MANIFEST.MF

After several tests with huge files (500GB) and playing with the Xmx param, the only situation I found can be problematic is when some part fails
In this case, we continue uploading parts instead of stopping the upload 
closes #2230

feature: fail fast uploads to s3

---

docs/config.rst
modules/nextflow/src/main/groovy/nextflow/executor/LsfExecutor.groovy

Closes #2862 
Also adds `executor.perTaskReserve` config option to override LSF config file.

Override lsf.conf settings with nextflow config settings

---

docs/config.rst

This PR adds the documentation for `aws.client.s3PathStyleAccess` which is often used for S3-like storage systems.

Document the aws.client.s3PathStyleAccess config

---

docker/Dockerfile

The Dockerfile uses a clever trick to install the `ps` binary without all the extra stuff in the `procps-ng` package. However, that leaves ps without several shared library files. This PR copies those shared libraries into the final docker image. Tested on my local machine and ps works now.

fix: add ps shared objects to Dockerfile

---

plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchTaskHandler.groovy
plugins/nf-amazon/src/test/nextflow/cloud/aws/batch/AwsBatchTaskHandlerTest.groovy

Nextflow registers AWS batch jobs implicitly when
a new configuration is detected. A local cache maintained
to prevent unnecesary API request to check if job with
the same features is already created.
This commit fixes conflict in the cache keys creation
that caused two or more processes using the same container
image but different task settins e.g. containerOptions
to use a wrong job definition
Signed-off-by: Paolo Di Tommaso <paolo.ditommaso@gmail.com>

Fix AWS Batch job definition conflict

---

modules/nextflow/src/test/groovy/nextflow/script/bundle/ModuleBundleTest.groovy

Seems some update of Linux or some vendor Java versions are creating files with unexpected permissions in tests

feature: set explicit permissions for test files

---

docs/config.rst
plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchTaskHandler.groovy
plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsOptions.groovy
plugins/nf-amazon/src/test/nextflow/cloud/aws/batch/AwsBatchTaskHandlerTest.groovy

This PR adds the config option `aws.batch.logsGroup`. When this option is given, the aws batch executor will append the following configuration to each job definition:
```json
"logConfiguration": {
"logDriver": "awslogs",
"options": {
"awslogs-region": "${aws.region}",
"awslogs-group": "${aws.batch.logsGroup}"
}
}
```

Add support for aws batch logs group

---

docs/script.rst

Closes #3109 
Adds a note about the `files()` method. Just a minimal change for now as this content will probably be overhauled anyway in the new docs.

Document `files()` method

---

modules/nextflow/src/main/groovy/nextflow/executor/HyperQueueExecutor.groovy
modules/nextflow/src/test/groovy/nextflow/executor/HyperQueueExecutorTest.groovy

After doing some digging I found that hyperqueue does have a concept of "job state" vs task state, but it doesn't include the job state in the JSON output for `hq job list`. However, the quiet output mode simply returns the id and state of each job. Additionally, submitting a job with quiet output mode simply returns the job id or an error if the submit failed.
Therefore, I changed the executor to use quiet mode for submitting jobs and checking job status. The parsing logic is much simpler and should scale much better because the hq commands now return the minimum required information.

Use quiet output mode for hyperqueue executor

---

docs/operator.rst
docs/process.rst

From some other discussions (#2113 #2682), it looks like some users like to use the following pattern:
1. start with a channel of tuples or maps
2. use `multiMap` to split tuple/map into individual channels
3. invoke process with the channels from (2) as inputs
4. re-combine any output channels from (3) with `merge`
I think this pattern is used in order to avoid having long tuples for process input/output, but actually I think tuples are the best practice here, and this multiMap+merge pattern should be discouraged, because there is a risk of items not being re-combined correctly. I think it happens to work for now but order preservation is not guaranteed in principle.
I think the broader issue is that users would like to have better support for optional inputs/outputs and named inputs …

Add notes about merge, multiMap, and multiple input channels

---

docs/container.rst
modules/nextflow/src/main/groovy/nextflow/container/CharliecloudBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/container/CharliecloudCache.groovy
modules/nextflow/src/test/groovy/nextflow/container/CharliecloudBuilderTest.groovy
modules/nextflow/src/test/groovy/nextflow/container/CharliecloudCacheTest.groovy

As of Charliecloud `v0.28`, support in Nextflow stopped working because the expected CLI arguments for the pull command changed in that release. dd69f62c648cf1126225bbdf7e2e08004e8f4f94 addresses that, raising the required Charliecloud version to >=0.28.
Bonus:
Charliecloud has recently gained some nice additions and default settings. This allows for substantial cleanup of the code that
builds the bash wrapper, making some of my earlier workarounds obsolete. See 799e9c33235a1df8cae83fe769dc79b56cac890b for details.

Charliecloud support v3

---

modules/nextflow/src/main/groovy/nextflow/config/ConfigBuilder.groovy

this is a tiny typo, but its particular location led to a bit of extra confusion for me as a new user learning nextflow. I was specifying containers in each process, and when adding the `-with-docker` flag, because this error said "...but no image *were* specified", i thought it was searching for multiple (like i wanted), ha
Saying "...but no image *was* specified" i think will help anyone in a similar scenario realize more quickly that these particular options are looking for one container for the whole run :)
Signed-off-by: Mike Lee <michael.lee0517@gmail.com>

small typo in ConfigBuilder.groovy

---

docs/process.rst

before and afterScript directives are not executed inside the specified process container by design.
This behavior is not intuitive and will be fixed with `prolog` and `epilog` directives once implemented #540
Added a warning for the time being
Signed-off-by: Kirill Bulert <bulert@infai.org>

Add before-afterScript warning regarding containers

---

plugins/nf-amazon/src/main/com/upplication/s3fs/S3OutputStream.java
plugins/nf-amazon/src/test/com/upplication/s3fs/AwsS3NioTest.groovy

if after uploading a few bytes the flush is called, a new multipart is added to the queue but the minimum size required from AWS is 1Mb. 
No error is thrown until the end when completeMultiPart is called 
This PR maintains the current buffer as "active" if flush is calling and buffer length is under minimum

bugfix: intermediate multipart upload requires a minimum size

---

README.md

Noticed that the Readme still pointed readers to the older Google groups mailing list.

Update community discussion

---

plugins/nf-google/src/main/nextflow/cloud/google/lifesciences/GoogleLifeSciencesHelper.groovy
plugins/nf-google/src/test/nextflow/cloud/google/lifesciences/GoogleLifeSciencesHelperTest.groovy

Apply GCP resourceLabels to the VirtualMachine to propagate into the VM's so that the labels can be used for things like GCP billing tracking etc.
Related to https://github.com/nextflow-io/nextflow/pull/2853#issuecomment-1255683926
Signed-off-by: Doug Daniels <daniels.douglas@gmail.com>

Apply GCP resourceLabels to the VirtualMachine

---

modules/nextflow/src/main/groovy/nextflow/executor/HyperQueueExecutor.groovy
modules/nextflow/src/test/groovy/nextflow/executor/HyperQueueExecutorTest.groovy

New version on hyperqueue no longer caps the jobname to 40, so this could be removed
to allow longer jobnames to be used. 
see  #3250

Remove jobname truncation for hyperqueue executor 

---

modules/nextflow/build.gradle

Hello
This pull request fixes the specification of the Gradle task `test`.
Apart from groovy source files, this task depends on some test files that are located in `src/test/groovy` directory.
For example this [test](https://github.com/theosotr/nextflow/blob/master/modules/nextflow/src/test/groovy/nextflow/executor/BashWrapperBuilderTest.groovy#L256) depends on the [test-bash-wrapper-with-trace.txt](https://github.com/theosotr/nextflow/blob/master/modules/nextflow/src/test/groovy/nextflow/executor/test-bash-wrapper-with-trace.txt) file.
This commit considers those directories as inputs of this task so that tests are triggered whenever there are updates to any of the dependent test files.

Add missing inputs to the incremental task "test"

---

docs/config.rst

This PR adds a note to the docs about the incompatibility between some Java versions and 3rd party integrations that require TLSv1.2. Motivated by a number of Tower users who had issues configuring their mail notifications.

Add note about default mail ssl protocol [ci skip]

---

docs/.wci.yml

The https://workflows.community/systems/contribute website contains
information about numerous workflow managers. It gets some basic
information such as programming language, icon and headline from the
GitHub repository page of the workflow manager, but the developers
are free to add more details in a .wci.yml file that is fetched
every 12 hours by a GitHub Action of the workflow.community
project.
Signed-off-by: Marcel Ribeiro-Dantas <mribeirodantas@seqera.io>

Add nextflow info to be fetched by workflows.community website

---

modules/nextflow/src/test/groovy/nextflow/scm/AssetManagerTest.groovy
modules/nextflow/src/test/groovy/nextflow/scm/LocalRepositoryProviderTest.groovy

Two test (`AssetManagerTest` and `LocalRepositoryProviderTest`) fail if the user has set their own `defaultBranch` in `~/.gitconfig`.
Before this PR, the tests assume that the git `defaultBranch` is `master` and that assumption is hardcoded into the tests. This PR will use the local value if set in the most common way (in .gitconfig without any subsections).
Changing the `defaultBranch` is increasingly common - [Gitlab](https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/), [Github](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/), and [Atlassian](https://bitbucket.org/blog/moving-away-from-master-as-the-default-name-for-branches-in-git) have all moved to using `main` instead of `master`, so many developers now user …

Make tests pass if user has set git defaultBranch

---

docs/process.rst

most minor change. from looking at source, seems we want `tags` in the example.
haven't tested.

tag -> tags in docs

---

modules/nextflow/src/main/groovy/nextflow/plugin/extension/PluginExtensionProvider.groovy
modules/nf-commons/src/test/nextflow/plugin/extension/PluginExtensionMethodsTest.groovy
modules/nf-commons/src/testFixtures/groovy/nextflow/plugin/hello/HelloExtension.groovy

Currently, nextflow is calling the `init` method of the plugin in the first call of the Operator
This PR initializes the plugin once it's defined 
closes #3348

initialize the plugin once it's defined

---

plugins/nf-google/src/main/nextflow/cloud/google/util/GsBashLib.groovy

it seems new versions of Java include their stripIndent implementation 
don't understand very well where is the problem but using GString force to use groovy version in all implementations
closes #3375

use groovy stripIndent instead java version

---

modules/nextflow/src/main/groovy/nextflow/cli/CliOptions.groovy
modules/nextflow/src/main/groovy/nextflow/cli/CmdLog.groovy

I'm not sure TAB is the best, but we definitely have to think of something
better than \t, that shows up as blank space in the CLI help.
To make it more clear what I mean:

Improve default value in cli help of `nextflow log -s`

---

modules/nextflow/src/main/groovy/nextflow/container/ContainerBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/container/DockerBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/container/PodmanBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskBean.groovy
modules/nextflow/src/test/groovy/nextflow/container/DockerBuilderTest.groovy
modules/nextflow/src/test/groovy/nextflow/container/PodmanBuilderTest.groovy

This PR implements the use of cpu-shares for container CPUs allocation instead of Docker `--cpus` option. 
This allows better utilization of CPUs resources and makes consistent with the semantic of cpus request with other schedulers such as AWS Batch and Kuberneters. 
See also [here](https://www.batey.info/cgroup-cpu-shares-for-kubernetes.html) and #3338

Container cpu shares

---

modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/K8sDriverLauncherTest.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/K8sTaskHandlerTest.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/model/PodSpecBuilderTest.groovy

Remove cpu limits from K8s pod spec builder

---

docs/executor.rst
modules/nextflow/src/main/groovy/nextflow/executor/FluxExecutor.groovy
modules/nextflow/src/test/groovy/nextflow/executor/FluxExecutorTest.groovy

This pull request fixes one bug, and adds a new parameter to the FluxExecutor to support printing of output to stderr/stdout.
- Fixes https://github.com/nextflow-io/nextflow/issues/3419
Currently, for some reason the jobs listing is passing tests, but in testing with a workflow there is an error warning printed to the terminal as reported in https://github.com/nextflow-io/nextflow/issues/3419 The tweak suggested by Paolo there seems to fix the issue - I'm able to run the workflow from the terminal or web UI and I no longer see the warning.
We started a discussion in https://github.com/nextflow-io/nextflow/discussions/3421#discussioncomment-4204810 about how to enforce the process to print to stderr/stdout. I woke up and realized it was a "this is simple stupid" issue - we needed to add a …

fix bug with FluxExecutor jobs output

---

modules/nextflow/src/main/groovy/nextflow/executor/FluxExecutor.groovy
modules/nextflow/src/test/groovy/nextflow/executor/FluxExecutorTest.groovy

This is a tiny change to ensure that the flux.terminalOutput is correctly passed all the way from the config to the executor! For some reason with task.config, it's not there, likely because it's not known to the task to be parsed?
This was all @pditommaso thank you for the help! Once this is in we are good to go for Nextflow with Flux I think.
- This will close #3429 
Here is the fixed workflow (before this said the job didn't produce output):
Signed-off-by: vsoch <vsoch@users.noreply.github.com>

testing fix for config variables

---

modules/nextflow/src/main/groovy/nextflow/conda/CondaCache.groovy
modules/nextflow/src/main/groovy/nextflow/conda/CondaConfig.groovy
modules/nextflow/src/test/groovy/nextflow/conda/CondaCacheTest.groovy
modules/nextflow/src/test/groovy/nextflow/conda/CondaConfigTest.groovy
plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveClient.groovy
plugins/nf-wave/src/test/io/seqera/wave/plugin/WaveClientTest.groovy

This PR adds the support for custom conda channels.  
The channels can be specified in the nextflow config e.g. 
```
conda {
channels = ['bioconda','defaults']
}
```
They are used when creating the Conda environment via punctual packages specified via the `conda` directive e.g. 
```
process foo {
conda 'samtools'
} 
```
Note, custom channels are ignored when the `conda` directive specified a Conda recipe yaml file 
Signed-off-by: Paolo Di Tommaso <paolo.ditommaso@gmail.com>

Add support for custom conda channels

---

plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerArchiver.groovy
plugins/nf-tower/src/test/io/seqera/tower/plugin/TowerArchiverTest.groovy

When archiving files defined in an environment variable, we should assume that they are relative paths to `baseDir` no to the current working directory.
Given `NXF_ARCHIVE_DIR="/scratch,s3://fusionfs/archived"` when running a normal pipeline with Tower we have for example this variable `NXF_OUT_FILE=nf-3rvDYTUlUhJ1Ge.txt` that [here](http://github.com/nextflow-io/nextflow/blob/1ed2640a8bba0b43cdb69bb9fdfa5ed3308395bf/plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerArchiver.groovy#L133-L133) it ends resolved to this absolute path `/3rvDYTUlUhJ1Ge.txt` because the launcher is running at `/` folder. But then [here](http://github.com/nextflow-io/nextflow/blob/1ed2640a8bba0b43cdb69bb9fdfa5ed3308395bf/plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerArchiver.groovy#L125-L125) it is …

At TowerArchiver resolve envar paths relative to baseDir

---

docs/tracing.rst

The information is helpful when parsing the file with some sort of script. Information taken from: https://github.com/nextflow-io/nextflow/blob/fa400d5f3b5a32ac30117b85cc107f9edfa75e8d/modules/nextflow/src/main/groovy/nextflow/processor/TaskHandler.groovy#L127-L139

Add possible values of `status` in `trace.txt` to the documentation

---

docs/process.rst

Signed-off-by: Alexander Toenges <21218078+ATpoint@users.noreply.github.com>
Add a sentence on how to provide custom bash/shell options such as `pipefail` to the process definition.

add sentence on bash options

---

plugins/nf-google/src/main/nextflow/cloud/google/batch/logging/BatchLogging.groovy

Quoting will allow special characters, in particular ":", to be parsed. This should prevent the unparseable filter exception in https://github.com/nextflow-io/nextflow/issues/3353.
Signed-off-by: Aaron Golden <aegolden@google.com>

Quote the logName in the Cloud Logging filter

---

.gitignore

@pditommaso I know this is a bit silly, but it is quite useful to ignore the .vscode directories that get created by MS Visual Studio Code .. for those who use it for development purposes.
Signed-off-by: Marco De La Pierre <marco.delapierre@gmail.com>

Update .gitignore to include vscode dot dir

---

docs/sync-doc.sh
docs/tracing.rst
modules/nextflow/src/main/groovy/nextflow/container/UdockerBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/executor/OarExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/PbsExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/PbsProExecutor.groovy
modules/nextflow/src/main/resources/nextflow/executor/command-trace.txt
modules/nextflow/src/test/groovy/nextflow/container/UdockerBuilderTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/OarExecutorTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/PbsExecutorTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/PbsProExecutorTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/test-bash-wrapper-with-trace.txt
tests/checks/dynamic-storedir.nf/.checks
tests/checks/error.nf/.checks

Replace `egrep` with `grep -E`

---

modules/nextflow/src/main/groovy/nextflow/trace/ReportObserver.groovy
modules/nextflow/src/main/groovy/nextflow/trace/TraceFileObserver.groovy

Filename rolling has been deprecated, but comments in the source code were out of date. This PR fixes it.
Ref: https://github.com/nextflow-io/nextflow/issues/3186

Update source comments related to overwrite in trace/report [ci skip]

---

docs/metadata.rst

Per FD#2725, added a note explaining the difference in behavior between passing a git tag or branch name vs. passing a commit ID using the `-r` argument. 
Signed-off-by: Llewellyn vd Berg <113503285+llewellyn-sl@users.noreply.github.com>

Add note for revision vs commitID [ci skip] 

---

docs/cli.rst

Update `-r -revision` to describe behavior when passing a tag or branch, vs. passing a commit ID.
Signed-off-by: Llewellyn vd Berg <113503285+llewellyn-sl@users.noreply.github.com>

Update `-r` description [ci skip]

---

modules/nextflow/src/main/groovy/nextflow/container/CharliecloudBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/container/CharliecloudCache.groovy
modules/nextflow/src/test/groovy/nextflow/container/CharliecloudBuilderTest.groovy

This merge request is to add the `readOnlyInputs` option as discussed in the  **Charliecloud and shared cacheDir** #3367 issue.
With this modification:
- the default `readOnlyInputs` value is `false`
- if `readOnlyInputs` is `true`;
- the `-w` option is removed from the command
- the bound volumes are transformed to only mount the first folder of the path
For example, if I try to bind `/home/user/workdir/` to `/home/` the bound path will be `/home` to `/home`. By doing that, charliecloud doesn't try to `mkdir -p /home/user/workdir/` within the read-only container, the external path is bound at the `/home` directory level so all the subfolders are accessible with the user rights. If one tries to bind `/` I added an expection.
ps: Sorry for the code style, it's my first time coding in …

Add readOnlyInputs option for CharliecloudBuilder

---

modules/nextflow/src/main/groovy/nextflow/container/CharliecloudBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/container/CharliecloudCache.groovy
modules/nextflow/src/test/groovy/nextflow/container/CharliecloudBuilderTest.groovy

It turns out unit tests were not running, and this PR #3477 causes the build to fail reverting it
Reverts nextflow-io/nextflow#3477

Revert "Add readOnlyInputs option for CharliecloudBuilder"

---

plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerClient.groovy

In some cases, an `IOException` might happen when sending a request to Tower even if the returned HTTP code is a successful code such as `200 OK`:
```
Feb-02 17:06:22.569 [main] TRACE io.seqera.tower.plugin.TowerClient - Got error 200 - refreshTries=0 - currentRefresh=null
```
This change logs the exception trace in order to have more debugging information.

Log exception trace in Tower client

---

modules/nextflow/src/test/groovy/nextflow/cli/CmdCleanTest.groovy
modules/nextflow/src/test/groovy/nextflow/config/ConfigBuilderTest.groovy
modules/nextflow/src/test/groovy/nextflow/script/params/FileOutParamTest.groovy
modules/nextflow/src/test/groovy/nextflow/util/SimpleHttpClientTest.groovy
modules/nf-commons/src/test/nextflow/extension/FilesExTest.groovy

Some methods in the unit tests have string literal names with parentheses in the name. For some reason, this breaks the Groovy syntax highlighter (at least in VS Code and GitHub), so I found them with a regex and fixed them.

Fix syntax highlighting in tests

---

modules/nextflow/src/main/groovy/nextflow/executor/GridTaskHandler.groovy
modules/nextflow/src/test/groovy/nextflow/executor/GridTaskHandlerTest.groovy

Closes #3024 
Some grid executors pipe the wrapper script to their submit command (e.g. LSF). In this case, when a task fails and Nextflow prints an error message, the submit command is incorrect because it doesn't include the pipe. For example:
```
Caused by:
Failed to submit process to grid scheduler for execution
Command executed:
bsub
Command exit status:
-
Command output:
(empty)
```
The submit command in this case should be `bsub < .command.run`.
This PR changes the error message to append `< .command.run` to the command if the wrapper script was piped into the submit command.

Fix submit command in error message for grid executors that pipe wrapper script

---

docs/getstarted.rst

This PR documents the recommendations provided here: https://github.com/nextflow-io/nextflow/issues/3110#issuecomment-1212014907
I think we should explicitly point users to SDKMAN and at least one recommended distro, since we keep doing it in support tickets.

Add java install recommendations to docs

---

docs/config.rst

-Add clarification and example of named config scope nesting inside a config profile.  -Minor language fixes.
Signed-off-by: Llewellyn vd Berg <113503285+llewellyn-sl@users.noreply.github.com>

Clarify named config scope nesting

---

docs/conf.py

Every new year, the year in the copyright notice at the bottom must be manually updated. This PR fixes this by automatically setting the current year at every build.

Automatically update year in the copyright notice at the bottom [ci skip]

---

modules/nextflow/src/main/groovy/nextflow/fusion/FusionAwareTask.groovy
modules/nextflow/src/main/groovy/nextflow/fusion/FusionConfig.groovy
plugins/nf-wave/src/main/io/seqera/wave/plugin/cli/WaveDebugCmd.groovy
plugins/nf-wave/src/main/io/seqera/wave/plugin/cli/WaveRunCmd.groovy
plugins/nf-wave/src/test/io/seqera/wave/plugin/cli/WaveDebugCmdTest.groovy

Make it easier to debug a task that was launched from Tower. The way of using it is providing also the image container.
**Usage:**
``` 
nextflow plugin nf-wave:debug-task s3://<task-work-directory> <image>
```
If the image is a wave image (starting with `wave.seqera.io`) is it use as it is. But when the image is not a wave image then it is "waved" using given Nextflow configuration.
Example Nextflow config to use if you need to use credentials at `~/.aws/credentials`
```
$ cat nextflow.config 
wave {
enabled = true
}
fusion {
enabled = true
}
docker {
userEmulation = true
}
```
Previous debug mode is still supported in the same way `nextflow plugin nf-wave:debug-task <task hash>` to debug tasks launched locally with Nextflow CLI.
**Example usage:**

Add support for debuging a Fusion task launched from Tower

---

docs/config.rst
plugins/nf-amazon/src/main/com/upplication/s3fs/AmazonS3Client.java
plugins/nf-amazon/src/main/com/upplication/s3fs/S3FileSystemProvider.java

Based on discussions with Michael Kroell about the Glacier auto retrieval. See this [AWS documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/batch-ops-initiate-restore-object.html) for context.
- Don't specify expiration days if storage class is intelligent tiering (otherwise the restore will fail)
- Add glacierRetrievalTier config option (Standard, Expedited, Bulk)

Updates to S3 Glacier auto retrieval

---

packing.gradle

Brings the gradle dockerPack task up to date. It's useful to build Nextflow locally and run it in a container.

Update gradle dockerPack

---

docs/azure.rst
plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy
plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzPoolOpts.groovy

Closes #2702 
I followed the suggested implementation from the issue, but I didn't find any unit tests for creating pools. I also haven't tested it end-to-end because I don't have an Azure config set up yet.

Add azure batch pool virtualNetwork option

---

docs/process.rst

I initially opened this edit to add the `fair` directive, only to find it already present in the edit view. Is there a reason it is not shown on the doc site? What's the usual lag time between merge and publish?

Edit `fair` directive

---

modules/nextflow/src/main/groovy/nextflow/extension/GroupKey.groovy

See discussions in #3104 and #2660
When modifying maps, it is generally better to copy the map, e.g. `metadata + [id: 'foo']`. However, if the map contains a GroupKey, it won't work. This PR simply makes GroupKey cloneable so that you don't have to remove and re-add the group key to clone a map.

Make GroupKey cloneable

---

modules/nextflow/src/main/groovy/nextflow/cli/CmdKubeRun.groovy
modules/nextflow/src/main/groovy/nextflow/k8s/K8sDriverLauncher.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/K8sDriverLauncherTest.groovy

Using `kuberun` with `-plugins xy` does not yet hand this over to the head-pod. This is implemented in this PR. It would be nice to have this, especially for CWS.

Kuberun: add plugins to config

---

.github/workflows/build.yml

The build CI tests are already skipped when only editing `docs/**` for the `push` event, but not for the `pull_request` event. This means that they run on every PR even if it's only to the docs.
This adds the `paths-ignore` config to the `pull_request` event, the same as `push`.

Skip build CI for pull-requests too

---

docs/aws.md
docs/azure.md
docs/channel.md
docs/config.md
docs/google.md
docs/metadata.md
docs/operator.md
docs/process.md
docs/script.md
docs/secrets.md
docs/sharing.md
docs/tracing.md
docs/wave.md

I'm experimenting with something in the Markdown docs and wanted to run it by the two of you.
There are all of these huge tables, mostly on the Configuration page. They are hard to use because each option is packed onto a single line and you have to scroll horizontally to read a long option.
I converted some of these tables to definition lists and I think they are much better. Each option description is just a paragraph, so no more scrolling. I also moved version notes to separate lines so that they stand out. I think this change could set us up nicely in the future to expand on options that need it and just be more organized overall.
If you guys like what you see, I'll add these changes to the Markdown PR.

Convert large tables to definition lists

---

docs/channel.rst
docs/operator.rst
docs/process.rst

Documents for each operator whether it returns a queue channel or value channel.

Document return type of operators

---

modules/nextflow/src/main/groovy/nextflow/script/ScriptMeta.groovy

This PRs false positive warning message shown when importing twice the same function with a different alias. 
See https://github.com/nextflow-io/nextflow/issues/3765 for context

Fix invalid warning on func import

---

plugins/nf-amazon/src/main/nextflow/cloud/aws/AmazonClientFactory.groovy
plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsConfig.groovy
plugins/nf-amazon/src/main/nextflow/cloud/aws/fusion/AwsFusionEnv.groovy
plugins/nf-amazon/src/test/nextflow/cloud/aws/config/AwsConfigTest.groovy

The goal of this PR is to refactor the AWS authentication logic, so that:
* The AWS credentials chain is [used by default](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html)
* The `accessKey` and `secretKey` can be provided alternatively via nextflow.config file in the `aws` scope
* The AWS profile can be provided alternatively via nextflow.config file in the `aws` scope

AWS config refactor using AWS credentials chain

---

.github/workflows/build.yml

See discussion in https://github.com/nextflow-io/nextflow/pull/3839#issuecomment-1498736576
This PR changes the CI logic so that jobs only run on `push` to the `master` branch - ie. after PRs are merged, or on direct push to master.
The logic within the build steps is then simplified, so that jobs _always_ run on the `pull_request` event.
This should still mean that CI isn't double-triggered, but makes things a bit simpler and the logic a bit clearer when PRs are coming from forks / internal branches.

Propsal: Different CI trigger logic

---

modules/nextflow/src/main/groovy/nextflow/Channel.groovy

Not really a high priority item, but I discovered this `Channel.interval` factory and found that it didn't work, it would only emit one item. I checked the [Timer](https://docs.oracle.com/javase/7/docs/api/java/util/Timer.html) API and found that the wrong method was being used, so I fixed it.
I assume no one is using it since it currently doesn't work, but I guess an interval function is a good component of any reactive library. If you want to keep it then I can document it as well.

Fix `interval` channel factory

---

.github/workflows/docs.yml

See PR https://github.com/nextflow-io/nextflow/pull/3840 and discussion in https://github.com/nextflow-io/nextflow/pull/3839#issuecomment-1498691963
This PR adds a new CI workflow that has exactly the same name as the Nextflow build CI. It is only triggered in the complementary situation, so there should be no pull request where both run at the same time.
Having it here means that those tests can be set as required, but GitHub doesn't sit and wait forever for them to show up, meaning that pull-requests can be merged without forcing an admin override.

CI for docs

---

.github/workflows/build.yml
.github/workflows/docs.yml

Adding in the suggested changes from @pditommaso to run build CI tests on branches beginning with `test*` or `dev*` (in addition to tests on pull-requests).
See https://github.com/nextflow-io/nextflow/pull/3842#discussion_r1163009298

Run build CI tests on push to branches starting with `test*` or `dev*`

---

.github/workflows/build.yml
.github/workflows/docs.yml

* Remove sphinx version pin, this was breaking Jinja I think
* Add a trigger for the docs CI for workflow_dispatch
* Add specific job name, for required CI jobs
* Change workflow name, for nicer inspection in the UI
I actually tested this one in GitHub Actions [on my fork](https://github.com/ewels/nextflow/actions/runs/4675882335/jobs/8281504238) this time, instead of just testing commands locally. So I'm more confident that it'll work!
Sorry for the multiple-PR spam 😬 
Follow-on from https://github.com/nextflow-io/nextflow/pull/3842#issuecomment-1504813002

Fix docs CI

---

docs/conda.rst

Though `-with-conda true` works just like without the true if a
conda directive was specified, it tries to install `true` with
conda if none was specified. To make sure the same behavior will
occur with the same option, we should push for `-with-conda`
without the `true` in the docs.

Fix -with-conda option in the docs

---

plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzBatchServiceTest.groovy

This PR fixes the problem with the pool creation timestamp, that's caused by the increased Instant precision in the newer Java version resulting in a timestamp string not parsed by Azure

Fix Azure pool creation timestamp

---

plugins/nf-console/src/main/nextflow/ui/console/Nextflow.groovy

Closes #2689 and #3461 
This PR adds a few missing pieces to the nextflow console:
- set DSL mode to 2 by default
- fire the dataflow network after running the script
These changes solves issues where the console didn't support DSL2 syntax by default, and setting `nextflow.enable.dsl=2` would cause the execution to hang.
I determined the necessary changes by comparing the Nextflow console class to CmdRun and ScriptRunner, since these two classes are bypassed by the console.

Fix DSL2 support in nextflow console

---

modules/nextflow/src/main/resources/nextflow/executor/command-run.txt
modules/nextflow/src/test/resources/nextflow/executor/test-bash-wrapper-with-trace.txt
modules/nextflow/src/test/resources/nextflow/executor/test-bash-wrapper.txt
modules/nf-commons/src/main/nextflow/plugin/PluginUpdater.groovy
plugins/nf-google/src/test/nextflow/cloud/google/lifesciences/bash-wrapper-gcp.txt

This PR simplifies the stdout and stderr redirection made in the task launcher script removing the need to use two FIFO pipe redirections.

Improve task out redirect

---

docs/executor.rst
plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzBatchServiceTest.groovy

Closes #3865 
The issue OP technically asked for a time constraint on pools, but AFAIK it is only possible for tasks, also that is the model that Nextflow already uses via the `time` directive.

Support `time` directive in Azure Batch

---

modules/nextflow/src/main/groovy/nextflow/k8s/K8sTaskHandler.groovy

This problem occurred when a workflow was run with `k8s.debug.yaml = true`
The created `.command.yaml` file contained an args like this:
```
...
args:
- /bin/bash
- -ue
- !!org.codehaus.groovy.runtime.GStringImpl {}
...
```
Converting the GString to String looks like it should:
```
...
args: [/bin/bash, -ue, /input/data/work/aa/abf3408753f4c094567abc16d1e543/.command.run]
...
```

Fix problem args were not correctly represented in debug yaml

---

modules/nf-commons/src/main/nextflow/util/CacheHelper.java
modules/nf-commons/src/test/nextflow/util/CacheHelperTest.groovy

Close #3899 
Nextflow currently caches enums using their hash code, which is not guaranteed to be the same across runs. This PR updates the CacheHelper to use the enum string value instead. This way, renaming an enum value will break the cache but changing the enum ordering will not.

Support enums in cache helper

---

docs/_static/theme.css
docs/aws.md
docs/azure.md
docs/channel.md
docs/cli.md
docs/conda.md
docs/config.md
docs/container.md
docs/dsl2.md
docs/executor.md
docs/flux.md
docs/fusion.md
docs/getstarted.md
docs/google.md
docs/ignite.md
docs/kubernetes.md
docs/make-html.sh
docs/operator.md
docs/plugins.md
docs/process.md
docs/script.md
docs/secrets.md
docs/sharing.md
docs/spack.md
docs/tracing.md
docs/wave.md

This PR attempts to standardize the wording and placement of version notes in the documentation, so that they are easy to spot without distracting from the text.
- New features are marked as *New in version ...`, changes are marked as *Changed in version ...*.
- Use italics instead of admonitions so that there aren't so many admonitions.
- Add tons of missing version notes for new features from the last few release cycles.
Basically just more prep work for the website overhaul.

Cleanup version notes in docs

---

docs/config.md
plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy
plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzBatchOpts.groovy

Nextflow was leaving Azure Batch jobs around in active state after completion. This does the following:
- Nextflow now deletes jobs even if a task has failed
- If config `azure.batch.TerminateJobsOnCompletion` is true (default), it will set the job to automatically terminate after all tasks have finished. This no longer counts towards Azure Batch quota.
Fixes #3926

Azure jobs correctly deleted after completion

---

modules/nextflow/src/main/groovy/nextflow/container/CharliecloudBuilder.groovy
modules/nextflow/src/test/groovy/nextflow/container/CharliecloudBuilderTest.groovy

Close #3951 
In Charliecloud v0.32, the `--no-home` option was removed. It has been the default since version v0.31. Since Nextflow always adds this option, Nextflow won't work with Charliecloud v0.32 or later.
This PR removes the `--no-home` option from the builder. Users can preserve the old behavior by adding `--no-home` to `charliecloud.runOptions` or `process.containerOptions`.
I can add a note to the container docs as well if you want.

Remove `--no-home` default option from charliecloud builder

---

plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy
plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchTaskHandlerTest.groovy

When the method `findBestMachineType` fails to find a best candidate the `machineType` provided by the user should only be used if it is a correct machine type, and not if it's a list of families that can contain a wildcard. In that case, `machineType` should be empty so Google Batch will decide a custom type depending on the CPU and Memory allocated.

Fix invalid machine type setting when no valid machine type is found

---

modules/nextflow/src/main/groovy/nextflow/splitter/JsonSplitter.groovy

At the moment, the JsonSplitter abandons the list of valid options from `super`, leading to errors when splitting any Json string as noted by @mribeirodantas.
This fix ensures that the inherited valid methods are preserved.

Use full map of valid options for JsonSplitter creation

---

docs/wave.md

Update link in Nextflow documentation, previously linked to (broken) https://help.tower.nf/latest/credentials/registry_credentials, now links to https://help.tower.nf/latest/credentials/overview

Update link to Tower registry credentials docs.

---

docs/azure.md

Fixes a markdown error on the azure docs page. A warning didn't have a closing `:::`.

Fix error in Azure docs

---

docs/process.md
plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchTaskHandler.groovy

Nextflow is applying the accelerator type to the AWS Batch job definition. However, according to the [AWS documentation](https://docs.aws.amazon.com/batch/latest/APIReference/API_ResourceRequirement.html), the type must be "GPU", and does not support specific GPU types. It looks like the only way to control the GPU type is indirectly through the allowed instance types in a compute environment.
This PR ignores the accelerator type for AWS Batch and adds a warning if the type is specified, so that it's clear that it isn't supported.

Ignore accelerator type for AWS Batch

---

plugins/nf-ga4gh/src/main/nextflow/ga4gh/tes/executor/TesBashBuilder.groovy
plugins/nf-ga4gh/src/main/nextflow/ga4gh/tes/executor/TesExecutor.groovy
plugins/nf-ga4gh/src/main/nextflow/ga4gh/tes/executor/TesFileCopyStrategy.groovy
plugins/nf-ga4gh/src/main/nextflow/ga4gh/tes/executor/TesTaskHandler.groovy
plugins/nf-ga4gh/src/resources/META-INF/MANIFEST.MF
plugins/nf-ga4gh/src/test/nextflow/ga4gh/tes/executor/TesBashBuilderTest.groovy
plugins/nf-ga4gh/src/test/nextflow/ga4gh/tes/executor/TesTaskHandlerTest.groovy

Adds support for using remote bin with TES in a shared file system workdir. The shared file system mount on the server running the pipeline needs to be the same the mount in the image, so a mount off root is easiest. Code is based on the AWS Batch plugin's remote bin support. 
Also sets the TES name to the task name.
@pditommaso I see you have done all the updates in the plugin repository for the official plugins, do you want/need to handle that or should I create a pr there to go along with this one?

feat: add remote bin support for TES in a workdir

---

docker/Makefile

Close #2750 
Haven't tested it myself, just drafting a PR for anyone who wants to try a Nextflow docker image on ARM:
```bash
cd docker
make build-arm
```

Add rule to build Nextflow docker image for ARM

---

plugins/nf-azure/src/main/nextflow/cloud/azure/nio/AzFileAttributes.groovy

Using Azure Batch executor with storage account enabling hierarchical namespaces have problems publishing directories.
The problem is that for each directory azure will create an empty "stub blob" with a metadata field: `"hdi_isfolder": "true"`
Nextflow currently detects these as files and will create a download request for that stub blob using a directory path which will cause a BlobStorageException (Status code 400: InvalidInput)
This PR adds a simple to check to detect such blobs and mark those as directories.
Fixes: #4016, #2557

Fix invalid detection of hierarchical namespace stub blobs as files

---

docs/netlify.toml

Turn _off_ the new Netlify deployment previews, unless something in the `docs/` folder changes.

Netlify: No deployment (previews) unless 'docs/' files change

---

docs/tracing.md
modules/nextflow/src/main/groovy/nextflow/trace/TraceRecord.groovy
modules/nextflow/src/main/resources/nextflow/executor/command-trace.txt
modules/nextflow/src/test/resources/nextflow/executor/test-bash-wrapper-with-trace.txt

This adds the CPU model name to the trace files (to allow using this information for a CO2 footprint plugin) and accordingly to the `traceRecord`.
It is not added to any tests yet.

Add CPU model name to trace files and traceRecord

---

docs/aws.md
plugins/nf-amazon/build.gradle
plugins/nf-amazon/src/main/nextflow/cloud/aws/AwsClientFactory.groovy
plugins/nf-amazon/src/main/nextflow/cloud/aws/util/SsoCredentialsProviderV1.groovy

Close #2295 
I currently can't test it properly because we don't use SSO internally, but we will try to set up a test environment.
@multimeric feel free to give it a try in the meantime.

Add SSO credentials provider from AWS SDK v2

---

docs/config.md
docs/executor.md
modules/nextflow/src/main/groovy/nextflow/executor/SlurmExecutor.groovy
modules/nextflow/src/test/groovy/nextflow/executor/SlurmExecutorTest.groovy

This PR addresses #2054. 
Some SLURM cluster require memory to be defined per CPU using the `--mem-per-cpu` argument in the `sbatch` command and disallow using `--mem`. 
Currently, nextflow translates the `task.memory` directive into `--mem` only. 
The proposed changes introduces the boolean `executor.memPerCpu` option to execute `sbatch` with `--mem-per-cpu`. 
This is my first time working with the Nextflow codebase and using Groovy, so any help getting this to work is appreciated 🙏

feat: Allow SLURM executor option `--mem-per-cpu`

---

modules/nextflow/src/main/groovy/nextflow/executor/BashFunLib.groovy
modules/nextflow/src/test/groovy/nextflow/executor/BashFunLibTest.groovy
plugins/nf-amazon/src/test/nextflow/cloud/aws/batch/AwsBatchFileCopyStrategyTest.groovy
plugins/nf-amazon/src/test/nextflow/cloud/aws/batch/AwsBatchScriptLauncherTest.groovy
plugins/nf-amazon/src/test/nextflow/cloud/aws/util/S3BashLibTest.groovy
plugins/nf-amazon/src/test/nextflow/executor/BashWrapperBuilderWithS3Test.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzFileCopyStrategyTest.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/file/AzBashLibTest.groovy
plugins/nf-google/src/test/nextflow/cloud/google/lifesciences/bash-wrapper-gcp.txt
plugins/nf-google/src/test/nextflow/cloud/google/util/GsBashLibTest.groovy

`nxf_parallel` runs a number of processes in parallel, distributing them
across a limited number of workers.
Prior to PR #1884, errors were not being checked.  PR #1884 was
intended to remedy this but effectively only checked the _last_
command (or some subset of the commands) to exit (which was,
unfortunately the case that was tested for).
Processes that exit while there is still work going on were not being
"waited" on, so their exit status was not being checked, and failures
were escaping unnoticed.
This commit:
- updates the loop that's tracking the work so that it waits on
processes that have exited; and
- updates the test cases so that the failing command is _not_ the
last in the list and ensures that the templated text is as expected.
Note that an alternative change would be:
[[ -e …

Wait for _all_ child processes in nxf_parallel

---

modules/nf-commons/src/main/nextflow/util/InsensitiveMap.groovy
modules/nf-commons/src/test/nextflow/util/InsensitiveMapTest.groovy
modules/nf-httpfs/src/main/nextflow/file/http/XFileSystemProvider.groovy
modules/nf-httpfs/src/test/nextflow/file/http/XFileSystemProviderTest.groovy

Treat HTTP headers as case insensitive

---

modules/nextflow/src/main/groovy/nextflow/script/ScriptParser.groovy

Close #2082 #3325 
Some syntax errors in processes and workflows, such as missing/extra commas, are not handled well by the Groovy parser, likely because the custom DSL syntax makes it difficult to determine exactly which token is the cause. As a result, Groovy simply reports the opening brace as the cause: `Unexpected input: '{'`, which causes many users to look for errors *before* this point, when in reality the error is almost always after it.
Unfortunately, we can't use the DSL to improve this error because it happens during parsing, before our custom AST transforms. The most we can do is to intercept the error and try to provide a hint to the user. The long-term solution is to create a DSL that doesn't require as many syntax transformations.
Try any of the pipeline examples in the …

Improve "Unexpected input: '{'" error message

---

docs/config.md
modules/nf-commons/src/main/nextflow/Const.groovy
plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy
plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchTaskHandler.groovy
plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzBatchOpts.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzBatchServiceTest.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/config/AzureConfigTest.groovy

Deleting Azure Tasks was checking the configuration object `deleteJobsOnCompletion` which was incorrect since a task belongs to a job. This adds the equivalent configuration for tasks which is checked before deleting the tasks.

Add deleteTasksOnCompletion to Azure Batch configuration

---

plugins/nf-tower/src/main/io/seqera/tower/plugin/CacheCommand.groovy
plugins/nf-tower/src/main/io/seqera/tower/plugin/CacheManager.groovy
plugins/nf-tower/src/test/io/seqera/tower/plugin/CacheManagerTest.groovy

This PR changes the nf-tower `cache` command to not try to save/restore the Nextflow cache if `NXF_CLOUDCACHE_PATH` is set.

Disable cache backup/restore if cloudcache is used

---

modules/nextflow/src/main/groovy/nextflow/script/BaseScript.groovy
modules/nextflow/src/main/groovy/nextflow/script/ScriptMeta.groovy
modules/nextflow/src/test/groovy/nextflow/script/BaseScriptTest.groovy
modules/nextflow/src/test/groovy/nextflow/script/ProcessDefTest.groovy
modules/nextflow/src/test/groovy/nextflow/script/ScriptMetaTest.groovy

Close #4127 
The entryFlow is updated when workflows are defined in the main script, but not when they are imported from a module. This PR checks the imported workflows for a matching entry flow if it wasn't found in the main script.

Allow workflow entry from module import

---

modules/nextflow/src/main/groovy/nextflow/script/params/BaseParam.groovy
modules/nextflow/src/test/groovy/nextflow/script/params/ParamsInTest.groovy

Close #3185 
This PR fixes a particularly nasty error message that occurs with missing commas in process inputs/outputs.
Consider the following example:
```groovy
process foo {
debug true
input:
tuple val(x) val(y) // missing comma
script:
"""
echo "foo ${task.index} ${task.workDir}"
"""
}
workflow {
foo(['x', 'y'])
}
```
Currently, the script compiles despite the missing comma but then Nextflow reports that the process has been used twice:
```console
nextflow run gh-3185/bad-error-message-4.nf
N E X T F L O W  ~  version 23.06.0-edge
Launching `gh-3185/bad-error-message-4.nf` [loving_keller] DSL2 - revision: 63eb6918e1
Process 'foo' has been already used -- If you need to reuse the same component, include it with a different name or include it in a different workflow context
-- Check …
```

Fix incorrect error message on missing comma

---

docs/fusion.md
docs/wave.md

A few minor fixes to Wave and Fusion config docs

Update Wave and Fusion docs

---

docs/config.md

Close #4148 
When I documented strict mode, I said that certain options are true "by default", when in fact they are true regardless of any user setting.

Fix strict mode docs

---

docs/cli.md
modules/nextflow/src/main/groovy/nextflow/cli/CmdConfig.groovy
modules/nextflow/src/test/groovy/nextflow/cli/CmdConfigTest.groovy
modules/nf-commons/src/main/nextflow/Const.groovy

Close #4138 
The config CLI `-property` optional has been implemented here. I have also updated the docs accordingly. I tested the feature with the following config and test script:
```groovy
some {
nullval = null
nested = [
key: "value"
]
}
profiles {
myprofile {
some.nested.key = "alt-value"
}
}
```
```bash
echo "Running tests..."
echo "Should print 'value'"
./launch.sh -C test.config config -property some.nested.key
echo ""
echo "Should print 'alt-value'"
./launch.sh -C test.config config -property some.nested.key -profile myprofile
echo ""
echo "Should print 'null'"
./launch.sh -C test.config config -property some.nullval -profile myprofile
echo ""
echo "Should return a non-zero exit code"
./launch.sh -C test.config config -property does.not.exist
echo "Exit Code: $?"
```
```
Running …
```

Add `-value` option to `config` command

---

docs/script.md

Close #3188 
Consider the following Groovy code:
```groovy
println """
cat ${'foo.txt'} \ 
| wc -l
"""
```
Because the backslash is followed by a space, apparently it is interpreted by Groovy as an escaped space rather than a backslash. For regular strings, this causes an "Unexpected token" error, but for GStrings, it simply prints a lexer warning and continues, but now the string is incorrect.
I couldn't find a way to intercept this error, since apparently it is just printed as a warning. So instead I added a blurb to a section in the docs about backslash continuations.

Document error about trailing backslash with space

---

docs/aws.md

I recently went through the process of creating a custom AMI in AWS.
This PR reflects the changes in the AWS interface, defaults and AMI naming.

Update AWS instructions for creating a custom AMI [ci skip]

---

modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy
modules/nextflow/src/main/groovy/nextflow/script/BaseScript.groovy

Close #3418 
When a method invoked via reflection throws an exception, the exception is wrapped in an `InvocationTargetException`. `BaseScript` already has a catch block to unwrap this exception, but for some reason there are some cases where the exception is wrapped twice, such as the linked issue.
I tried burying the user exception in more function calls and workflow calls, but it was only ever wrapped once or twice. So it does not seem to depend on the call depth, but I can't explain why it is wrapped sometimes once and sometimes twice. So I just check both cases.

FIx nested InvocationTargetException

---

docs/executor.md
docs/process.md
plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy
plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzVmPoolSpec.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzBatchServiceTest.groovy

Close #3248 
Based on discussions in the issue and with Adam, it seems cost analysis in Azure is tied to pools, and job metadata is not propagated to VMs. As a result, this PR applies `resourceLabels` to the pool when it is created, and the docs make clear that resource labels in Azure should be defined once for all processes, or else they will be non-deterministic.
Happy to be proven wrong if anyone knows better. But this feature is still useful for pipeline-level labels, like pipeline name, user, project, etc.
@adamrtalbot can you test it?

Support resource labels for Azure Batch

---

docs/config.md
docs/container.md
modules/nextflow/src/main/groovy/nextflow/container/SingularityBuilder.groovy
modules/nextflow/src/test/groovy/nextflow/cli/CmdInfoTest.groovy
modules/nextflow/src/test/groovy/nextflow/container/ApptainerBuilderTest.groovy
modules/nextflow/src/test/groovy/nextflow/container/SingularityBuilderTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/BashWrapperBuilderTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/fusion/FusionHelperTest.groovy

This PR align the execution of Singularity (and Apptainer) containers to make experience more consistent with Docker containers. 
More in detail: 
- Use `singularity run` command in place of `singularity exec`. This allows the execution of the `%runscript`, when defined in the Singularityfile, which provides a behaviour similar to Docker entry-point. To rollback to the previous `exec` command the variable `NXF_SINGULARITY_RUN_COMMAND=exec` (or `NXF_APPTAINER_RUN_COMMAND=exec`).  
- Automatically mount the host path in the running container. This, along with the recent change of disabling the mount of the home dir by default (a0ee4657), makes the file system isolation of Singularity containers more singular to Docker. To rollback to the previous behavior use `singularity.autoMounts=false` …

Align Singularity experience with Docker

---

modules/nextflow/src/main/groovy/nextflow/conda/CondaCache.groovy

As documented in https://github.com/nextflow-io/nextflow/issues/4233 conda can currently not be executed in parallel in a safe way. This PR proposes a temporary fix to this issue, so that nextflow applications continue to work. This PR should be reverted when the bug is eventually fixed in conda. The upstream bug is tracked at https://github.com/conda/conda/issues/13037

Temporary fix for upstream conda bug: parallel execution of conda corrupts data and packages

---

docs/azure.md

Fixing and updating File shares documentation.
I've asked clarifications to the Azure SDK team (see https://github.com/Azure/azure-sdk-for-java/issues/36546). They confirmed that authentication with AAD for Azure Files is not supported and not in their immediate roadmap.

Update AZ File share doc. [ci skip]

---

docs/script.md

Document use of local variables in closures

---

docs/config.md
modules/nextflow/src/main/groovy/nextflow/processor/ParallelPollingMonitor.groovy
modules/nextflow/src/main/groovy/nextflow/util/ConfigHelper.groovy
modules/nextflow/src/test/groovy/nextflow/util/ConfigHelperTest.groovy

Setting `executor.queueSize` to 0 is equivalent to having no limit. However, due to an incorrect null check, the queue size is ignored and falls back to the default value if it is set to 0 in the config. This PR fixes that, as well as a null reference error that happens when the queue size is 0.

Fix `executor.queueSize = 0` ignored

---

docs/process.md

Document API differences of process path inputs

---

docs/config.md

The `conda.enabled` option is missing from the conda scope documentation under configs.

Add conda.enabled to conda config scope docs

---

docs/tracing.md
modules/nextflow/src/main/groovy/nextflow/trace/TraceRecord.groovy

Based on a customer ticket where they asked about how these fields are defined, which is from the /proc filesystem.

Document source of `vol_ctxt` and `inv_ctxt` trace metrics

---

plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchScriptLauncher.groovy
plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchScriptLauncherTest.groovy

Fixes #4331
`-o allow_other` as a gcsfuse option creates a potential shell injection vulnerability.
As a result, current `process.executor = google-batch` submissions are being rejected with the error:
```
ERROR ~ Error executing process > 'splitLetters'
Caused by:
INVALID_ARGUMENT: volume.mount_options field is invalid. mount_option -o rw,allow_other has potential shell injection, please check again.
-- Check '.nextflow.log' file for details
```
Removing `allow_other` corrects this.

Removed allow_other vulnerability preventing google-batch submissions

---

modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy
modules/nextflow/src/test/groovy/nextflow/processor/TaskProcessorTest.groovy

This PR prevents the cache invalidation then a process directive is modified, as introduced by PR https://github.com/nextflow-io/nextflow/issues/2382, with the exception of the `ext.*` extension directives. 
More context here https://github.com/nextflow-io/nextflow/issues/4326#issuecomment-1731183716. 
Solves #4326.

Prevent cache invalidation for task directives

---

.github/workflows/build.yml
docs/getstarted.md
launch.sh
nextflow

This PR adds support for Java 21. Moreover, it enables virtual threads by default when using Java 21. It's still possible to rollback to platform threads by setting the variable `NXF_ENABLE_VIRTUAL_THREADS=false`.

Add support for Java 21

---

docs/process.md

Document when process directives are evaluated

---

docs/cache-and-resume.md
docs/cli.md
docs/getstarted.md
docs/index.md
docs/operator.md
docs/process.md
docs/script.md
docs/sharing.md

Close #4344 
- New docs page on how the cache works, different cache stores, and troubleshooting advice from blog posts
- New hyperlinks from cache-related warnings throughout the docs to the new page to provide some helpful context

Add docs page on caching and resuming

---

.codespellrc
.github/workflows/codespell.yml
changelog.txt
docs/conf.py
docs/sharing.md
modules/nextflow/src/main/groovy/nextflow/ast/ASTHelpers.groovy
modules/nextflow/src/main/groovy/nextflow/ast/NextflowDSLImpl.groovy
modules/nextflow/src/main/groovy/nextflow/cli/CmdDrop.groovy
modules/nextflow/src/main/groovy/nextflow/config/ConfigBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskRun.groovy
modules/nextflow/src/main/groovy/nextflow/script/IterableDef.groovy
modules/nextflow/src/main/groovy/nextflow/script/WorkflowDef.groovy
modules/nextflow/src/main/groovy/nextflow/script/WorkflowNotifier.groovy
modules/nextflow/src/main/groovy/nextflow/trace/TraceRecord.groovy
modules/nextflow/src/main/groovy/nextflow/util/ConfigHelper.groovy
modules/nextflow/src/main/resources/nextflow/trace/assets/d3-timeline.js
modules/nextflow/src/test/groovy/nextflow/cli/CmdSecretTest.groovy
modules/nextflow/src/testFixtures/groovy/test/BaseSpec.groovy
modules/nf-commons/src/main/nextflow/file/FileHelper.groovy
modules/nf-commons/src/main/nextflow/file/TagAwareFile.groovy
plugins/nf-amazon/src/main/nextflow/cloud/aws/nio/S3FileSystemProvider.java
plugins/nf-amazon/src/main/nextflow/cloud/aws/nio/S3Iterator.java
tests/Dockerfile
tests/bin/AMPA.pl

workflow would only detect when a new typo is introduced, it will not automagically inject its fix somehow.
more info on codespell: https://github.com/codespell-project/codespell

add codespell: config, workflow and have typos fixed

---

modules/nextflow/src/main/groovy/nextflow/executor/GridTaskHandler.groovy
modules/nextflow/src/test/groovy/nextflow/executor/GridExecutorTest.groovy

This change modifies the exitStatus value from MAX_INTEGER to `-1` when the exitcode file exists but it's empty. 
This prevents interrupting the pipeline execution and allows instead to handle this condition as job error

Return -1 when exitcode file is empty

---

docs/cli.md
modules/nextflow/src/main/groovy/nextflow/Session.groovy
modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy
modules/nextflow/src/main/groovy/nextflow/cli/Launcher.groovy
modules/nextflow/src/main/groovy/nextflow/config/ConfigBuilder.groovy
modules/nextflow/src/test/groovy/nextflow/cli/LauncherTest.groovy
modules/nextflow/src/test/groovy/nextflow/config/ConfigBuilderTest.groovy
modules/nf-commons/src/main/nextflow/plugin/PluginsFacade.groovy
modules/nf-commons/src/test/nextflow/plugin/PluginsFacadeTest.groovy
plugins/nf-amazon/src/test/nextflow/S3SessionTest.groovy
plugins/nf-cloudcache/src/main/nextflow/cache/CloudCacheFactory.groovy
plugins/nf-cloudcache/src/main/nextflow/cache/CloudCacheStore.groovy
plugins/nf-tower/src/main/io/seqera/tower/plugin/CacheCommand.groovy
plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerFactory.groovy

This adds the support for enabling cloudcache plugin via `run` CLI option `-cloudcache [path]`

Add support for enabling cloudcache from CLI

---

docs/fusion.md
modules/nextflow/src/main/groovy/nextflow/fusion/FusionAwareTask.groovy
modules/nextflow/src/main/groovy/nextflow/fusion/FusionConfig.groovy
modules/nextflow/src/main/groovy/nextflow/fusion/FusionEnvProvider.groovy
modules/nextflow/src/main/groovy/nextflow/k8s/K8sTaskHandler.groovy
modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy
modules/nextflow/src/test/groovy/nextflow/fusion/FusionConfigTest.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/K8sTaskHandlerTest.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/model/PodSpecBuilderTest.groovy

This PR the config option 
```
fusion.privileged = true|false // defualt true
```
Enable or disable the privileged execution required by Fusion. The implementation depends on the target executor

Support for Fusion unprivileged execution

---

docs/config.md

This undocumented retryMode is handy. This is a retryMode that will catch any exception type. The AWS modes only catch specific types. I needed something to catch "No space left on device." This 'built-in' mode does that, nothing else does.

Document aws.batch.retryMode = 'built-in'.

---

README.md

I updated the colors for the docs page but forgot about the README.md of the GitHub repository. This PR fixes this.

Update README.md with new branding color for Nextflow

---

docs/getstarted.md

OS X has been officially known as macOS since 2016.
I think it would be a good idea to use the official naming convention to avoid user confusion. 
Might need to consider updating the [Nextflow home page](https://www.nextflow.io/) as well

Reflect current macOS naming convention

---

docs/plugins.md

As spotted [here](https://community.seqera.io/t/include-nf-validation-in-the-all-nextflow-binary/219/3?u=ewels), these docs are incorrect as the `-all` binary doesn't allow the use of custom plugins.
x-ref https://github.com/nextflow-io/nextflow/issues/4330

Docs: Plugins offline, don't recommend -all

---

nextflow

Close #4360 
This PR applies the changes suggested in the original issue, basically ensures that any variables based on `NXF_HOME` are correctly quoted to prevent argument splitting.
Note the caveat from the original issue:
> It is worth noting that although the %q conversion operator appears to be well supported, it is not portable according to POSIX. In practice, I have not found this to be a problem, but I don't like it. Hopefully someone with more sh-fu than me has a better idea.
I do not have more bash-fu, so I did not try to find a better solution...
By the way, a helpful thing I found was to install the shellcheck extension in VS Code (should be an equivalent in IntelliJ) which provides lots of hints for these problems.

Fix errors when NXF_HOME contains spaces

---

docs/config.md

Corrects the documentation for `google.batch.network` and `google.batch.subnetwork` to match the Google Cloud documentation: https://cloud.google.com/java/docs/reference/google-cloud-batch/latest/com.google.cloud.batch.v1.AllocationPolicy.NetworkInterface.Builder#com_google_cloud_batch_v1_AllocationPolicy_NetworkInterface_Builder_setNetwork_java_lang_String_
The current text was copied from the corresponding Life Sciences settings but Batch and Life Sciences have different semantics for these two settings

Fix google batch network/subnetwork docs

---

plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsConfig.groovy
plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsS3Config.groovy
plugins/nf-amazon/src/main/nextflow/cloud/aws/fusion/AwsFusionEnv.groovy
plugins/nf-amazon/src/main/nextflow/cloud/aws/nio/S3FileSystemProvider.java
plugins/nf-amazon/src/test/nextflow/cloud/aws/config/AwsS3ConfigTest.groovy
plugins/nf-amazon/src/test/nextflow/cloud/aws/nio/S3FileSystemProviderTest.groovy

This PR adds support for passing the AWS region to Fusion when using a custom endpoint.

Add support for FUSION_AWS_REGION 

---

docs/process.md
modules/nextflow/src/main/groovy/nextflow/k8s/K8sConfig.groovy
modules/nextflow/src/main/groovy/nextflow/k8s/model/PodOptions.groovy
modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/model/PodOptionsTest.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/model/PodSpecBuilderTest.groovy

For my master thesis I needed a way to specify which scheduler is used to schedule nextflow tasks. Maybe it could be useful for others as well. This adds a `schedulerName` field to `PodOptions` and a shortcut to it via `K8sConfig`.
K8s docs reference: https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/#specify-schedulers-for-pods
Given I already had the code, I opted to create a PR directly instead of creating an issue first. If this is not needed or already worked on, feel free to close :)

Add support for K8s pod schedulerName

---

docs/module.md

Has a brief description of sharing modules, and adds a link to the nf-core page about modules.

Add section about sharing modules

---

docs/plugins.md
docs/process.md

This PR expands the documentation on the `ext` directive and how to access process directives in a custom executor. Based on discussions with MemVerge and YellowDog and their Nextflow plugins.

Add section on process directives to plugin docs

---

docs/process.md
docs/workflow.md

Update process.md to document the `emit` option in process outputs.

Document `emit` option in process outputs

---

plugins/nf-google/src/main/nextflow/cloud/google/batch/logging/BatchLogging.groovy

Batch used to use generic_task as monitored resource type. However, the type is not only for Batch. Google Batch is planning to switch it's own monitored resource type which is "batch.googleapis.com/Job". To have a smooth changing, add a OR filter to have the new monitored resource type included. After we finished transition, the generic_task filter could be removed.

Update logging filter for Google Batch provider

---

docs/snippets/test.sh

This PR adds some logic to the doc tests so that a failing test actually causes the test suite to fail, without aborting the remaining tests.

Fix doc tests to fail on test failure

---

docs/fusion.md
modules/nextflow/src/main/groovy/nextflow/fusion/FusionConfig.groovy
modules/nextflow/src/main/groovy/nextflow/fusion/FusionEnvProvider.groovy
modules/nextflow/src/test/groovy/nextflow/fusion/FusionConfigTest.groovy

Add `cacheSize` Fusion configuration option that allows to limit the size of the local cache that creates Fusion.

Add "fusion.cacheSize" config option

---

plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchMachineTypeSelector.groovy

Close #4520 
Maybe we still want to add an explicit option to disable the price query though

Bypass google batch price query if task cpus and memory are defined

---

Makefile

@pditommaso  this should fix weird behaviours observed when testing Nextflow builds with source modifications.
A while ago the fix you handed me was:
```
find . -name MANIFEST.MF | grep build/tmp | xargs rm
```
Upon inspection, the command above reduces to the `Makefile` change in this PR.

Makefile clean to also remove buildSrc/build

---

docs/config.md
plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy
plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzPoolOpts.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzBatchServiceTest.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/config/AzPoolOptsTest.groovy

This PR adds initial support for Azure Low-priority VMs by adding a new `lowPriority` boolean option to the azure pool settings

Add support for Azure low-priority VMs

---

docs/config.md
plugins/nf-google/src/main/nextflow/cloud/google/GoogleOpts.groovy
plugins/nf-google/src/main/nextflow/cloud/google/config/GoogleRetryOpts.groovy
plugins/nf-google/src/main/nextflow/cloud/google/config/GoogleStorageOpts.groovy
plugins/nf-google/src/main/nextflow/cloud/google/util/GsPathFactory.groovy
plugins/nf-google/src/test/nextflow/cloud/google/config/GoogleRetryOptsTest.groovy
plugins/nf-google/src/test/nextflow/cloud/google/util/GsPathFactoryTest.groovy
plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveClient.groovy
plugins/nf-wave/src/test/io/seqera/wave/plugin/WaveClientTest.groovy

This adds support for retry settings for Google Storage operations. By default it uses 10 retries up to 90 seconds. 
The policy can be customised by using those settings 
```
google.storage.retryPolicy.maxAttempts = <number>
google.storage.retryPolicy.maxDelay = '<duration>'
google.storage.retryPolicy.multiplier = <decimal>
```

Add Retry policy to Google Storage

---

plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy
plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchTaskHandlerTest.groovy

This change will add the missing labels to Batch Job request.
Without some of the labels, some Batch side optimization is not recognized.

Fix the missing labels field in Job request for Google Batch

---

modules/nf-commons/src/main/nextflow/util/StringUtils.groovy
modules/nf-commons/src/test/nextflow/util/StringUtilsTest.groovy

Include option to strip secrets from single-quoted strings.
Closes https://github.com/nextflow-io/nextflow/issues/4562

Harden regular expression to used to strip secrets in logs

---

plugins/nf-amazon/src/main/nextflow/cloud/aws/fusion/AwsFusionEnv.groovy
plugins/nf-amazon/src/test/nextflow/cloud/aws/fusion/AwsFusionEnvTest.groovy

In some scenarios the `AWS_SESSION_TOKEN` variable is also needed by Fusion to authenticate AWS. 
This PR exports this variable if exists and `fusion.exportStorageCredentials` is set to `true`.

Add AWS_SESSION_TOKEN when exporting credentials for Fusion

---

Makefile
build.gradle
settings.gradle

This PR includes two improvements:
- Remove `buildInfo` as a dependency of `compile` and add it as a dependency of `make assemble`, since the build info is only needed when building a release
- Add a make rule `make compileCore` which compiles only Nextflow without the plugins. Useful when testing core features that don't depend on the plugins
The first optimization alone brings my cached build time from ~45s to ~3s

Build optimizations

---

modules/nextflow/src/main/groovy/nextflow/processor/PublishDir.groovy
tests/checks/fusion-symlink.nf/.checks

Follow up to #4348 , based on multiple customer reports that Fusion symlinks are still not being published correctly.
It looks like some last minute changes on the original PR introduced a bug, but the integration test was not robust enough to catch it.
While I'm confident that this PR will fix the bug, I haven't been able to make the integration test fail. Whenever I run `fusion-symlink.nf` locally, the `data.txt` output in each task directory is a copy instead of a symlink, so it is not actually testing the symlink resolution.

Fix bug with Fusion symlink resolution

---

modules/nextflow/src/main/groovy/nextflow/container/DockerBuilder.groovy
modules/nextflow/src/test/groovy/nextflow/container/DockerBuilderTest.groovy

This PR removes the undocumented setting `docker.userEmulation`.

Remove undocumented userEmulation mode

---

tests/checks/fusion-symlink.nf/.checks

This PR should fix the fusion symlink test which can fail sometimes if multiple instances are running at the same time and clobber each other's results.
A more robust solution would be if every CI test instance used a unique S3 work directory.

Fix fusion symlink test

---

plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchExecutor.groovy
plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy
plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchExecutorTest.groovy
plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchTaskHandlerTest.groovy

This PR adds the ability to disable the use of Cloudinfo service by setting the env variable
```
export NXF_CLOUDINFO_ENABLED=false
```

Add ability to disable Cloudinfo service

---

modules/nextflow/src/main/groovy/nextflow/container/ContainerConfig.groovy

as per PR title, just a small typo in an output message.

fixed output typo, OCI, in ContainerConfig.groovy

---

plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy

This PR adds `IOException` and `TimeoutException` to the conditions to retry an Azure Batch API failure.

Fix azure retry policy

---

changelog.txt
modules/nextflow/src/test/groovy/nextflow/secret/LocalSecretsProviderTest.groovy

This PR fixes a unit test failure that happens if the machine you run on has tight default file permissions (e.g. as obtained via `umask`, for instance `umask 067`).   
The error reads:
```
LocalSecretsProviderTest > should fail with invalid permissions FAILED
org.spockframework.runtime.WrongExceptionThrownError at LocalSecretsProviderTest.groovy:114
```
To succeed, this tests is expected to raise an exception as a result of the permissions of a created file being different from `rw-------`.  If this configuration is the default in the machine (more secure),  the test will fail. 
The PR explicitly sets the file permissions for the test to something different, i.e. `rw-r-----` , instead of relying on the machine default.

LocalSecretsProvider: invalid permissions tests made more robust

---

docs/conda.md

This Documentation PR adds an example to the Conda doc page, showing how to install `pip` packages through Conda through an  environment YAML file.

docs for conda: added yaml example for pip packages

---

modules/nextflow/src/main/groovy/nextflow/fusion/FusionScriptLauncher.groovy

I spoke to Jordi and found that we originally defaulted scratch to true with Fusion at a time when Fusion was only staging input data. But now that Fusion handles both inputs and outputs staging, it makes no sense to ever use scratch=true with Fusion because it eliminates the performance benefit of Fusion. I think we can safely set the default to false now.

Set scratch default to false when using Fusion

---

plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerJsonGenerator.groovy

Addresses a customer suggestion that the "max size exceeded" warning should not print the entire offending value since it might be very long

Truncate max size exceeded error message

---

docs/config.md
docs/kubernetes.md
modules/nextflow/src/main/groovy/nextflow/k8s/K8sConfig.groovy
modules/nextflow/src/main/groovy/nextflow/k8s/K8sTaskHandler.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/K8sConfigTest.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/K8sTaskHandlerTest.groovy

When Nextflow uses Fusion over K8s with unprivileged mode requires the use of the [k8s-fuse-plugin](https://github.com/nextflow-io/k8s-fuse-plugin) to mount the FUSE device. 
Other plugins are available which requires the use of a custom fuse device name to be specified in the K8s spec. 
This PR adds the ability to specify a custom fuse device name via the nextflow config file. For example: 
```
k8s {
fuseDevicePlugin = ['smarter-devices/fuse':1] 
}
```
Solved #4611

Add support for custom fuse device plugin

---

docs/config.md

ERROR ~ S3 endpoint must begin with http:// or https:// prefix

aws.client.endpoint requires http(s)

---

modules/nf-commons/src/main/nextflow/extension/Bolts.groovy
modules/nf-commons/src/test/nextflow/extension/BoltsTest.groovy
plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveClient.groovy
plugins/nf-wave/src/test/io/seqera/wave/plugin/WaveClientTest.groovy

This PR adds a small fix in WaveClient, to better handle `s5cmdConfigUrl`.
This is spun out of #4701, and comes from original Paolo's PR #4554.
internally renames `dockerArch` to `dockerPlat`, for better jargon consistency in the codebase and docs. This variable specifies the platform to build containers via Wave, ie X86 or ARM.

nf-wave WaveClient: fix for s5cmdConfigUrl

---

modules/nextflow/src/main/groovy/nextflow/container/DockerBuilder.groovy

Minor tweak in the wording of the warning message about `userEmulation`

Slight change in wording for error message about userEmulation

---

modules/nextflow/src/main/groovy/nextflow/processor/PublishDir.groovy

Close #4639 
If the creation of the base publish directory fails, the error message is misleading and vague. This PR makes this error handling consistent with other publish errors. If the publish directory cannot be created, it logs a specific warning and fails the pipeline only if `failOnError` is true (or strict mode is enabled).
Test case:
```groovy
process foo {
publishDir 's3://<my-bucket>/results'
output:
path 'result.txt'
script:
"""
echo foo > result.txt
"""
}
workflow {
foo()
}
```
Set the publishDir to any S3 bucket for which you don't have access.

Improve handling of publish error

---

plugins/nf-ga4gh/src/main/nextflow/ga4gh/tes/executor/TesFileCopyStrategy.groovy
plugins/nf-ga4gh/src/main/nextflow/ga4gh/tes/executor/TesTaskHandler.groovy

This PR includes updates to the GA4GH TES plugin to allow successfully communication between it and a local TES executor, specifically by passing the contents of the working directory's `bin` directory as TES inputs. 
Nextflow's [default behavior](https://www.nextflow.io/docs/latest/faq.html#how-do-i-invoke-custom-scripts-and-tools) is to add the contents of the `bin` directory to a process and automatically update the $PATH variable to allow workflows to run with dependencies:
> Nextflow will automatically add the directory bin into the PATH environmental variable. So therefore any executable in the bin folder of a Nextflow pipeline can be called without the need to reference the full path.
- https://github.com/nextflow-io/nextflow/pull/4195
- …

Update support for local TES executor with GA4GH TES Plugin

---

modules/nextflow/src/main/groovy/nextflow/processor/PublishDir.groovy

Close https://github.com/nextflow-io/nf-prov/issues/22
When publishing a symlink for a cached task, the publish event is normally skipped because the source and target paths are the same "real path". This PR adjusts the logic to ensure that the publish event is still emitted.
Symlink is the default publish mode, and nf-prov depends on publish events to generate the provenance manifest, so this is causing some confusing behavior for new users of nf-prov.
This fix was tested with Rob's minimal example in the linked issue and works.

Always emit publish event for symlinks on resume

---

modules/nextflow/src/main/groovy/nextflow/executor/LsfExecutor.groovy
modules/nextflow/src/test/groovy/nextflow/executor/LsfExecutorTest.groovy

When there is a task name with square brackets, it fails on my LSF cluster:
```
-[nf-core/differentialabundance] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:CUSTOM_MATRIXFILTER ([id:study])'
Caused by:
Failed to submit process to grid scheduler for execution
Command executed [/hpc/users/goateomics/.nextflow/assets/nf-core/differentialabundance/./workflows/../modules/nf-core/custom/matrixfilter/templates/matrixfilter.R]:
cat << 'LAUNCH_COMMAND_EOF' | bsub
#!/bin/bash
#BSUB -o /sc/arion/projects/load/users/goateomics/garretti_francesca/20240305.THP1_siRNA_bulkRNAseqDGE/work/8e/b989526c492d2818e8d2991b54110b/.command.log
#BSUB -q express
#BSUB -W 04:00
#BSUB -M 6144
#BSUB -R "select[mem>=6144] rusage[mem=6144]"
#BSUB …
```

Remove square brackets from job name in LSF executor

---

plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerClient.groovy
plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerReports.groovy

Close #3460 
This PR saves the built-in reports as Tower reports by inspecting the Nextflow config. If a report is enabled, it will be eagerly sent to the reports file on workflow completion.
Note that if a report fails to create for some reason, it will be displayed in the platform run page but will not load since the file doesn't exist. In this case, the failure will have been logged as a warning to the console output.

Save built-in reports as Tower reports

---

docs/container.md

This PR fixes an inconsistency in the containers documentation around the default execution command for Singularity/Apptainer. 
Closes #4801

containers docs: fixed note on singularity default command

---

nextflow

This PR aims to address #4653, and as such applies a few small edits to the main `nextflow` script:
* if no installation found at all (`$JAVA_CMD --version failing), print additional advice (in red):
```
NOTE: please refer to the Nextflow Get Started page at https://www.nextflow.io/docs/latest/getstarted.html.
```
* if SDKMAN sourceable script found but not sourced, have Nextflow source it in case it has Java installed; if Java found this way, also print a notice (in yellow):
```
NOTE: Nextflow has found a working SDKMAN Java installation and is going to use it. For a more robust setup, add the following lines at the end of your Bash .profile or .bash_profile:
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
```
If …

Nextflow launch script: improving search for JAVA_CMD

---

docs/snippets/process-out-env.nf
plugins/nf-google/src/test/nextflow/cloud/google/batch/client/BatchConfigTest.groovy

Fix failing CI tests

---

docs/config.md
plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy
plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzBatchOpts.groovy
plugins/nf-azure/src/main/nextflow/cloud/azure/config/CopyToolInstallMode.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/config/AzBatchOptsTest.groovy

This PR improves the control over the installation of the `azcopy` tool used by Azure batch execution by adding the ability to disable its installation using the `none` option or when Fusion is enabled. 
Moveover it prevents the installation in the compute node when the `task` mode is specified

Improve control on azcopy install

---

modules/nextflow/src/main/groovy/nextflow/trace/AnsiLogObserver.groovy

Truncation of the fully qualified process name was being too aggressive when the subworkflows included the process name as a substring.
Changed this to remove the process name by number of characters instead of by subtracting the string, now works as expected.

Fix coloured ANSI log bug

---

docs/config.md
docs/google.md

Updated docs on Google Cloud setup, in regards to credentials (e.g., setting service account roles).
This PR is specifically dealing with https://github.com/nextflow-io/nextflow/issues/4603 and [this slack thread](https://nextflow.slack.com/archives/C02TLU7U57F/p1712683379535059?thread_ts=1712517797.743939&cid=C02TLU7U57F).

Updated docs on Google Cloud setup and credentials

---

modules/nextflow/src/main/groovy/nextflow/trace/AnsiLogObserver.groovy

When using `process.debug = true`, even if any process generates `stdout`, a new line is printed to `stdout` for each executed task.
I was expecting that if the process does not generate any `stdout`, then Nextflow does not print anything to `stdout`.
**NOTE:** If ANSI is disabled, this will not happen.

Do not print a new line when stdout is empty

---

modules/nextflow/src/testFixtures/groovy/test/TestHelper.groovy
plugins/nf-wave/build.gradle
plugins/nf-wave/src/main/io/seqera/wave/plugin/SubmitContainerTokenRequest.groovy
plugins/nf-wave/src/main/io/seqera/wave/plugin/SubmitContainerTokenResponse.groovy
plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveAssets.groovy
plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveClient.groovy
plugins/nf-wave/src/test/io/seqera/wave/plugin/WaveClientTest.groovy
plugins/nf-wave/src/test/io/seqera/wave/plugin/config/WaveConfigTest.groovy

This PR implements the support for Wave API v1alpha2

Wave cli v1alpha2

---

plugins/nf-azure/src/test/nextflow/cloud/azure/config/AzPoolOptsTest.groovy

Some commented out lines were leftover from https://github.com/nextflow-io/nextflow/commit/27d01e3a2de65bb02d32a0240180c85b7507d03f in Azure Batch pool setup tests. This PR uncomments them so they are explicit.
Signed-off-by: Adam Talbot <12817534+adamrtalbot@users.noreply.github.com>

fix: remove commented out test lines in Azure Batch Pool opts tests.

---

docs/_templates/layout.html

We switched from using /master/ to using /latest/ - update the quick switch dropdown.
Ties together with https://github.com/nextflow-io/website/pull/198 - forgot that these links are also hardcoded into the Nextflow repo itself 🙈

Docs: Version switcher dropdown link fix

---

plugins/nf-amazon/src/main/nextflow/cloud/aws/nio/S3FileSystemProvider.java

Before this fix, error messages that referred to S3 paths would print potentially-confusing messages that omit the `s3:/` prefix:
> `reason: the path: /my-bucket/path/to/file does not exist `
With this fix, the message prints the full URI:
> `reason: the path: s3://my-bucket/path/to/file does not exist `

Use full (String) form of S3 uris in error message

---

modules/nextflow/src/main/groovy/nextflow/processor/ParallelPollingMonitor.groovy
modules/nextflow/src/test/groovy/nextflow/processor/ParallelPollingMonitorTest.groovy

In #4228 I made some changes to ensure that `executor.queueSize = 0` corresponds to no queue limit, and fixed a null reference error in the parallel polling monitor.
I made a small mistake which causes `executor.queueSize = 0` to mean "limit jobs to zero" instead of "no limit". Setting this in AWS Batch will cause no jobs to run. This PR corrects the mistake.

Fix semaphore in parallel polling monitor

---

docs/azure.md

Adds details about the Azure Batch autopool feature including how to use variable sized pools and nodes. Should make it more obvious to end users that Nextflow supports splitting work across variable sized machines.
Closes #4304 (kinda, it documents a feature that already existed).

[ci skip] docs: azure batch autopool feature more comprehensive documentation

---

docs/config.md

Spun off from #4510 , see also #4416 
- reorder the resolution priority to be lowest to highest, a bit easier to read and understand
- clarify some details about process selectors as they relate to included modules

Improve config resolution docs

---

modules/nextflow/src/main/groovy/nextflow/k8s/K8sTaskHandler.groovy

This PR guarantees that a pod name is unique so that when resuming there is going to be no conflict

Guarantees K8s pod name is unique on resume

---

modules/nextflow/src/main/groovy/nextflow/ast/NextflowDSLImpl.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy
modules/nextflow/src/test/groovy/nextflow/script/WorkflowDefTest.groovy

Fixes https://github.com/nextflow-io/nextflow/issues/4585
Using this toy:
```nextflow
workflow {
TASK(Channel.of('a')).view()
}
process TASK {
input:
val letter
script:
assert letter.isUpperCase()
def puzzle = null
if ( puzzle ) {
println "Puzzled"
} else {
println "LGTM"
}
"""
echo $letter
"""
output:
stdout
}
```
I now get a properly formatted error:
```
N E X T F L O W  ~  version 23.12.0-edge
Launching `../main.test.nf` [spontaneous_galileo] DSL2 - revision: 81c47780ef
[-        ] process > TASK -
ERROR ~ Error executing process > 'TASK (1)'
Caused by:
assert letter.isUpperCase()
|      |
'a'    false -- Check script '/workspace/main.test.nf' at line: 10
Source block:
assert letter.isUpperCase()
def puzzle = null
if ( puzzle ) {
println "Puzzled"
} else {
println "LGTM"
}
"""
echo …
```

Fix error text alignment

---

modules/nextflow/src/main/groovy/nextflow/container/CharliecloudCache.groovy
modules/nextflow/src/main/groovy/nextflow/container/SingularityCache.groovy

Closes #4823  by adding an explicit suggestion in the error message, to increase the `pullTimeout` config for the relevant container runtime.

Improve error message for image pull time-out for Singularity/Apptainer/Charliecloud

---

modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/executor/GridTaskHandler.groovy
modules/nextflow/src/main/groovy/nextflow/executor/LsfExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/PbsExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/SgeExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/SlurmExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/TaskArrayExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskArrayCollector.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskBean.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskHandler.groovy
modules/nextflow/src/test/groovy/nextflow/executor/BashWrapperBuilderTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/GridTaskHandlerTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/LsfExecutorTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/PbsExecutorTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/PbsProExecutorTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/SgeExecutorTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/SlurmExecutorTest.groovy
modules/nextflow/src/test/groovy/nextflow/processor/TaskArrayCollectorTest.groovy
plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchExecutor.groovy
plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchTaskHandler.groovy
plugins/nf-amazon/src/test/nextflow/cloud/aws/batch/AwsBatchTaskHandlerTest.groovy
plugins/nf-amazon/src/test/nextflow/executor/AwsBatchExecutorTest.groovy
plugins/nf-amazon/src/test/nextflow/executor/TaskArrayExecutorTest.groovy
plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchExecutor.groovy
plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchScriptLauncher.groovy
plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy
plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchExecutorTest.groovy

This PR refactor the support for job array provided by #3892. Main changes 
* Remove the need for `getWorkDir` and `getLaunchCommand` in `TaskHandler` 
* Add similar methods to TaskArrayExecutor providing default implementation 
* Fix support for Fusion 
* Add tests

Job array refactor 

---

docs/operator.md

Update operator docs to distinguish between operators that always return a queue channel and operators that may return a queue or value channel matching the source channel type.

Update operator return types

---

docs/config.md
modules/nextflow/src/main/groovy/nextflow/executor/LsfExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/PbsExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/PbsProExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/SlurmExecutor.groovy
modules/nextflow/src/test/groovy/nextflow/executor/LsfExecutorTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/PbsExecutorTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/PbsProExecutorTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/SlurmExecutorTest.groovy

This PR adds the ability to define a Slurm account in the nextflow config. For example: 
```
executor {
account = 'some-project-xyz'
}
```
Solve https://github.com/nextflow-io/nextflow/issues/4921
Updated to use `executor` instead of `slurm` on 7th May

Add account config option for grid executors

---

modules/nextflow/src/main/groovy/nextflow/exception/MissingModuleComponentException.groovy

Close #4980 
The problem is that the anonymous workflow is included in the script meta and it's name is null. A more radical solution would be to not add the anonymous workflow to the script meta, since I don't think it is ever retrieved from the script meta

Fix missing include error message

---

plugins/nf-console/build.gradle

This PR fixes the issue https://github.com/nextflow-io/nextflow/issues/4915 by using a patched build of the Groovy console dependencies based on https://github.com/apache/groovy/pull/2084

Fix groovy console issue

---

modules/nextflow/src/main/groovy/nextflow/Session.groovy
modules/nextflow/src/main/groovy/nextflow/cli/CmdPlugin.groovy
modules/nextflow/src/main/groovy/nextflow/script/ScriptRunner.groovy

This PR fixed the warning reported by the Console when running a script more then one time 
> WARN: Plugin manager not initialised -- Using built-in executors

Fix console "Plugin manager not initialised" warn

---

docs/executor.md
docs/process.md
modules/nextflow/src/main/groovy/nextflow/executor/AbstractGridExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/BridgeExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/CrgExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/FluxExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/HyperQueueExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/LsfExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/MoabExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/NqsiiExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/OarExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/PbsExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/PbsProExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/SgeExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/SlurmExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskConfig.groovy
modules/nextflow/src/test/groovy/nextflow/executor/AbstractGridExecutorTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/LsfExecutorTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/SlurmExecutorTest.groovy
modules/nextflow/src/test/groovy/nextflow/processor/TaskConfigTest.groovy

This PR adds the ability to define process `clusterOptions` as a list of values other than a string. 
Solves https://github.com/nextflow-io/nextflow/issues/4935

Implements clusterOptions as a list

---

docs/metadata.md
modules/nextflow/src/main/groovy/nextflow/Session.groovy
modules/nextflow/src/main/groovy/nextflow/config/ConfigBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/script/WorkflowMetadata.groovy
modules/nextflow/src/test/groovy/nextflow/config/ConfigBuilderTest.groovy
modules/nextflow/src/test/groovy/nextflow/script/WorkflowMetadataTest.groovy

This addresses #4478. I more-or-less copied the implementation of the `stubRun` property.

Add 'preview' to workflow runtime metadata

---

docs/wave.md
plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveClient.groovy

This PR removes `seqera` from the Conda default channels as it's not going to be maintained anymore

Remove `seqera` and `defaults` from Conda default channels

---

modules/nextflow/src/main/groovy/nextflow/extension/PublishOp.groovy
modules/nextflow/src/main/groovy/nextflow/script/OutputDsl.groovy
modules/nextflow/src/test/groovy/nextflow/script/OutputDslTest.groovy

This PR adds the `enabled` option to output DSL that allows to turn it on/off specific publish targets.

Add enabled property to output DSL

---

modules/nextflow/src/main/groovy/nextflow/processor/TaskPollingMonitor.groovy
modules/nf-commons/src/main/nextflow/SysEnv.groovy
modules/nf-commons/src/test/nextflow/SysEnvTest.groovy

The PR fixes the setting for the `NXF_ENABLE_ASYNC_FINALIZER` env variable. 
The expression `'some string' as boolean` is always true unless the string is null or empty. 
Therefore the setting is always enabled unless `NXF_ENABLE_ASYNC_FINALIZER` is set to an empty string.

Fix the default for async finalizer

---

docs/config.md
modules/nextflow/src/main/groovy/nextflow/container/CharliecloudBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/container/CharliecloudCache.groovy
modules/nextflow/src/main/groovy/nextflow/container/ContainerHandler.groovy
modules/nextflow/src/test/groovy/nextflow/container/CharliecloudCacheTest.groovy
modules/nextflow/src/test/groovy/nextflow/container/ContainerHandlerTest.groovy

Hi,
I noticed that my previous attempt (https://github.com/nextflow-io/nextflow/pull/4879) at making charliecloud handle the registry does not work. This PR fixes this by following the general approach of other container engines: letting normalizeDockerImageName handle this.
I also realized that my previous PR added three new options for charliecloud, but these were not documented, so this also updates the docs accordingly. This is identical to #5017, except that here I signed off the commits.

Charliecloud: registry, docs

---

modules/nextflow/src/main/groovy/nextflow/script/FunctionDef.groovy
modules/nextflow/src/test/groovy/nextflow/script/ScriptIncludesTest.groovy

This fixes the invocation of a module function having a String type in the signature and  GString value as argument.

Fix the invocation of function with gstring

---

modules/nextflow/src/main/groovy/nextflow/secret/LocalSecretsProvider.groovy
modules/nextflow/src/test/groovy/nextflow/secret/LocalSecretsProviderTest.groovy

Closes https://github.com/nextflow-io/nextflow/issues/4977  , i.e. handles proper escaping of dollar characther in secrets values.
- Uses `nextflow.util.Escape`
- Added unit test

LocalSecretsProvider: escapes dollar char

---

modules/nextflow/src/main/groovy/nextflow/scm/BitbucketRepositoryProvider.groovy
modules/nextflow/src/test/groovy/nextflow/scm/BitbucketRepositoryProviderTest.groovy

This PR fixes the handling of tags containing one or more `/` characters for Bitbucket repositories. 
See https://github.com/nextflow-io/nextflow/issues/4599 and https://jira.atlassian.com/browse/BCLOUD-20223.

Fix handling of tags with slash on Bitbucket

---

docs/_static/theme.css

Meet accessibility / contrast requirements.

Docs sidebar: Black text for version changer.

---

modules/nextflow/src/main/groovy/nextflow/extension/OperatorImpl.groovy
modules/nextflow/src/test/groovy/nextflow/extension/OperatorDsl2Test.groovy
modules/nextflow/src/test/groovy/nextflow/extension/OperatorImplTest.groovy

This PR fixes the `unique` operator hanging when applied to a value channel. Close #5052

Fix unique operator hangs when applied to value

---

modules/nextflow/src/main/groovy/nextflow/trace/TimelineObserver.groovy

fix a typo for a message giving a wrong advice : 
```
enable the 'timelime.overwrite' option in your config 
```
to
```
enable the 'timeline.overwrite' option in your config 
```

timelime -> timeline

---

modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy
modules/nextflow/src/test/groovy/nextflow/executor/BashWrapperBuilderTest.groovy
plugins/nf-google/src/test/nextflow/executor/BashWrapperBuilderWithGoogleTest.groovy

Close #4537 
HTTP response exceptions from the Google SDK are IOExceptions: https://cloud.google.com/java/docs/reference/google-http-client/latest/com.google.api.client.http.HttpResponseException

Retry Google 500 errors when writing task helper files

---

plugins/nf-amazon/src/main/nextflow/cloud/aws/util/S3BashLib.groovy
plugins/nf-amazon/src/test/nextflow/cloud/aws/util/S3BashLibTest.groovy
plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveClient.groovy
plugins/nf-wave/src/test/io/seqera/wave/plugin/WaveClientTest.groovy

This PR fixed the support for s5cmd 2.2.2. Closes #4757.

Fix support for s5cmd 2.2.2

---

modules/nextflow/src/main/groovy/nextflow/processor/TaskPollingMonitor.groovy

This PR prevents the execution from hanging when an exception is thrown in the task finalisation phase. 
Closes #5041

Fix executions hangs on finalisation exception

---

docs/metadata.md
docs/process.md
modules/nextflow/src/main/groovy/nextflow/Session.groovy
modules/nextflow/src/main/groovy/nextflow/processor/ErrorStrategy.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy
modules/nextflow/src/main/groovy/nextflow/script/WorkflowMetadata.groovy
modules/nextflow/src/test/groovy/nextflow/script/ProcessConfigTest.groovy
modules/nextflow/src/test/groovy/nextflow/script/WorkflowMetadataTest.groovy
tests/checks/error-ignore-then-fail.nf/.checks
tests/checks/error-ignore-then-fail.nf/.config
tests/checks/error-ignore-then-fail.nf/.nextflow.config
tests/error-ignore-then-fail.nf

This PR implements the fail on ignore by using by setting the option `nextflow.enable.failOnIgnore` in the nextflow config file.

4446 ignore then fail strategy v3

---

plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzHelper.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzHelperTest.groovy

This PR allows configuring the Azure Blob client retry options using `azure.retryPolicy` configuration settings. Find more details [here](https://www.nextflow.io/docs/latest/config.html#scope-azure). 
Closes #5097. Fixes #5067.

Add retry options to Azure Blob client

---

docs/operator.md

Before this PR, the docs claimed the "default" value for these configuration values was true when strict mode is enabled. In truth, the value is _set_ to `true` when strict mode is enabled (stronger than just the default).

Documentation clarification for `failOnDuplicate` and `failOnMismatch`

---

docs/install.md

Both I and @odagayev missed this half of the bullet point, and I guess many others do too.
Moved the "open a new terminal" onto it's own bullet point so that it's harder to miss.
'cc @justinegeffen @christopher-hakkaart @vdauwera

Installation instructions - new terminal onto its own line

---

docs/process.md

Should improve clarity around the role of `workflow.failOnIgnore` with the different errorStrategies

Adds example of error strategies to documentation

---

docs/config.md
docs/requirements.txt
modules/nextflow/src/main/groovy/nextflow/processor/PublishDir.groovy
modules/nextflow/src/test/groovy/nextflow/processor/PublishDirTest.groovy

This PR adds the ability to override the default of failOnError publish setting default by using the env variable `NXF_PUBLISH_FAIL_ON_ERROR=true|false`.

Add ability to override failOnError setting default via env variable

---

docs/process.md

Based on some improved wording by @pinin4fjords this improves the language for the errorStrategy examples.

Improve wording for errorStrategy examples

---

docs/process.md

Suggestion from Slack by @vagkaratzas
Pending tasks are cancelled immediately. Only submitted and running tasks are left to complete.

Docs: Pending tasks won't execute

---

.gitignore
docs/config.md

Fix the default AWS Logs group name in the docs consistently with the implementation 
https://github.com/nextflow-io/nextflow/blob/1ab8d56a628b2d7361d0bf37fa069b410086d69a/plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchHelper.groovy#L209-L209

Fix aws logs group name

---

docs/config.md
plugins/nf-google/src/main/nextflow/cloud/google/batch/client/BatchConfig.groovy
plugins/nf-google/src/test/nextflow/cloud/google/batch/client/BatchConfigTest.groovy

This PR introduces a new config option that allows setting one more exit codes when running a task with Google Batch that should trigger an automatic retry when a task returns an error code and the opinion `google.batch.maxSpotAttempts` is set to a value greater than zero.
By default this option is set to `[50001]`. See the [Google docs](https://cloud.google.com/batch/docs/troubleshooting#vm_preemption_50001) for more details.

Make auto retry codes configurable

---

plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsContainerOptionsMapper.groovy
plugins/nf-amazon/src/test/nextflow/cloud/aws/batch/AwsContainerOptionsMapperTest.groovy

This commit ensures that the `shm-size` option is correctly parsed from the containerOptions. This is necessary to ensure that the correct value in MiB is passed to the AWS Batch API when creating a job definition.
Fixes https://github.com/nextflow-io/nextflow/issues/5176

More robust parsing of shm-size containerOptions

---

modules/nextflow/src/main/groovy/nextflow/plugin/extension/PluginExtensionProvider.groovy
modules/nextflow/src/test/groovy/nextflow/script/ScriptDslTest.groovy

Consider the following script:
```groovy
Channel.doesNotExist()
```
Nextflow does not throw an error for an invalid channel factory. This PR adds the following error:
```
Missing process or function Channel.doesNotExist()
-- Check script 'test.nf' at line: 1 or see '.nextflow.log' file for more details
```
reported by @robsyme

Add runtime error for missing channel factory

---

modules/nf-httpfs/src/main/nextflow/file/http/XFileSystemProvider.groovy
modules/nf-httpfs/src/test/nextflow/file/http/HttpFilesTests.groovy

This commit fixes the use of `Files.readAllBytes` when applied to a Http file `Path`. The implement was only working for files smaller than buffer object.

Fix readAllBytes with http files

---

docs/module.md
modules/nextflow/src/main/groovy/nextflow/script/IncludeDef.groovy

Based on our discussion this morning

Deprecate module addParams() and params()

---

docs/config.md
plugins/nf-google/src/main/nextflow/cloud/google/batch/client/BatchConfig.groovy
plugins/nf-google/src/test/nextflow/cloud/google/batch/client/BatchConfigTest.groovy

This PR disables the automatic retry made by Googke Batch when a spot instance is reclaimed. 
The main reasons to disable this capability is: 
* The same tasks can be re-tried multiple times incurring in significant spending increase with the user is a aware of that 
* The Google automatic retry re-execute a task in the same working directory because it's not directly managed by nextflow. This can introduce nasty side effects with partial/corrupted data left in a previous execution 
* There's not log/visual feedback during the pipeline execution, because it's managed directly by Google Batch. 
* Keep it aligned with same feature with Google Batch that's disabled by default. 
User can still enable this capability by setting the following option: 
```
google.batch.maxSpotAttempts = n 
``` …

Disable Google Batch spot retries

---

docs/_templates/layout.html

Docs pages under the developer/ directory (workflow diagram, packages, core plugins etc) had a broken Seqera logo in the sidebar.
Fixes this by using a Sphinx function to always use a path for that file that's relative to the build root.
To test, see https://nextflow.io/docs/latest/developer/index.html:
@netlify /developer/index.html

Docs sidebar: Fix logo for nested pages.

---

docs/conf.py

Should avoid duplicate `v` in google results:
Reported by @FriederikeHanssen

Avoid double vv in `<title>` for docs

---

nextflow

The use of Java virtual threads is supported as experimental feature. This PR disables the automatic use of virtual threads with Java 21 or later.

Disable automatic detection of virtual threads

---

docs/config.md
plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy
plugins/nf-google/src/main/nextflow/cloud/google/batch/client/BatchConfig.groovy
plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchTaskHandlerTest.groovy
plugins/nf-google/src/test/nextflow/cloud/google/batch/client/BatchConfigTest.groovy

The default boot image is batch-cos, but it may not be desired in all
situations. In particular, there is an ongoing issue in which the
batch-cos image does not retry pulling a docker image if there was a
network issue. The user may also have some some other configuration
pre-configured in their custom boot image.
Signed-off-by: Siddhartha Bagaria <1929612+siddharthab@users.noreply.github.com>

In Google Batch, support user specified boot images

---

plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzActiveDirectoryOpts.groovy
plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzRegistryOpts.groovy
plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzStorageOpts.groovy
plugins/nf-azure/src/main/nextflow/cloud/azure/fusion/AzFusionEnv.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzBatchServiceTest.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/fusion/AzFusionEnvTest.groovy

This PR extends the `nextflow.cloud.azure.fusion.AzFusionEnv` class so that it now takes into account a potential Azure Managed Identity in Nextflow's [configuration file](https://www.nextflow.io/docs/latest/azure.html#managed-identities). This also fixes a configuration error (#5081) by which Nextflow complained of a missing SAS token despite having a Managed Identity properly configured.

Support Azure Managed Identities in Fusion configuration logic

---

docs/google.md
plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy

When both boot disk image and instance template are specified, the
instance template gets priority, as with many other options covered by
instance templates. Warn the user in this case.
This was missed in #5268.
Signed-off-by: Siddhartha Bagaria <1929612+siddharthab@users.noreply.github.com>

In Google Batch, add missed warning

---

modules/nextflow/src/main/groovy/nextflow/executor/PbsExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/PbsProExecutor.groovy
modules/nextflow/src/test/groovy/nextflow/executor/PbsExecutorTest.groovy

Fix job array syntax for PBS/Torque executor

---

build.gradle
modules/nextflow/build.gradle
modules/nf-commons/build.gradle
modules/nf-httpfs/build.gradle
plugins/nf-amazon/build.gradle
plugins/nf-azure/build.gradle
plugins/nf-cloudcache/build.gradle
plugins/nf-codecommit/build.gradle
plugins/nf-console/build.gradle
plugins/nf-google/build.gradle
plugins/nf-tower/build.gradle
plugins/nf-wave/build.gradle

This PR bumps groovy runtime to version 4.0.23

Bump groovy 4.0.23

---

docs/config.md
modules/nextflow/src/main/groovy/nextflow/container/CharliecloudBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/container/CharliecloudCache.groovy
modules/nextflow/src/test/groovy/nextflow/container/CharliecloudBuilderTest.groovy
modules/nextflow/src/test/groovy/nextflow/container/CharliecloudCacheTest.groovy

Here are changes to the charliecloud driver.
- `charliecloud.writeFake` is true by default (!)
- if `charliecloud.writeFake` is true and `$CH_IMAGE_STORAGE` is set, images will go into `$CH_IMAGE_STORAGE` and be run from there with --write-fake (will be run by name in that case).
- if charliecloud.writeFake is true, but `$CH_IMAGE_STORAGE` is unset, images will go into `charliecloud.cacheDir`, `$NXF_CHARLIECLOUD_CACHE` or `work/charliecloud` (order of priority) and will be run by path (since run by name only works if `$CH_IMAGE_STORAGE `is set)
- if `charliecloud.writeFake` is set to `false`, images will need to be run with `-w` to enable mounting of the workDir. In this case `$CH_IMAGE_STORAGE` will not be used to store images, since `$CH_IMAGE_STORAGE` is incompatible with `-w`. Images …

Update container handling with charliecloud

---

modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy

This PR adds the container image name in the error dump reported when a task fail. For example 
```
Work dir:
/Users/pditommaso/Projects/rnaseq-nf/work/3c/84cf5887bae50581acb8df41fa01a4
Container:
community.wave.seqera.io/library/fastqc:0.12.1--959cb910d069d258
Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

Add container tip in the task error report

---

docs/config.md
modules/nextflow/src/main/groovy/nextflow/config/Manifest.groovy
modules/nextflow/src/test/groovy/nextflow/config/ManifestTest.groovy

Include new fields in the manifest and update the documentation with the new fields

Include additional fields to manifest

---

plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzStorageOpts.groovy
plugins/nf-azure/src/main/nextflow/cloud/azure/fusion/AzFusionEnv.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/fusion/AzFusionEnvTest.groovy

This PR fixes two issues: 
* Azure Fusion missing authentication if accountKey is provided
* Catch when service principal exists but no keys or SAS

Fix Azure Fusion env misses credentials when no key or SAS provided

---

plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsBatchConfig.groovy

This PR fixes the use of zero as value for AWS batch `maxSpotAttempts` setting  
Solve #5330

Fix AWS spot attempts with zero value

---

docs/_templates/layout.html

Call the default version of the docs `latest` instead of `development`, as it's less scary. And still accurate. Also then matches the URL.

Docs version dropdown: latest

---

modules/nf-httpfs/src/main/nextflow/file/http/XPath.groovy

Add XPath default serializer

---

plugins/nf-google/src/main/nextflow/cloud/google/batch/client/BatchClient.groovy

Raised by Adam during some testing. The Google Batch describeTask didn't have a retry policy like the other methods and sure enough a 5xx error struck

Add retry policy to google batch describe task

---

docs/reference/channel.md
modules/nextflow/src/main/groovy/nextflow/datasource/SraExplorer.groovy
modules/nextflow/src/main/groovy/nextflow/datasource/SraRetryConfig.groovy
modules/nextflow/src/test/groovy/nextflow/ChannelTest.groovy
modules/nextflow/src/test/groovy/nextflow/datasource/SraExplorerTest.groovy
modules/nextflow/src/test/groovy/nextflow/datasource/SraRetryConfigTest.groovy

A retry policy is included in the `Channel.fromSRA` factory following the same approach as used when retriable failures appear in the wave, azure APIs. 
- The `SraRetryConfig` and corresponding `SraRetryConfigTest` classes are created to manage the retry policy properties
- `SraExplorer` class is modify to include the `retryPolicy` option and the management of the retry of the request calls. 
- New tests has been added to `SraExplorerTest` and `ChannelTest` to validate the changes.
- Update documentation with the new `retryPolicy` option in the `Channel.fromSRA`
Note: The `SraExplorer` class was using a deprecated constructor `URL()` to create a URL. As suggested by the deprecation message, it is changed by `new URI().toURL()`

Add retry policy in Channel.fromSRA factory

---

docs/wave.md

This PR updates Wave docs with new capabilities

Add wave docs

---

modules/nextflow/src/main/groovy/nextflow/trace/ProgressRecord.groovy
modules/nextflow/src/test/groovy/nextflow/trace/ProgressRecordTest.groovy

The number of total tasks during the execution did not match with the total tasks at the end of the execution. This was due to  aborted taks where not included in the ProgressRecord total count. This PR fixes it, including aborted tasks to the total count.

Fix incorrect total count at the end of the execution

---

docs/wave.md
plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveClient.groovy
plugins/nf-wave/src/main/io/seqera/wave/plugin/config/WaveConfig.groovy
plugins/nf-wave/src/test/io/seqera/wave/plugin/WaveClientTest.groovy
plugins/nf-wave/src/test/io/seqera/wave/plugin/config/WaveConfigTest.groovy

This PR changes the setting `scan.levels` to `scan.allowedLevels`

Change to scan.allowedLevels

---

modules/nextflow/src/main/groovy/nextflow/cli/CmdConfig.groovy
modules/nextflow/src/main/groovy/nextflow/util/ConfigHelper.groovy
modules/nextflow/src/test/groovy/nextflow/cli/CmdConfigTest.groovy
modules/nextflow/src/test/groovy/nextflow/util/ConfigHelperTest.groovy

This PR adds a new `-output` option to `config` command that allows specifying `yaml` and `json` other the existing `canonical`, `properties` and `flat` formats. 
The option `-flat` and `-properties` have been deprecated in favour of `-output`.
Solves #5398

Add more out formats to config command

---

modules/nf-commons/src/main/nextflow/file/CopyMoveHelper.java
modules/nf-httpfs/src/main/nextflow/file/http/XFileSystemProvider.groovy

Proof of concept for #5360 
This uses Java's [OpenOption](https://docs.oracle.com/javase/8/docs/api/java/nio/file/OpenOption.html) mechanism to pass a configuration param to the `XFileSystemProvider`, allowing a script to declare that it doesn't care if the input stream is closed before being fully read:
```groovy
import nextflow.file.http.HttpOpenOption
def firstLine(path) {
path.withInputStream(HttpOpenOption.ALLOW_EARLY_CLOSE) {
def r = new BufferedReader(new InputStreamReader(it))
return r.readLine()
}
}
```
This approach is quite flexible and generic, since it would also allow other `OpenOptions` to be passed to other `FileSystemProviders`, and as a result might be a little in conflict with the formalisation of a nextflow script syntax. An alternative could be to add a single-purpose …

Allow http file to be closed early

---

modules/nextflow/src/main/groovy/nextflow/config/ConfigClosurePlaceholder.groovy
modules/nextflow/src/main/groovy/nextflow/util/ConfigHelper.groovy
modules/nextflow/src/test/groovy/nextflow/cli/CmdConfigTest.groovy
modules/nextflow/src/test/groovy/nextflow/util/ConfigHelperTest.groovy

This PR fixed the rendering of closures in config file reporting as strings. 
For example 
```
{ 
"process": {
"memory": "{ 1.GB }"
}
} 
``` 
or 
```
process:
memory: '{ 1.GB }'
```

Fix closure rendering in yaml and json config

---

modules/nextflow/src/main/groovy/nextflow/executor/AbstractGridExecutor.groovy
modules/nextflow/src/test/groovy/nextflow/executor/AbstractGridExecutorTest.groovy

The equals character from nf-core modules/local/hicpro/dnase_mapping_stats.nf causes pipeline to crash on SGE executor.
Add "=" to list of invalid chars

Remove invalid equals char

---

docs/reference/operator.md

Close #5354 
Clarify that `subscribe` should be used only as a terminal operator.
We could also update the `subscribe()` API to return `void`, but that could break some existing pipeline. On the other hand, from the issue it sounds like it already causes the pipeline to hang, so perhaps it would be better to change the API so that there is a runtime error.
Doesn't matter much to me because I have plans for a "v2" operator library anyway

Document `subscribe` as a teminal operator

---

docs/process.md
docs/reference/process.md
modules/nextflow/src/main/groovy/nextflow/processor/TaskPollingMonitor.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy
modules/nextflow/src/testFixtures/groovy/test/MockHelpers.groovy
tests/checks/trace-access.nf/.checks
tests/trace-access.nf

When retry trace record is generated and included in the task context with variable `trace`
In the first attempt, trace is null. I tried to set a partial trace record for the first attempt generating the trace record just after the creation of the TaskHandler. But the evaluation of the directives is executed before the generation of the first TaskHandler at executor.submit. So, the value was null. One alternative, could be to move the generation of the trace record to the TaskRun but it implies to move some data such as the status, start and stop time in the TaskRun.
Included a suggestion for documentation

Exposing trace record meta info in the task context

---

plugins/nf-tower/src/main/io/seqera/tower/plugin/LogsCheckpoint.groovy

close #5433 
- Moving the start of LogsCheckpoit thread from onWorkflowBegin to onWorkflowCreate
- Implementing onWorkflowError

Fix nf-tower plugin to upload logs when early failures 

---

modules/nextflow/src/main/groovy/nextflow/util/NameGenerator.groovy

Added two spanish scientists with occasion of the nextflow 2024 summit in Barcelona

added two spanish scientists 

---

.github/workflows/generate-send-dependencies.yml

Added a Github action to generate and submit the dependencies used by the project. Then, dependabot will be able to display the vulnerabilities found on the libraries used by Nextflow. 
Task has been tested on PR:
although result cannot be published because it is not being run from `master` branch:
>Notice: Submitted dependency-graph-reports/generate_and_submit_dependency_graph_for_nextflow-dependency-submission-nextflow.json: The snapshot was accepted, but it is not for the default branch. It will not update dependency results for the repository.

Add GHA to submit dependencies to dependabot

---

modules/nextflow/build.gradle

`com.github.johnrengelman.shadow` plugin has moved to `com.gradleup.shadow`
This change updates to the new name and latest version, and in so doing updates a transitive build-time dependency on the vulnerable apache commons-io 2.11.0 to the latest 2.17.0

Update gradle 'shadow' plugin version to 8.3.5

---

modules/nextflow/build.gradle
plugins/nf-google/build.gradle

This change updates bouncy castle to the 1.78.1 to get the latest security fixes.
It also switches from the Java 1.5+ compatible version (_jdk15on_) to the Java 1.8+ compatible version (_jdk18on_) since I don't think Nextflow supports Java versions that old.

Update 'bouncycastle' dependency to 1.78.1

---

docs/reference/process.md

Extends the accelerator documentation to clarify that further requirements might be needed.
This wasn't obvious from the existing docs so I felt like it needed to be clarified.

Add further instructions for using the accelerator directive and additional options

---

.github/workflows/build.yml
validation/google.sh
validation/wave-tests/example6/nextflow.config
validation/wave-tests/example6/run-aws.sh
validation/wave-tests/example6/run-gcp.sh
validation/wave-tests/example6/run.sh
validation/wave.sh

Enable the Wave GCP test, rather than running the AWS test twice.

Enable wave gcp test

---

modules/nextflow/src/main/groovy/nextflow/conda/CondaCache.groovy
modules/nextflow/src/test/groovy/nextflow/conda/CondaCacheTest.groovy

Fix conda packages with same name and content but different path.
Include a hash of the path in the environment prefix directory.

Fix overlapping file lock exception

---

modules/nextflow/src/main/groovy/nextflow/processor/TaskRun.groovy
modules/nextflow/src/test/groovy/nextflow/processor/TaskRunTest.groovy

When migrating resolve evaluation from TaskProcessor to TaskRun it was not checking if stub block was not defined.
Adding stub check and including the corresponding unit test.

Fixing bug when execution with stub and no stub defined

---

docs/process.md

Clarify that template rendering will fail when a Nextflow variable is missing, even if the variable is commented out in the template
Inspired by this [test case](https://github.com/FriederikeHanssen/mre/tree/python_template) by @FriederikeHanssen

Clarify behavior of template scripts

---

modules/nextflow/src/main/groovy/nextflow/scm/RepositoryProvider.groovy
modules/nextflow/src/test/groovy/nextflow/scm/RepositoryProviderTest.groovy

One line change to make the RepositoryProvider.revision a public property. The driver for this is to allow clients to better manage repository validation by allowing the RepositoryProvider to be the source of truth for the current revision that is set. 
An alternate approach would be to add revision validation within the RepositoryProvider itself, e.g. 
`setRevision(String revision, boolean validateRevision = false)` 
Validation could then proceed by verifying the revision is present in getBranches or getTags.

feat: RepositoryProvider.revision now public property

---

plugins/nf-wave/src/main/io/seqera/wave/plugin/resolver/WaveContainerResolver.groovy

This PR fixes the access to the method [isContainerReady](https://github.com/nextflow-io/nextflow/blob/803f4ee386c63e945dfd3daf5cbef895428a456b/plugins/nf-wave/src/main/io/seqera/wave/plugin/resolver/WaveContainerResolver.groovy#L131-L131) when Wave is disabled. 
Solve #5503

Fix isContainerReady when wave is disabled

---

modules/nextflow/src/main/groovy/nextflow/Session.groovy
modules/nextflow/src/main/groovy/nextflow/util/LoggerHelper.groovy

This PR is a an attempt to fix issues https://github.com/nextflow-io/nextflow/issues/5437 turning off the printing of logs once `abort` has been invoked

Fix secondary exceptions from console

---

docs/cache-and-resume.md
docs/channel.md
docs/conda.md
docs/container.md
docs/developer/nextflow.ast.md
docs/developer/plugins.md
docs/dsl1.md
docs/google.md
docs/metrics.md
docs/overview.md
docs/process.md
docs/reference/channel.md
docs/reference/process.md
docs/secrets.md
docs/spack.md
docs/vscode.md
docs/your-first-script.md

The strict syntax is a bit more picky about the process `script:` section label ([source](https://nextflow.io/docs/latest/vscode.html#restricted-syntax)):
> The Nextflow language specification allows the `script:` label to be omitted only if there are no other sections
This PR updates process snippets throughout the docs to comply with this rule.

Update process snippets to comply with strict syntax

---

docs/reference/syntax.md

Forgot to document these operators in the syntax reference:
- spread dot (`x*.y`)
- safe dot (`x?.y`)

Document spread dot and safe dot

---

docs/reference/process.md

Process directive machineType was out of date. Updated it here.

Update machineType docs to reflect supported executors

---

docs/cli.md
docs/config.md
docs/reference/cli.md

- Added params file section to the config page
- Reduced CLI documentation (not the place to describe JSON and YAML)
- Added link to config page in the example
cc @FriederikeHanssen
@netlify /config#params-file

Docs: Move `-params-file` config from CLI to config

---

docs/conda.md
docs/wave.md

* Add docs about Conda lock files
* Create new headings specifically for PyPI, text files and lock files
* Add mention of ability to use PyPI packages to the Wave docs, with link
@netlify /conda#use-conda-environment-files

Docs: Improve Conda docs - PyPI + lock files

---

modules/nextflow/src/main/groovy/nextflow/conda/CondaCache.groovy
modules/nextflow/src/test/groovy/nextflow/conda/CondaCacheTest.groovy

Close #5530 
Alternative for fixing the overlapping conda lock file reusing the condaPrefixPath function.

Fix overlapping conda lock file

---

modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy
modules/nextflow/src/main/resources/nextflow/executor/command-run.txt
modules/nextflow/src/test/groovy/nextflow/executor/BashWrapperBuilderTest.groovy
modules/nextflow/src/test/resources/nextflow/executor/test-bash-wrapper-with-trace.txt
modules/nextflow/src/test/resources/nextflow/executor/test-bash-wrapper.txt
plugins/nf-google/src/main/nextflow/cloud/google/lifesciences/GoogleLifeSciencesHelper.groovy
plugins/nf-google/src/main/nextflow/cloud/google/lifesciences/GoogleLifeSciencesScriptLauncher.groovy
plugins/nf-google/src/test/nextflow/cloud/google/lifesciences/GoogleLifeSciencesHelperTest.groovy
plugins/nf-google/src/test/nextflow/cloud/google/lifesciences/GoogleLifeSciencesScriptLauncherTest.groovy
plugins/nf-google/src/test/nextflow/cloud/google/lifesciences/bash-wrapper-gcp.txt

This is PR is an improvement of PR #5345 trying to keep the changes at level of of launcher script. 
In particular uses re-organise the `nxf_unstage` function splitting into `nxf_unstage_outputs` and `nxf_unstage_std_files` helper functions. 
@jorgee please check if it makes sense to you

Improve handling unstage  outputs and controls

---

docs/_static/dag.mmd
modules/nextflow/src/main/resources/nextflow/dag/mermaid.dag.template.html

Figured that VSCode shouldn't get all the fun: https://github.com/nextflow-io/vscode-language-nextflow/pull/59
Ported the Nextflow greens theme over to the main Nextflow run-time DAG.
| Before | After |
| -- | -- |
| ![CleanShot 2024-12-01 at 23 56 35@2x](https://github.com/user-attachments/assets/83251094-a2e8-426b-b728-48a1998b3ed7) | ![CleanShot 2024-12-01 at 23 56 41@2x](https://github.com/user-attachments/assets/059afe6a-0fd6-4f2b-b975-c2b16f357695) |
Updated example from the [docs](https://www.nextflow.io/docs/latest/reports.html#workflow-diagram):
[new-rnaseq.html.zip](https://github.com/user-attachments/files/17970635/new-rnaseq.html.zip)
@netlify /reports.html#workflow-diagram

Customise mermaid diagram theme in DAG template

---

.github/workflows/seqeradocs-changelog.yml

Add a CI workflow that on release events would create a pull-request against https://github.com/seqeralabs/docs
A PR would look like this: https://github.com/seqeralabs/docs/pull/324 which will add an entry into this feed: https://docs.seqera.io/changelog/tags/nextflow
Assumes two secrets are set: `DOCS_BOT_APP_ID` and `DOCS_BOT_APP_PRIVATE_KEY` - they can be found in the 1password Engineering vault.

Workflow to sync changelog to Seqera docs

---

modules/nextflow/build.gradle
modules/nextflow/src/main/groovy/nextflow/scm/AssetManager.groovy

Otherwise the tests fail if you have git config setting `gpg.format=ssh`, with the following error:
```
java.lang.IllegalArgumentException: Invalid value: gpg.format=ssh
at org.eclipse.jgit.lib.DefaultTypedConfigGetter.getEnum(DefaultTypedConfigGetter.java:103)
at org.eclipse.jgit.lib.Config.getEnum(Config.java:454)
at org.eclipse.jgit.lib.GpgConfig.<init>(GpgConfig.java:86)
at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:661)
at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:188)
at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:1)
at nextflow.scm.LocalRepositoryProviderTest.setup(LocalRepositoryProviderTest.groovy:48)
```

Update jgit to 7.1.0

---

plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy
plugins/nf-google/src/main/nextflow/cloud/google/batch/client/BatchClient.groovy
plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchTaskHandlerTest.groovy

When there is an internal error in Google Batch the job during scheduling. Jobs go from queued to failed. This situation is happening when request a VM type which is not available in the selected region. In this situation, there are no tasks in the batch job and NF is blocked in an infinite loop caused by the following part of code.
[nextflow/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy](https://github.com/nextflow-io/nextflow/blob/62fc0017ffae1ea151581f738c17ab840649aa0c/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy#L448-L449)
In this PR, this part is modified including a job status check to avoid to continue checking when job is failed.
I still have pending to decide what to do if job do not have tasks and …

Fix Google Batch hang when internal error during scheduling

---

docs/reference/process.md

The `csi` option is implied to be a name but is actually a config object. Updated to be consistent with similar options (e.g. `emptyDir`)

Fix docs for `csi` option in `pod` directive

---

modules/nextflow/src/main/groovy/nextflow/executor/CachedTaskHandler.groovy
modules/nextflow/src/main/groovy/nextflow/executor/GridTaskHandler.groovy
modules/nextflow/src/main/groovy/nextflow/executor/NopeExecutor.groovy
modules/nextflow/src/main/groovy/nextflow/executor/StoredTaskHandler.groovy
modules/nextflow/src/main/groovy/nextflow/executor/local/LocalTaskHandler.groovy
modules/nextflow/src/main/groovy/nextflow/executor/local/NativeTaskHandler.groovy
modules/nextflow/src/main/groovy/nextflow/k8s/K8sTaskHandler.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskHandler.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskPollingMonitor.groovy
modules/nextflow/src/test/groovy/nextflow/k8s/K8sTaskHandlerTest.groovy
modules/nextflow/src/test/groovy/nextflow/processor/TaskPollingMonitorTest.groovy
modules/nextflow/src/testFixtures/groovy/test/MockHelpers.groovy
plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchTaskHandler.groovy
plugins/nf-amazon/src/test/nextflow/cloud/aws/batch/AwsBatchTaskHandlerTest.groovy
plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchTaskHandler.groovy
plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy
plugins/nf-google/src/main/nextflow/cloud/google/lifesciences/GoogleLifeSciencesTaskHandler.groovy
plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchTaskHandlerTest.groovy

This PR improves the task kill logic as below: 
1. implement the flag check in the `kill` method (instead of a new one) for a) API backward compatibility, and b) make sure it's invoked by the already existing component
2. use an `AtomicBool` to make the handling of a possible race condition more robust 
3. rename existing `kill` methods to `killTask` and declare `protected` to highlight it should not be invoked directly 
4. do not mark `kill` as `final` (even if it would be better) to prevent breaking asking plugins

Improve kill task logic

---

modules/nextflow/src/main/groovy/nextflow/cli/CmdInspect.groovy
modules/nextflow/src/main/groovy/nextflow/container/ContainerHandler.groovy
modules/nextflow/src/main/groovy/nextflow/container/inspect/ContainerInspectMode.groovy
modules/nextflow/src/test/groovy/nextflow/container/inspect/ContainerInspectModeTest.groovy
plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveClient.groovy
plugins/nf-wave/src/test/io/seqera/wave/plugin/WaveClientTest.groovy

This PR improve the granularity of `ContainerInspectMode semantics so that it's possible independently if the inspect mode has been enabled and if it's running in dry-run (or concretize) mode.
Previously the `active` method was implemented with the semantics of "dry-run". In this PR it the method is has been renamed to `dryRun` to better reflect its semantics. 
Along with this a method `activate` it has been added to detect when the inspect mode is running.

Improve inspect mode

---

docs/snippets/your-first-script.nf

While it appears to work fine, the vs code extension for nextflow indicates that the script element should be used.
I thought it should be corrected as this is the first snippet that a user will try executing.
https://www.nextflow.io/docs/latest/your-first-script.html
Here is the VS Code view of the snippet prior to fixing.

Add "script:" before bash script in 'your-first-script' snippet

---

docs/vscode.md

Add some notes to the syntax migration guide, as well as some updates for v1.0.3 of the language server.

Update syntax docs

---

docs/reference/stdlib.md

I keep searching for this specific term and it's been removed. Apparently I wasn't the only one.
Adding it back so that hitting this term into the search box brings up the right page.
'cc @theJasonFan

Add term 'workflow introspection' to docs

---

modules/nextflow/src/main/groovy/nextflow/executor/GridTaskHandler.groovy
modules/nf-commons/src/main/nextflow/file/FileHelper.groovy

Close #5630 
Lustre performs attribute caching similar to NFS, but the `stat` command on a Lustre filesystem returns `lustre` instead of `nfs`. This PR adds a check for Lustre so that the grid executors can handle attribute caching for both NFS and Lustre.

Handle attribute caching with Lustre filesystem

---

modules/nextflow/src/main/groovy/nextflow/executor/FluxExecutor.groovy
modules/nextflow/src/test/groovy/nextflow/executor/FluxExecutorTest.groovy

problem: the current regex does not include a regular f
solution: add an OR (|) that will allow either.

bug: update flux job id regular expression

---

modules/nextflow/src/main/groovy/nextflow/scm/AzureRepositoryProvider.groovy
modules/nextflow/src/main/groovy/nextflow/scm/ProviderConfig.groovy
modules/nextflow/src/test/groovy/nextflow/scm/AzureRepositoryProviderTest.groovy
modules/nextflow/src/test/groovy/nextflow/scm/ProviderConfigTest.groovy

- Add support for Clone URL.
- Unifies the parse of URL path to extract organization, project and repository in all the supported cases. (AzureRepositoryProvider.getUniformPath). It is used in the AzureRepositoryProvider constructor to get the project and repo and in the ProviderConfig.resolveProjectName used when pulling the pipeline from a repo.

Fix azure repos when clone URL is used

---

modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy
modules/nextflow/src/test/groovy/nextflow/cli/CmdRunTest.groovy

Fix CLI params normalization

---

docs/reference/process.md

Improve storeDir docs

---

docs/reference/config.md

I found the Google Batch spot documentation a bit hard to follow, I've updated the language here to see if it makes more sense.

Update Google Batch docs to clarify spot retry behaviour

---

plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy

These PR add warning messages when using Cloudinfo fails to retrieve the machine type for a Google Batch

Warning messages when Cloudinfo fails in Google Batch machine type selection

---

modules/nextflow/src/main/groovy/nextflow/script/params/EnvOutParam.groovy
modules/nextflow/src/test/groovy/nextflow/script/params/EnvOutParamTest.groovy

The strict syntax requires process env inputs/outputs to be quoted. This works for env inputs, but apparently env outputs did not work this way prior to 24.04. Support for this syntax was added as a side effect of [eval outputs](https://github.com/nextflow-io/nextflow/commit/df978113cf05f8767dbd453baff976e899194bcc).
Since some users have reported issues when trying to use this syntax with 23.10, this PR backports just the quoted env syntax.

Fix `env` output with quotes

---

modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy

This prevent the use of existing task work dir when launching a new task execution. 
This may happen when task execution already run but it failed to save the cache metadata and therefore it is not recognised as resume dir. 
Close https://github.com/nextflow-io/nextflow/issues/5595

Prevent the use existing work dir

---

modules/nextflow/src/main/groovy/nextflow/processor/TaskHandler.groovy
modules/nextflow/src/main/groovy/nextflow/trace/TraceRecord.groovy
modules/nextflow/src/test/groovy/nextflow/trace/TraceRecordTest.groovy

This PR uses Java NIO API to read the trace file providing an alternative implementation to #5501

Use Java API to read trace file

---

modules/nextflow/src/main/groovy/nextflow/processor/TaskConfig.groovy
modules/nextflow/src/test/groovy/nextflow/processor/TaskConfigTest.groovy

This PR strengthen the validation to `process.shell` directive to prevent empty, multiline, trailing and leading blanks

Strengthen shell directive validation

---

build.gradle

Configure the target Java version inside the gradle `java` block next to the toolchain info, rather than on a per-task basis. This propogates the information to all the variants, in particular the test fixtures.
Without this, a project depending on the test fixtures (such as a nextflow plugin) can, in some situations, fail to build with the following error:
```
- Variant 'testFixturesApiElements' declares a library for use during compile-time, packaged as a jar, and its dependencies declared externally:
- Incompatible because this component declares a component, compatible with Java 21 and the consumer needed a component, compatible with Java 17
```
Using command `gradle :nextflow:outgoingVariants` to show the variants, the 'main' variants correctly declare that they require Java 17:
but …

Configure target java version alongside gradle toolchain

---

docs/developer/index.md

The new `dist` release makes it easier to build and test locally. Updating the developer docs to reflect the new approach

Improve developer docs for local builds

---

modules/nextflow/src/main/groovy/nextflow/secret/LocalSecretsProvider.groovy

This PR revers the cleanup of local secret made via https://github.com/nextflow-io/nextflow/pull/5061 .
The rationale is that that change makes impossible to replicate the execution of failed task upon completion. 
Solves #5613

Revert Fix the cleanup of local secret file 

---

modules/nextflow/src/main/groovy/nextflow/util/BlockingThreadExecutorFactory.groovy
modules/nextflow/src/main/groovy/nextflow/util/HardBlockingQueue.groovy
modules/nextflow/src/main/groovy/nextflow/util/ThreadPoolBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/util/ThreadPoolManager.groovy
modules/nextflow/src/test/groovy/nextflow/util/ThreadPoolBuilderTest.groovy

This PR changes the default setting `ThreadPoolBuilder` class so that: 
* by default uses an unbound queue instead in order to prevent the triggering of the rejection policy when exceeding the queue size 
* use [BlockingBlockingQueue](https://github.com/nextflow-io/nextflow/blob/075ef4ccbec7caf122b966ff89af56d5b0351e30/modules/nextflow/src/main/groovy/nextflow/util/BlockingBlockingQueue.groovy#L33-L33) when the queue size is specified 
* use the `AbortPolicy` as rejection policy to prevent the issue reported [here](https://github.com/nextflow-io/nextflow/issues/5363#issuecomment-2607211371)
* default to `-1`(unbound) queue size in the [ThreadPoolManager](https://github.com/nextflow-io/nextflow/blob/075ef4ccbec7caf122b966ff89af56d5b0351e30/modules/nextflow/src/main/groovy/nextflow/util/Thre …

Use unbound queue for transfer thread pool

---

docs/reference/process.md
modules/nextflow/src/main/groovy/nextflow/processor/TaskArrayCollector.groovy

This PR fixes the usage of `conda` directive with task arrays. 
Solves #5694

Fix Conda directive is not honoured by task array

---

docs/reference/channel.md

Changes:
- Updates docs, adding a note to document watchPath incompatibility with cloud URIs.

 Add note to document watchPath incompatibility with cloud URIs

---

docs/process.md

In the "script" section there was a tip recommending to use the `shell` directory, however as that has been deprecated the tip confusing.

Remove tip about shell block

---

docs/reference/cli.md

Just a note from my backlog. Clarify that `-C` and `-c` can be a comma-separated list of files.

Improve documentation of CLI options for specifying config files

---

docs/process.md
docs/reference/syntax.md

Close #5680 
Provide some explicit examples of function calls with only named args, to show that no comma is required. Several people have been confused by this with the `stdout` directive.

Document examples of directives with only named args

---

docs/reference/config.md

Close #5095 
This config option was documented incorrectly: https://github.com/nextflow-io/nextflow/blob/8a714a4b90eac1a1209ec15c6930c301e6572175/modules/nextflow/src/main/groovy/nextflow/executor/GridTaskHandler.groovy#L149
This PR updates the docs to match the code. Alternatively, we could update the code to match the docs.

Fix docs for `executor.submit.retry.reason` config option

---

modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy

Close #5446 
During a stub run, the stub flag is added to a task hash even if the specific process doesn't have a stub section. When a process doesn't have a stub section, it is executed normally. Therefore, the stub flag shouldn't be added in that case.

Add stub flag to task hash only if task has a stub

---

Makefile

Move `compile` to the top of the Makefile so that `make` equates to `make compile` instead of `make clean`

Change the default make rule to `compile`

---

plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy
plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzJobKey.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzBatchServiceTest.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzJobKeyTest.groovy

context: https://nextflow.slack.com/archives/C02T98A23U7/p1738748591243169
Processes could not be submitted to different queues on Azure Batch because the logic looked for an existing job/pool before submitting and didn't check the queue details. This includes the pool ID so that it will now submit to different queues based on user configuration.
You can test it with the following main.nf:
```
process ECHO {
queue { if (a == "a") "my_test_pool_1" else if (a == "b") "my_test_pool_2" else "my_test_pool_3" }
container "ubuntu:2204"
input:
val a
output:
tuple val("sampleId"), val(a)
script:
"""
echo "a: ${a}"
"""
}
workflow {
Channel.of("a", "b", "c")
| ECHO
| view
}
```
and nextflow.config (with credentials and details redacted):
```
azure {
batch {
copyToolInstallMode = 'node' …
```

feat(AzBatchService): Allow Azure Batch tasks to be submitted to different pools 

---

docs/reference/config.md
modules/nextflow/src/main/groovy/nextflow/Session.groovy

This PR disable the work dir clean-up when using a remote object storage since this capability is not supported.

Disable cleanup on remote work dir

---

plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy
plugins/nf-google/src/main/nextflow/cloud/google/batch/client/BatchClient.groovy
plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchTaskHandlerTest.groovy
plugins/nf-google/src/test/nextflow/cloud/google/batch/client/BatchClientTest.groovy

This PR is an alternative to process task status in task arrays. 
In the current status, every time that getTaskState is called, we perform two calls to the Google Batch client, one to retrieve the list of tasks(`listTasks`) and another to get the task state (`getTaskStatus`). This second call is problematic because it generates the NotFoundException and it is also redundant because the first call already provides the task descriptions including their states.
The BatchClient has a HashMap as a cache of array task status. A new method is created to retrieve the status of a task belonging to a task array. Instead of making the call to the Google Batch API, it checks the status in the cache. When the status is not in the cache or is outdated, the `listTasks` method is called to update all …

Alternative for managing task array status in Google Batch

---

modules/nextflow/src/main/groovy/nextflow/processor/TaskArrayCollector.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskRun.groovy
modules/nextflow/src/test/groovy/nextflow/processor/TaskArrayCollectorTest.groovy
modules/nextflow/src/test/groovy/nextflow/processor/TaskProcessorTest.groovy
plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy

This PR tries to avoid the use of side-effect to change the state of `TaskRun.isChild` field. 
Overall logic: 
1. set the field only when `createTaskArray` is invoked 
2. when a task is retried reset the attribute in the `TaskRun.clone` method
3. skip the `TaskArrayCollector` when it's a task retry in any case

Task array improve

---

modules/nextflow/src/main/groovy/nextflow/processor/TaskHandler.groovy
plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchScriptLauncher.groovy
plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy

Close #5777 
This PR modifies the execution command for task arrays to directly run the task command avoiding race conditions when using gcfuse.

Change task array submission commad in  Google Batch

---

plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzBatchServiceTest.groovy

The Azure Batch task did not include the `--cpu-shares` or `--memory` options of the docker run command, meaning resource allocation was only controlled by slots on the node. This PR introduces the additional options to the container run command, including `--cpu-shares` and `--memory`. The behaviour will now be more similar to AWS Batch which includes a soft limit on CPUs and hard limit on memory.

feat(AzBatchService): Include cpu-shares and memory in docker run command

---

modules/nextflow/src/main/groovy/nextflow/ast/VariableVisitor.groovy
modules/nextflow/src/test/groovy/nextflow/ast/NextflowDSLImplTest.groovy

Close #804 
Test case:
```groovy
process VariableTesting {
input:
val foo
exec:
if( foo[0] == "a" )
log.info "Found an A"
def bar = foo.find { it == "d" }
}
workflow {
inputs = Channel.from(["a", "b", "c"], ["d", "e", "f"])
inputs | VariableTesting
}
```
Currently it fails with:
```
Script compilation error
- file : /path/to/main.nf
- cause: Variable `foo` already defined in the process scope @ line 28, column 15.
def bar = foo.find {
^
1 error
```
This is because the variable visitor was treating the `foo` in `foo.find` as a re-declaration of `foo` rather than merely a reference to it

Fix false error in variable visitor

---

docs/azure.md
plugins/nf-azure/src/main/nextflow/cloud/azure/config/AzPoolOpts.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/batch/AzBatchServiceTest.groovy
plugins/nf-azure/src/test/nextflow/cloud/azure/config/AzureConfigTest.groovy
validation/azure.config

This PR bumps Ubuntu 22.04 as default SKU for Azure Batch node pools. This is required because Ubuntu 20.04 is going to be retired by April 2025 (See below):
> Support for Ubuntu 20.04 LTS for Azure Batch pools will be retired on 23 April 2025
You're receiving this notice because you're currently using either an Ubuntu 20.04 LTS Marketplace or derived image with Azure Batch pools subject to support end of life.
> 
> Azure Batch typically follows standard end of life timelines set by publishers for supported images from the Azure Marketplace. Ubuntu 20.04 LTS is reaching the end of standard support life. Batch pools with Ubuntu 20.04 LTS VM images and the Batch node agent SKU batch.node.ubuntu 20.04 will no longer be supported in Batch after 23 April 2025.

Bump ubuntu 22.04 as default SKU for Azure Batch

---

modules/nextflow/src/main/groovy/nextflow/extension/PublishOp.groovy
modules/nextflow/src/test/groovy/nextflow/script/OutputDslTest.groovy

Close #5808 
@jorgee I'm gonna start requesting your review for some small bug fixes like this to relieve Paolo a bit

Fix dynamic publish path

---

docs/container.md

"paths are configure" > "paths are configured"

Typo fix in container.md

---

plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy
plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchTaskHandlerTest.groovy

close #5827 
The autoretry exit code set in the google Batch Job request was hardcoded to the default value. This branch fixes it, setting the codes specified in the configuration.

Fix Google Batch autoRetryExitCodes bug

---

tests/checks/fusion-symlink.nf/.checks
tests/checks/fusion-symlink.nf/.config

The `fusion-symlink.nf` fails randomly due to what looks like a race condition. Since it was impossible to reproduce the problem in the a controlled environment, we are slightly modifying the test in an attempt to better diagnose the problem. To this end, this PR
extends the `fusion-symlink.nf` in two ways:
1. We add a retry protocol with an exponential backoff to the `nextflow fs cp [...]` commands used for validating the published data. The idea is that if there's indeed a race condition between the publishing and the validation, retrying the validation should eventually succeed. We ensure the test still fails so that we may detect when the potential race condition occurs.
2. If the error is not a publish/validation race condition, we still want to capture as much information from the …

ci: Improve `fusion-symlink.nf` test

---

modules/nextflow/src/main/groovy/nextflow/Session.groovy
modules/nextflow/src/main/groovy/nextflow/cli/CmdCid.groovy
modules/nextflow/src/main/groovy/nextflow/data/cid/CidObserver.groovy
modules/nextflow/src/main/groovy/nextflow/data/cid/CidStoreFactory.groovy
modules/nextflow/src/main/groovy/nextflow/data/config/DataConfig.groovy
modules/nextflow/src/main/groovy/nextflow/trace/DefaultObserverFactory.groovy
modules/nextflow/src/test/groovy/nextflow/cli/CmdCidTest.groovy
modules/nextflow/src/test/groovy/nextflow/data/cid/CidObserverTest.groovy
modules/nextflow/src/test/groovy/nextflow/data/config/DataConfigTest.groovy

This PR double the CID store from the Session object. Tests needs to be fixed.

Decouple cid store from session

---

docs/process.md

- Move the explanations of `arity` to more appropriate subsections
- Use "arity" instead of "cardinality" in the table explaining how multiple input files are staged

Improve docs for process path input/output arity

---

docs/reference/config.md

There was an additional config option for azure.managedIdentity which wasn't used anywhere. It probably crept in during development with the previous version of the SDK. We sshould remove it to prevent confusion.
Signed-off-by: adamrtalbot <12817534+adamrtalbot@users.noreply.github.com>
Hi! Thanks for contributing to Nextflow.
When submitting a Pull Request, please sign-off the DCO [1] to certify that you are the author of the contribution and you adhere to Nextflow's open source license [2] by adding a `Signed-off-by` line to the contribution commit message. See [3] for more details.
1. https://developercertificate.org/
2. https://github.com/nextflow-io/nextflow/blob/master/COPYING
3. https://github.com/apps/dco

fix: Remove azure.managedIdentity.tenantId which was not valid

---

docs/developer/plugins.md
docs/working-with-files.md

Document custom filesystems as a plugin extension point as described [here](https://youtu.be/Pn_B2cI62_o?si=oBfwprTD0HIUKG7F&t=348)

Document plugin filesystems

---

plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsS3Config.groovy
plugins/nf-amazon/src/test/nextflow/cloud/aws/config/AwsS3ConfigTest.groovy

This PR consider AWS china as a custom endpoint to prevent the use of default AWS global endpoint in some operations. 
Closes https://github.com/nextflow-io/nextflow/issues/5836

Consider AWS china as custom endpoint

---

docs/process.md
modules/nextflow/src/main/groovy/nextflow/container/ContainerBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/container/DockerBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/container/PodmanBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/container/resolver/ContainerResolver.groovy
modules/nextflow/src/main/groovy/nextflow/container/resolver/ContainerResolverProvider.groovy
modules/nextflow/src/main/groovy/nextflow/container/resolver/DefaultContainerResolver.groovy
modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskBean.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskConfig.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskRun.groovy
modules/nextflow/src/test/groovy/nextflow/container/DockerBuilderTest.groovy
modules/nextflow/src/test/groovy/nextflow/container/PodmanBuilderTest.groovy
modules/nextflow/src/test/groovy/nextflow/executor/BashWrapperBuilderTest.groovy
modules/nextflow/src/test/groovy/nextflow/processor/TaskConfigTest.groovy
modules/nextflow/src/test/groovy/nextflow/processor/TaskRunTest.groovy
modules/nf-commons/src/main/nextflow/util/SysHelper.groovy
plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveClient.groovy
plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveFactory.groovy
plugins/nf-wave/src/main/io/seqera/wave/plugin/resolver/WaveContainerResolver.groovy
plugins/nf-wave/src/test/io/seqera/wave/plugin/WaveClientTest.groovy
plugins/nf-wave/src/test/io/seqera/wave/plugin/WaveFactoryTest.groovy
plugins/nf-wave/src/test/io/seqera/wave/plugin/resolver/WaveContainerResolverTest.groovy
plugins/nf-wave/src/test/nextflow/processor/TaskRunTest2.groovy

This PR improves the handling of container platform in two ways: 
* Add explicitly the platform to be used to Docker and Podman commands. This is needed to solve the ambiguity on some OS (e.g. macOS) where a container can be executed both as ARM (using silicon) and AMD (via emulation) 
* Default to `linux/amd64` when no `process.arch` is specified for consistency with Wave defaults.

Add container platform to docker command

---

docs/channel.md

This PR simplifies the operator summary further to emphasize the "core" set of operators. This core set covers the entire functionality of the operator library, instead of the categories like "filtering" and "transforming" which aren't very helpful. Many of the linked operators already have "see also" links in their respective sections to suggest alternatives where appropriate.

Improve operator summary

---

modules/nextflow/src/main/groovy/nextflow/script/IncludeDef.groovy

This PR fixes a regression caused by #4613 .
The strict syntax requires some new include logic because it includes modules in a slightly different way. My original change was minimal but had a side-effect on the v1 script loader. So I went back and separated the logic more explicitly.
This change is easy to confirm with sarek:
```bash
make pack
./build/releases/nextflow-25.02.0-edge-dist inspect nf-core/sarek -r 3.4.2
```

Fix false "process already defined" error

---

docs/updating-syntax.md

Not totally clear, especially as other feature toggles use things like `nextflow.enable` within scripts. Better to be explicit.

Docs: Specify that `NXF_SYNTAX_PARSER` is an environment variable.

---

modules/nf-lang/src/main/antlr/ConfigParser.g4
modules/nf-lang/src/main/antlr/ScriptParser.g4
modules/nf-lang/src/main/java/nextflow/config/parser/ConfigAstBuilder.java
modules/nf-lang/src/main/java/nextflow/script/ast/ASTNodeMarker.java
modules/nf-lang/src/main/java/nextflow/script/ast/ASTUtils.java
modules/nf-lang/src/main/java/nextflow/script/ast/ProcessNode.java
modules/nf-lang/src/main/java/nextflow/script/ast/WorkflowNode.java
modules/nf-lang/src/main/java/nextflow/script/control/ResolveVisitor.java
modules/nf-lang/src/main/java/nextflow/script/control/ScriptToGroovyVisitor.java
modules/nf-lang/src/main/java/nextflow/script/control/TypeCheckingVisitor.java
modules/nf-lang/src/main/java/nextflow/script/control/VariableScopeVisitor.java
modules/nf-lang/src/main/java/nextflow/script/formatter/Formatter.java
modules/nf-lang/src/main/java/nextflow/script/parser/ScriptAstBuilder.java
modules/nf-lang/src/main/java/nextflow/script/types/TypeChecker.java
modules/nf-lang/src/main/java/nextflow/script/types/Types.java

- Add basic type checking utilities from language server
- Cleanup implicit declaration analysis
- Cleanup process/workflow output name checking

nf-lang: Add type checking utils

---

modules/nextflow/src/main/groovy/nextflow/cli/CmdFormat.groovy
modules/nextflow/src/main/groovy/nextflow/cli/CmdLint.groovy
modules/nextflow/src/main/groovy/nextflow/script/parser/v2/ScriptLoaderV2.groovy
modules/nf-lang/src/main/java/nextflow/util/PathUtils.java

Nicer output from the new `nextflow format` and `nextflow lint` commands. @bentsherman you will probably want to clean up my crappy Groovy code, but I'm happy with the outputs now.
TODO:
https://github.com/user-attachments/assets/a44a7049-689c-4e49-a953-16198f1963af
https://github.com/user-attachments/assets/c73fc2bb-8f09-4125-99e1-86d985d572ae

Fancy ANSI formatting for `lint` and `format` log outputs

---

modules/nextflow/src/main/groovy/nextflow/dag/DAG.groovy
modules/nextflow/src/main/groovy/nextflow/dag/MermaidRenderer.groovy

Fix and improve the corrupted export of DAGs in the mermaid format.
Fix issue #5855.
The issue comes from the way the _key_ of the hierarchical subgraphs for operators are inferred in the mermaid DAG printer.
Unlike regular process, the DAG given to the printer does not contain the complete hierarchical path (i.e. the _key_) to the channel operators. Because of this, the printer attempts to recover this information automatically prior to printing the subgraph, so as to print operators in the scope they were originally declared. 
The current version of the code fails to recover the correct subgraphs in many situations, as it assumes that:
* All interconnected channel operators share the same subgraph.
* The subgraph associated to a (group of) channel operator is an input (or output) …

Mermaid DAG export: Fix operator infer subgraph key

---

modules/nextflow/src/main/groovy/nextflow/ast/NextflowDSLImpl.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskConfig.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy
modules/nextflow/src/main/groovy/nextflow/script/IncludeDef.groovy
modules/nextflow/src/test/groovy/nextflow/processor/TaskConfigTest.groovy

We deprecated several language features since 24.10:
- include `addParams`
- Process `when` section
- Process `shell` section
Some users find these warnings intrusive, and users who run pipelines but don't write Nextflow are confused to receive a warning even though the pipeline still works correctly.
This PR makes these warnings less intrusive by ensuring that they are logged only once per run instead of once per occurrence.

Improve deprecation warnings

---

modules/nf-httpfs/src/test/nextflow/file/http/HttpFilesTests.groovy
modules/nf-httpfs/src/test/nextflow/file/http/XFileSystemProviderTest.groovy
plugins/nf-tower/src/test/io/seqera/tower/plugin/TowerFusionEnvTest.groovy

This should prevent an occasional `java.net.BindException` when running the tests locally, caused by two tests trying to start WireMock on the same port.

Allow WireMock to select a random port in tests

---

docs/reference/config.md
modules/nextflow/src/main/groovy/nextflow/fusion/FusionConfig.groovy
modules/nextflow/src/test/groovy/nextflow/fusion/FusionConfigTest.groovy
modules/nf-lang/src/main/java/nextflow/config/scopes/FusionConfig.java
plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchTaskHandler.groovy
plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsOptions.groovy
plugins/nf-amazon/src/main/nextflow/cloud/aws/config/AwsBatchConfig.groovy
plugins/nf-amazon/src/test/nextflow/cloud/aws/batch/AwsBatchTaskHandlerTest.groovy
plugins/nf-amazon/src/test/nextflow/cloud/aws/config/AwsBatchConfigTest.groovy
plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveClient.groovy
plugins/nf-wave/src/test/io/seqera/wave/plugin/WaveClientTest.groovy

This PR adds support for Fusion snapshots by adding a config setting: 
```
fusion.snapshots=true|false
```
When enabled Fusion snapshots restores automatically AWS Batch jobs interrupted by a spot reclamation. 
The number of restarts is determined by the setting `aws.batch.maxSpotAttempts` (default `5` when Fusion Snapshots is enabled)

Add support for Fusion Snapshots

---

modules/nextflow/src/main/groovy/nextflow/executor/ExecutorFactory.groovy

A user in Slack reported that this warning was being repeated for every task of a certain process, leading to 1000s of repeated warnings hogging the console output. This warning only needs to be logged once per process

Fix repeated warning for local executor

---

modules/nextflow/src/main/groovy/nextflow/trace/TraceObserver.groovy

This PR refactor the `TraceObserver` from a trait to a interface + defaults methods. 
This should solve backward incompatibilities problem when adding the methods to the observer as reported here https://github.com/nextflow-io/nf-schema/issues/90

Refactor TraceObserver as interface

---

docs/process.md
docs/updating-syntax.md

Update the shell block deprecation notices to recommend the strict syntax instead of the VS Code extension. This way it is less intrusive as a suggestion to users who don't use VS Code (based on user feedback).

Update shell block deprecation notice

---

modules/nextflow/src/main/groovy/nextflow/script/WorkflowBinding.groovy
modules/nf-lang/src/main/java/nextflow/script/control/ScriptToGroovyVisitor.java
tests/checks/output-dsl.nf/.checks
tests/output-dsl.nf

- Fix false error when publishing a ChannelOut with only one channel
- Fix compiler bug when output `path` directive is specified without a closure
- Update `output-dsl.nf` to test these cases

Fix bugs in workflow outputs

---

docs/reference/config.md

Searching for "poll" did not find `executor.pollInterval`. Adding "poll" to the description makes it findable.
cc @kenibrewer

Make executor.pollInterval findable.

---

docs/reference/config.md
modules/nf-lang/src/main/java/nextflow/config/scopes/GoogleBatchConfig.java
plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchScriptLauncher.groovy
plugins/nf-google/src/main/nextflow/cloud/google/batch/client/BatchConfig.groovy
plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchScriptLauncherTest.groovy

This PR adds the `google.batch`gcsfuseOptions` to fine control the mount settings when using [gcsfuse](https://cloud.google.com/storage/docs/cloud-storage-fuse/overview) with Google Batch

Add Google Batch gcsfuseOptions

---

docs/reference/stdlib.md
docs/reference/syntax.md
modules/nf-lang/src/main/java/nextflow/config/parser/ConfigAstBuilder.java
modules/nf-lang/src/main/java/nextflow/script/dsl/ScriptDsl.java
modules/nf-lang/src/main/java/nextflow/script/formatter/Formatter.java
modules/nf-lang/src/main/java/nextflow/script/parser/ScriptAstBuilder.java
modules/nf-lang/src/test/groovy/nextflow/script/formatter/ScriptFormatterTest.groovy

This PR adds more unit tests for formatting statements and expressions (and fixes a few bugs I found along the way)
As a bonus it also tests that these code snippets are parsed correctly
From now on, if someone reports a parsing/formatting bug, we need only add a regression test to this test suite

nf-lang: Add unit tests for formatting

---

docs/index.md
docs/reference/syntax.md

Spun out from our discussion in #5993 
@christopher-hakkaart I think this split is a good improvement over the current section, even if it's not perfect. It also creates some space for future expansions like a "runtime API" or CLI v2.
Also make a few small edits on the syntax page that I noticed after the split

Separate language and runtime reference docs

---

docs/developer/plugins.md
docs/workflow.md
modules/nextflow/src/main/groovy/nextflow/Session.groovy
modules/nextflow/src/main/groovy/nextflow/extension/PublishOp.groovy
modules/nextflow/src/main/groovy/nextflow/processor/PublishDir.groovy
modules/nextflow/src/main/groovy/nextflow/trace/TraceObserver.groovy
modules/nextflow/src/main/groovy/nextflow/trace/TraceObserverFactory.groovy
modules/nextflow/src/main/groovy/nextflow/trace/TraceObserverFactoryV2.groovy
modules/nextflow/src/main/groovy/nextflow/trace/TraceObserverV2.groovy
modules/nextflow/src/main/groovy/nextflow/trace/event/FilePublishEvent.groovy
modules/nextflow/src/main/groovy/nextflow/trace/event/TaskEvent.groovy
modules/nextflow/src/main/groovy/nextflow/trace/event/WorkflowOutputEvent.groovy
modules/nextflow/src/test/groovy/nextflow/SessionTest.groovy
modules/nextflow/src/test/groovy/nextflow/script/OutputDslTest.groovy
modules/nf-lang/src/main/java/nextflow/script/dsl/OutputDsl.java
modules/nf-lineage/src/main/nextflow/lineage/LinObserver.groovy
modules/nf-lineage/src/test/nextflow/lineage/LinObserverTest.groovy

- Add new TraceObserverV2 interface, replacing method overloads with custom event types
- Revert TraceObserver to be compatible with Nextflow 24.10
- Update Session to accept v1 and v2 trace observers
- Update lineage observer to use TraceObserverV2
- Fix issues with workflow output annotations
TODO:

Trace observer v2

---

docs/reference/operator.md

Fix typo docs splitFastq

---

docs/reference/config.md

Based on a request from a user who was dealing with AWS connection timeout errors

Document default values for `aws.client` config settings

---

docs/migrations/25-04.md
docs/reference/channel.md
docs/reference/feature-flags.md
docs/reference/syntax.md
modules/nextflow/src/main/groovy/nextflow/Channel.groovy
modules/nextflow/src/main/groovy/nextflow/NF.groovy
modules/nextflow/src/main/groovy/nextflow/NextflowMeta.groovy
modules/nf-lang/src/main/java/nextflow/script/dsl/FeatureFlagDsl.java
tests/topic-channel.nf

This PR brings topic channels out of preview, making them a first-class language feature that can be used without a feature flag.

Bring topic channels out of preview

---

modules/nextflow/src/main/groovy/nextflow/cli/CmdLineage.groovy
modules/nextflow/src/test/groovy/nextflow/cli/CmdLineageTest.groovy

This PR fixes a bug when checking the number of parameters in the `lineage find` command. It was not updated with the latest changes

Data lineage fix find command arguments check

---

modules/nextflow/src/main/groovy/nextflow/cli/CmdLineage.groovy
modules/nf-lineage/src/main/nextflow/lineage/LinObserver.groovy
modules/nf-lineage/src/main/nextflow/lineage/LinUtils.groovy
modules/nf-lineage/src/main/nextflow/lineage/cli/LinCommandImpl.groovy
modules/nf-lineage/src/main/nextflow/lineage/exception/OutputRelativePathException.groovy
modules/nf-lineage/src/test/nextflow/lineage/LinObserverTest.groovy
modules/nf-lineage/src/test/nextflow/lineage/LinUtilsTest.groovy
modules/nf-lineage/src/test/nextflow/lineage/cli/LinCommandImplTest.groovy

This PR includes some fixes about how the data lineage module works when there aren't outputs.
- Do not write the `#outputs` entry if there aren't workflow outputs
- lineage `view` command returns an empty list if there aren't workflow outputs
Other minor fixes:
- Fixes the return of fragment including empty lists
- Rename `LinCommand` methods `log` and `describe` to `list` and `view` and subclasses `CmdLog `and `CmdDescribe` to CmdList and CmdView

Data Lineage workflow outputs fixes

---

docs/reference/env-vars.md
modules/nf-commons/src/main/nextflow/plugin/PluginsFacade.groovy
modules/nf-commons/src/test/nextflow/plugin/PluginsFacadeTest.groovy

This adds the ability to define a list of allowed plugins that can be used by nextflow by using the env variable `NXF_PLUGINS_ALLOWED` specified a comma separate list of plugin IDs that can be used. For example 
```
NXF_PLUGINS_ALLOWED=nf-amazon,nf-google
```
Only the amazon and google plugins can be used 
```
NXF_PLUGINS_ALLOWED='' 
``` 
Empty string means no plugin is allowed

Add allowed plugins list

---

modules/nf-lang/src/main/java/nextflow/script/control/ScriptParser.java

Fixes an error that was found by linting the entire nf-core modules repo:
```bash
git clone https://github.com/nf-core/modules
cd modules
nextflow lint -output full modules/nf-core/**/main.nf | tee lint.log
```
The root cause is that `ScriptParser` iterates over the compiler sources while adding new sources via `ModuleResolver`

Fix concurrent modification error in `lint` command

---

modules/nf-lineage/src/main/nextflow/lineage/DefaultLinHistoryLog.groovy
modules/nf-lineage/src/main/nextflow/lineage/LinHistoryLog.groovy
modules/nf-lineage/src/main/nextflow/lineage/LinObserver.groovy
modules/nf-lineage/src/test/nextflow/lineage/DefaultLinHistoryLogTest.groovy
modules/nf-lineage/src/test/nextflow/lineage/LinObserverTest.groovy

This PR includes
- `LinHistoryLog` was only considering the session id to write the lineage log entry. Now, it also uses the run name.
- Sort the script files in workflow description to facilitate the diff between executions

Data Lineage quick fixes

---

modules/nextflow/src/main/groovy/nextflow/processor/TaskConfig.groovy
modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy
modules/nf-lang/src/main/java/nextflow/script/dsl/FeatureFlagDsl.java
modules/nf-lang/src/main/java/nextflow/script/dsl/ProcessDsl.java
modules/nf-lang/src/main/java/nextflow/script/dsl/WorkflowDsl.java
modules/nf-lang/src/main/java/nextflow/script/types/Channel.java

Removes the runtime warnings for `shell` and `when` deprecations. This way, non-developer users won't be spooked by these warnings, while developers will receive this warning from the linter / language server.
Also removed some spurious deprecations that I added in the first iteration of the language server. Things like `each` and `merge` don't need to be called out specifically because we'll just introduce static types and v2 operators instead.

Remove extraneous deprecation warnings

---

modules/nextflow/src/test/groovy/nextflow/cli/CmdLineageTest.groovy
modules/nf-lineage/src/main/nextflow/lineage/cli/LinCommandImpl.groovy
modules/nf-lineage/src/main/nextflow/lineage/cli/LinDagRenderer.groovy
modules/nf-lineage/src/test/nextflow/lineage/cli/LinCommandImplTest.groovy

This PR makes the following improvements to the lineage diagram:
- Move render code to separate class
- Separate graph traversal from Mermaid rendering
- Distinguish task nodes from file nodes
I also removed the rendering of WorkflowRun nodes, because workflow runs are more like boundaries around nodes rather than nodes. We can try to add them later as subgraphs but for now I don't think it's important. We do need to make sure that the lineage can still be traced across multiple workflow runs.
Example lineage graph for the multiqc report produced by rnaseq-nf:
```mermaid
%%{
init: {
'theme': 'base',
'themeVariables': {
'primaryColor': '#B6ECE2',
'primaryTextColor': '#160F26',
'primaryBorderColor': '#065647',
'lineColor': '#545555',
'clusterBkg': '#BABCBD22',
'clusterBorder': '#DDDEDE', …
```

Improve lineage diagram

---

modules/nextflow/src/main/groovy/nextflow/config/parser/v2/ConfigParserV2.groovy
modules/nextflow/src/main/groovy/nextflow/scm/AssetManager.groovy

Close #6027 
When the asset manaager parses a config file as raw text, config includes are automatically disabled, and compilation errors are not printed, since they don't have filename information.
I also changed the asset manager's exception to a warning, so that the runtime proceeds to parse the config file like normal and prints the actual error messages. Otherwise, you would never see config errors because it would always be short-circuited by the asset manager.

Make config parser v2 compatible with AssetManager

---

docs/process.md
docs/strict-syntax.md

Follow-up to #6055 . The following deprecation warnings have been demoted to "best practice recommendations:
- Using `params` outside the entry workflow
- Implicit closure `it` parameter
- Process `when` section
The language server will highlight these patterns as blue instead of yellow to indicate the decreased urgency.
Some of these patterns will become deprecated as part of static types, but there is no need to warn about them right now. Just trying to keep the set of strict errors/warnings as focused as possible.

Refactor deprecations as best practices

---

modules/nf-lineage/src/main/nextflow/lineage/DefaultLinStore.groovy
modules/nf-lineage/src/main/nextflow/lineage/LinStore.groovy
modules/nf-lineage/src/main/nextflow/lineage/LinUtils.groovy
modules/nf-lineage/src/main/nextflow/lineage/fs/LinFileSystemProvider.groovy
modules/nf-lineage/src/main/nextflow/lineage/fs/LinIntermediatePath.groovy
modules/nf-lineage/src/main/nextflow/lineage/fs/LinMetadataPath.groovy
modules/nf-lineage/src/main/nextflow/lineage/fs/LinPath.groovy
modules/nf-lineage/src/test/nextflow/lineage/DefaultLinStoreTest.groovy
modules/nf-lineage/src/test/nextflow/lineage/LinUtilsTest.groovy
modules/nf-lineage/src/test/nextflow/lineage/fs/LinFileSystemProviderTest.groovy
modules/nf-lineage/src/test/nextflow/lineage/fs/LinPathTest.groovy

In the current version, patterns can be used for subpaths of a `FileOutput`. For instance, if a workflow publishes `lid://abscd364/samples/quant`, a user can use the `fromPath` factory to get all the files in this folder.
```
channel.formPath(“lid://abscd364/samples/quant/*”)
```
However, it can’t be used in the parent paths of the `FileOutput` such as:
```
channel.formPath(“lid://abscd364/samples/*/*.sf”)
```
This PR allows to use this kind of patterns in fromPath with lid paths

Support fromPath with pattern in Lineage Pseudo-FS

---

docs/updating-nextflow.md

Discovered this issue while trying to self-update from 25.03 edge to 25.04

Document required `NXF_EDGE=0` when updating from edge to stable

---

modules/nextflow/src/main/groovy/nextflow/conda/CondaCache.groovy
modules/nextflow/src/test/groovy/nextflow/conda/CondaCacheTest.groovy

Fixes #5947
Tested with the example from that issue.

Remove obsolete conda create --mkdir option

---

modules/nf-lang/src/main/java/nextflow/config/control/VariableScopeVisitor.java
modules/nf-lang/src/test/groovy/nextflow/config/control/ConfigResolveTest.groovy

This PR fixes two issues with variable checking in config files:
- Issue with variable declarations reported in Slack: https://nextflow.slack.com/archives/C02TPSL19UJ/p1747399972745699?thread_ts=1747318132.936939&cid=C02TPSL19UJ
- Issue with dynamic config directives -- they can reference process inputs, which are not known during config parsing

Fix variable checking in v2 config parser

---

modules/nextflow/src/main/resources/nextflow/executor/command-trace.txt
modules/nextflow/src/test/resources/nextflow/executor/test-bash-wrapper-with-trace.txt

close #6090 
This PR forces the overwrite of .command.trace to avoid the error writting the trace file when `bash -C ` (noclobber) is set in `process.shell`

Force overwritting to trace file

---

docs/reference/config.md
modules/nf-lang/src/main/java/nextflow/config/scopes/K8sConfig.java
modules/nf-lang/src/main/java/nextflow/config/scopes/K8sRetryConfig.java
plugins/nf-k8s/src/main/nextflow/k8s/K8sConfig.groovy
plugins/nf-k8s/src/main/nextflow/k8s/client/ClientConfig.groovy
plugins/nf-k8s/src/main/nextflow/k8s/client/K8sClient.groovy
plugins/nf-k8s/src/main/nextflow/k8s/client/K8sRetryConfig.groovy
plugins/nf-k8s/src/test/nextflow/k8s/K8sConfigTest.groovy

close #5829 
This PR replace the failure mechanism by `FailSafe` retry mechanism used in other parts in the code base.
Replace the current config `k8s.maxErrorRetry` with `k8s.retryPolicy`

Add Failsafe retry mechanism in K8s

---

build.gradle
modules/nextflow/build.gradle
modules/nf-commons/build.gradle
modules/nf-httpfs/build.gradle
modules/nf-lang/build.gradle
modules/nf-lineage/build.gradle
plugins/nf-amazon/build.gradle
plugins/nf-azure/build.gradle
plugins/nf-cloudcache/build.gradle
plugins/nf-codecommit/build.gradle
plugins/nf-console/build.gradle
plugins/nf-google/build.gradle
plugins/nf-k8s/build.gradle
plugins/nf-tower/build.gradle
plugins/nf-wave/build.gradle

This PR bumps groovy to version 4.0.27

Bump Groovy to version 4.0.27

---

docs/reference/stdlib-types.md

Close #6012 
Document the different between `in` and `containsKey` for maps.
See also: https://groovy-lang.org/semantics.html#the-groovy-truth

Fix documentation of Map `in` operator

---

modules/nextflow/src/main/groovy/nextflow/scm/LocalRepositoryProvider.groovy
modules/nextflow/src/main/groovy/nextflow/scm/RepositoryProvider.groovy
plugins/nf-codecommit/src/main/nextflow/cloud/aws/codecommit/AwsCodeCommitRepositoryProvider.groovy

This PR changes the signature of `RepositoryProvider.readBytes` to public

Make RepositoryProvider readBytes public

---

docs/aws.md

The recommended AWS AMI (AL2023) no longer contains `amazon-linux-extras`
See:
https://docs.aws.amazon.com/linux/al2/ug/prepare-for-al2023.html
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-docker.html
https://docs.aws.amazon.com/batch/latest/userguide/create-batch-ami.html

Upgrade AWS instructions to AL2023

---

modules/nextflow/src/main/groovy/nextflow/scm/AzureRepositoryProvider.groovy
modules/nextflow/src/main/groovy/nextflow/scm/GiteaRepositoryProvider.groovy
modules/nextflow/src/main/groovy/nextflow/scm/GitlabRepositoryProvider.groovy
modules/nextflow/src/main/groovy/nextflow/scm/RepositoryProvider.groovy
modules/nextflow/src/test/groovy/nextflow/scm/GithubRepositoryProviderTest.groovy
modules/nextflow/src/test/groovy/nextflow/scm/RepositoryProviderTest.groovy

This PR replaces the HttpURLConnection with HttpClient provided by Java 11 and later. 
This allows a more final control on HTTP settings (e.g. virtual threads pool) and response error status (and retries)

Replace URLConnection with HttpClient

---

docs/reference/process.md

In the `### maxSubmitAwait` subsection, it originally read:
`queue "${task.submitAttempt==1 : 'spot-compute' : 'on-demand-compute'}"`
I believe this should be a standard ternary operator:
`queue "${task.submitAttempt==1 ? 'spot-compute' : 'on-demand-compute'}"`
(Note a colon has changed to a question mark)

typo correction for ternary operator

---

docs/reference/config.md
docs/reference/env-vars.md
modules/nextflow/src/main/groovy/nextflow/processor/PublishDir.groovy
modules/nextflow/src/main/groovy/nextflow/scm/AssetManager.groovy
modules/nextflow/src/main/groovy/nextflow/scm/AzureRepositoryProvider.groovy
modules/nextflow/src/main/groovy/nextflow/scm/RepositoryProvider.groovy
modules/nextflow/src/main/groovy/nextflow/util/ConfigHelper.groovy
modules/nextflow/src/main/groovy/nextflow/util/RetryConfig.groovy
modules/nextflow/src/test/groovy/nextflow/scm/RepositoryProviderTest.groovy
modules/nextflow/src/test/groovy/nextflow/util/ConfigHelperTest.groovy
modules/nextflow/src/test/groovy/nextflow/util/RetryConfigTest.groovy

This pull request introduces a significant refactor and enhancement of the retry policy mechanism across the codebase, aiming to standardize and centralize its configuration and usage. The changes include the migration of retry policy settings to a new `RetryConfig` class, updates to the documentation, and modifications to several classes to adopt the new retry mechanism.
* Migrated retry policy settings from `workflow.output.retryPolicy` to `nextflow.retryPolicy` in the configuration, and updated relevant documentation in `docs/reference/config.md`. Added details about new retry policy parameters like `delay`, `jitter`, `maxAttempts`, and `maxDelay`. [[1]](diffhunk://#diff-9ae244d0598c1cc7efc9875baf25a5f8b4bc13aabad4fbe17dd4bc5cfe856909L1185-R1204) …

Implement retry strategy for Git repository provider

---

plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchScriptLauncher.groovy
plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchExecutorTest.groovy

This pull request updates the behavior of the trap command in the Google Batch Script Launcher and its corresponding test case. The trap now triggers on `EXIT` instead of `ERR` to ensure cleanup actions are performed regardless of whether the script exits successfully or with an error.
Updates to trap command behavior:
* [`plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchScriptLauncher.groovy`](diffhunk://#diff-5a492f3bd48a2f68ae819fa4efb2b7fb874732c0b8e720a09bbadfecbc547d00L207-R207): Changed the trap command in the `launchCommand` method to trigger on `EXIT` instead of `ERR`, ensuring log copying occurs on any script termination.
* [`plugins/nf-google/src/test/nextflow/cloud/google/batch/GoogleBatchExecutorTest.groovy`](diffhunk://#diff-1d010711c5150855d148651e42268e45ab …

Upload Google Batch log on task exit

---

docs/reference/config.md

Minor formatting bug when rendering the [AWS config reference](https://www.nextflow.io/docs/latest/reference/config.html#aws):

Fix docs rendering on config page

---

docs/guides/aws-java-sdk-v2.md

Language suggestion for AWS Java SDK v2 guide

Update AWS Java SDK v2 guide

---

plugins/nf-amazon/src/main/nextflow/cloud/aws/nio/S3Client.java

Porting the nf-build-plugin, I have noted the download directory method implemented in the nf-amazon plugin is not checking if there are failed transfers. It could silently ignore failures in the transfers generated by the download directory in the S3 Transfer Manager. This check is already done when uploading a directory.
In this PR, the same mechanism is added for the download case. The CompleatedDirectoryDownload.failedTransfers() is inspected to check if there have been errors in the generated transfers.

Fix silent failure when downloading a directory with AWS SDK v2

---

modules/nextflow/src/test/groovy/nextflow/script/parser/v2/ScriptLoaderV2Test.groovy
modules/nf-lang/src/main/java/nextflow/config/control/ConfigToGroovyVisitor.java
modules/nf-lang/src/main/java/nextflow/config/control/VariableScopeVisitor.java
modules/nf-lang/src/main/java/nextflow/config/parser/ConfigAstBuilder.java
modules/nf-lang/src/main/java/nextflow/script/ast/ImplicitClosureParameter.java
modules/nf-lang/src/main/java/nextflow/script/control/ScriptToGroovyVisitor.java
modules/nf-lang/src/main/java/nextflow/script/control/VariableScopeVisitor.java
modules/nf-lang/src/main/java/nextflow/script/parser/ScriptAstBuilder.java

Fix #6237 
Fixes an issue with explicit `it` params. Also makes the detection of implicit `it` more precise.

Fix explicit `it` closure parameter

---

modules/nextflow/src/main/groovy/nextflow/scm/AzureRepositoryProvider.groovy
modules/nextflow/src/test/groovy/nextflow/cli/CmdConfigTest.groovy
modules/nextflow/src/test/groovy/nextflow/scm/AzureRepositoryProviderTest.groovy
modules/nextflow/src/test/groovy/nextflow/scm/GiteaRepositoryProviderTest.groovy

The AzureRepositoryProvider readBytes method appears to corrupt data for image files.
This PR contains 2 identical tests for a Gitea and Azure repo, both of which simple readBytes for an image in each and check whether the bytes returned are a valid image. The Gitea test passes whilst the Azure test fails.
The tests are currently set up with a public Gitea repo, so the existing auth should work for that. The azure repo is private, so will need changing to a repo which the current CI env has access to.

AzureRepositoryProvider readBytes corrupt 

---

docs/cache-and-resume.md

Revise the revisions to cache/resume docs

---

modules/nextflow/src/main/groovy/nextflow/trace/WorkflowStats.groovy
modules/nextflow/src/main/groovy/nextflow/trace/WorkflowStatsObserver.groovy
modules/nextflow/src/test/groovy/nextflow/trace/WorkflowStatsTest.groovy

Fix submitted count when aborting submitted tasks

---

modules/nextflow/src/main/groovy/nextflow/scm/ProviderConfig.groovy
modules/nextflow/src/test/groovy/nextflow/scm/GiteaRepositoryProviderTest.groovy
modules/nextflow/src/test/groovy/nextflow/scm/ProviderConfigTest.groovy

The old try.gitea.io free tier url has been superseded by gitea.com. This PR simply updates that default in the ProviderConfig.

feat: Updated Gitea ProviderConfig server default

---

docs/config.md
docs/reference/feature-flags.md
modules/nextflow/src/main/groovy/nextflow/script/parser/v2/ScriptCompiler.java
modules/nextflow/src/main/groovy/nextflow/script/parser/v2/ScriptLoaderV2.groovy
modules/nextflow/src/test/groovy/nextflow/script/parser/v2/ScriptLoaderV2Test.groovy
modules/nf-lang/src/main/java/nextflow/script/control/CallSiteCollector.java
modules/nf-lang/src/main/java/nextflow/script/control/ProcessNameResolver.java
modules/nf-lang/src/main/java/nextflow/script/dsl/FeatureFlagDsl.java

This PR extends the strict parser to resolve fully-qualified process names via static analysis -- including conditional processes.
This should eliminate any false warnings when validating process selectors. Thus we can deprecate the `nextflow.enable.configProcessNamesValidation` feature flag and move towards requiring all feature flags to be defined in the script.

Register fully-qualified process names at compile-time

---

modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy
modules/nextflow/src/test/groovy/nextflow/processor/TaskProcessorTest.groovy

close  #5470
Adds the CmdEvalParams in the task outputs as a key to compute the hash

Fix hash when CmdEvalParam as output

---

docs/config.md
docs/developer/plugins.md
docs/migrations/25-10.md
docs/notifications.md
docs/reference/syntax.md
modules/nf-lang/src/main/antlr/ScriptLexer.g4
modules/nf-lang/src/main/antlr/ScriptParser.g4
modules/nf-lang/src/main/java/nextflow/script/ast/ScriptVisitorSupport.java
modules/nf-lang/src/main/java/nextflow/script/ast/WorkflowNode.java
modules/nf-lang/src/main/java/nextflow/script/control/ScriptResolveVisitor.java
modules/nf-lang/src/main/java/nextflow/script/control/ScriptToGroovyVisitor.java
modules/nf-lang/src/main/java/nextflow/script/control/VariableScopeVisitor.java
modules/nf-lang/src/main/java/nextflow/script/formatter/ScriptFormattingVisitor.java
modules/nf-lang/src/main/java/nextflow/script/parser/ScriptAstBuilder.java
modules/nf-lang/src/test/groovy/nextflow/script/formatter/ScriptFormatterTest.groovy
tests/checks/.IGNORE-PARSER-V2
tests/workflow-oncomplete-v2.nf
validation/test.sh

This PR adds new syntax for workflow onComplete and onError as sections in the entry workflow instead of closure calls.
It also deprecates config workflow handlers, as this kind of code should be implemented in a plugin trace observer. This is better anyway since a plugin is easier to re-use across multiple pipelines.

Workflow onComplete and onError sections

---

modules/nextflow/src/main/groovy/nextflow/script/parser/v2/ErrorListener.groovy

This is a suggested fix for #6127 
I have not managed to build and test this with Gradle just yet, but seems it should work based on surrounding code, which does append the `.reset()` after changing color.

Reset terminal color after lint success/failure message

---

docs/azure.md

Azure Fusion using Managed Identity docs were wrong. This PR corrects to the right syntax and highlights this requires Fusion to use.

docs(Azure): Fusion docs correction

---

modules/nextflow/src/main/groovy/nextflow/extension/PublishOp.groovy
tests/checks/output-dsl.nf/.checks
tests/output-dsl.nf

Close #6340 
This PR fixes a bug where `normalizePath()` in `PublishOp` was not supplying the correct filename to the dynamic path closure.
It was supplying the simple file name instead of the path relative to the task directory, which caused an error when the file included a nested directory.
The `output-dsl.nf` e2e test has been updated to test this condition. The `summary` task is modeled after `multiqc` which creates nested output files.

Fix null reference error in workflow output

---

docs/reference/config.md

- Specify that only environment variables are exported, not credential files
- Add guidance for AWS SSO users to export credentials manually
- Include example command for aws configure export-credentials

Clarify fusion.exportStorageCredentials behavior [ci skip]

---

modules/nextflow/src/main/groovy/nextflow/config/Manifest.groovy
modules/nextflow/src/test/groovy/nextflow/config/ManifestTest.groovy

When a contributor in manifest.contributors omits the 'contribution' field, the code would attempt to call .stream() on null, causing a NullPointerException. Now defaults to empty list when contribution field is missing.
Fixes #6382

Fix NPE when contributors omit contribution field in manifest

---

plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerClient.groovy

Add defensive null checking for sender thread and workflowId to prevent NullPointerException when onFlowComplete is called after initialization failures in onFlowCreate or onFlowBegin methods.
- Add null checks for `sender` thread and `workflowId` in `TowerClient.onFlowComplete()`
- Prevents NullPointerException when Tower API rejects configuration with HTTP 400
- Fixes workflow failure cascade caused by early exit from `onFlowBegin` hook
When Nextflow encounters invalid configuration (e.g., https://github.com/nextflow-io/nextflow/issues/6382 ), the following cascade occurs:
1. Nextflow sends malformed configuration to Seqera Platform via `onFlowBegin` hook
2. Platform rejects configuration and returns HTTP 400 response  
3. nf-tower plugin receives 400 response and throws …

Add null checks in TowerClient onFlowComplete method
